loomio/loomio

- config/locales/en.yml
@robguthrie this is ready to go
> add username to simple_form translation text

- config/locales/frontpage.ru.yml
- config/locales/pt-BR.yml
- config/locales/ru.yml
- config/locales/sl.yml
- config/locales/sr-RS.yml
- config/locales/sr.yml
- config/locales/tr.yml
- config/locales/zh-TW.yml
I want to have a go deploying this
@gdpelican can you hold my hand ?
> locales update (ru, pt-BR, ru, sl, sr-RS, sr, tr, zh-TW)

- .translation_stats.yml
- config/locales/el.yml
- config/locales/mi.yml
- config/locales/ru.yml
- config/locales/sv.yml
hey @robguthrie this is ready. It's: 
- standard locale update
- inclusion of the new `.translation_stats.yml` in the app root, as [discussed previously](https://github.com/loomio/loomio/pull/1831)
> Translations update (ru, el,sv)

- config/locales/client.en.yml
- lineman/app/modules/discussion_page/proposals_card/proposal_expanded/proposal_expanded.haml
- lineman/app/modules/discussion_page/proposals_card/proposal_expanded/proposal_expanded.scss
- lineman/app/modules/discussion_page/proposals_card/proposal_expanded/proposal_expanded_controller.coffee
> Add toggle for showing votes on expanded proposal card

- lineman/app/templates/group_form.haml
> Disable group edit submit button while submitting

- app/views/discussions/show.xml.builder
- features/step_definitions/discussion_steps.rb
Add author uri entry to rss feed, for #1884
> Add author uri to discussion rss feed

- app/services/attachment_service.rb
- app/services/comment_service.rb
- app/services/contact_message_service.rb
- app/services/discussion_service.rb
- app/services/group_service.rb
- app/services/membership_service.rb
- app/services/motion_service.rb
- app/services/vote_service.rb
Fix deprecation warnings coming from service arguments
> Fix deprecation warnings for services

- config/loomio_i18n.yml
- lib/loomio_i18n.rb
in creating a node script for updating the locales it's become clear our locales config is based into some ruby.
I've extracted them into yaml, so that they are : 
- easier for node to read 
- easier for users to find and edit
> extract locale config into yml

- app/models/discussion.rb
- app/services/discussion_service.rb
- spec/services/discussion_service_spec.rb
Well I didn't mean to work on a beta feature, but this one lept out of the abyss and gnawed on me during some angular stuff. :whale:
> Fix for discussion title / description events not being published

- app/helpers/locales_helper.rb
This is a fix for not catching the locale of users that aren't signed in as discussed here: #1858
> Add detected locale for non-signed in users.

- db/migrate/20150218210234_fix_translation_indices.rb
- db/schema.rb
and replace with hopefully optimising index on association fields
> translations table: remove unsed,  error prone idx

- app/serializers/event_serializer.rb
- lineman/app/models/event_model.coffee
- lineman/app/modules/navbar/notification_items/user_mentioned.haml
Hook up notifications links
It'll be cool to revisit this after pagination is done, so we can look at how to make the anchors work properly.
:us:
> Link up notifications to urls

- app/views/groups/_form.html.haml
- features/groups/create_subgroup.feature
- features/step_definitions/create_subgroup_steps.rb
> Remove subgroup permissions option to create subgroups

- app/views/searches/_discussion_line_item.html.haml
- app/views/searches/_motion_line_item.html.haml
cherry picked version of this #1897
> Simple Fix to parse HTML in Search Results

- app/controllers/api/discussions_controller.rb
- app/controllers/api/events_controller.rb
- app/controllers/api/memberships_controller.rb
- app/controllers/api/motions_controller.rb
- app/controllers/api/notifications_controller.rb
- app/controllers/api/restful_controller.rb
- app/controllers/api/votes_controller.rb
I paired with my good friend Jim Beem on this one, but I still reckon it turned out pretty well. :tropical_drink:
> Generalize index action

- app/views/application/_heap_analytics.html.haml
they're going to deprecate the old script soon
> upgrade heap

- app/controllers/groups_controller.rb
- features/groups/create_subgroup.feature
- features/groups/start_new_group.feature
- features/step_definitions/create_subgroup_steps.rb
- features/step_definitions/start_new_group_steps.rb
> Example discussion for top-level groups created in app

- app/controllers/email_actions_controller.rb
- app/views/thread_mailer/_footer.html.haml
- app/views/thread_mailer/_footer.text.haml
- config/locales/en.yml
- config/routes.rb
- spec/controllers/email_actions_controller_spec.rb
controller test
no cuke 
no qa yet 
does need ? 
forgot charger ... in hurry
> add Follow action to emails. Fixes #1711

- app/models/user.rb
- app/views/base/_avatar.html.haml
- spec/models/user_spec.rb
a cherry-pick of this now messy pull request : https://github.com/loomio/loomio/pull/1903
> Resquashed commit of avatar thumbnail fix.

- app/views/discussions/_form.html.haml
- spec/extras/queries/visible_discussions_spec.rb
> Update subgroup discussion privacy message

- app/views/marketing/index.html.haml
add google site verification to activate Web Master Tools for better marketing knowledge
> meta google site verification

- app/controllers/api/votes_controller.rb
- app/models/permitted_params.rb
- app/serializers/current_user_serializer.rb
- config/locales/client.en.yml
- lineman/app/models/base_model.coffee
- lineman/app/models/comment_model.coffee
- lineman/app/models/discussion_model.coffee
- lineman/app/models/group_model.coffee
- lineman/app/models/proposal_model.coffee
- lineman/app/modules/discussion_page/comment_form/delete_comment.haml
- lineman/app/modules/discussion_page/comment_form/delete_comment_controller.coffee
- lineman/app/modules/discussion_page/comment_form/edit_comment.coffee
- lineman/app/modules/discussion_page/proposals_card/proposal_expanded/proposal_expanded.haml
- lineman/app/modules/discussion_page/thread_card/new_comment_item_controller.coffee
- lineman/app/modules/group_page/group_form_controller.coffee
- lineman/app/router.coffee
- lineman/app/services/comment_form_service.coffee
- lineman/app/services/proposal_form_service.coffee
Patches up some basic functionality for angular interface
> Basic functionality sweep

- app/helpers/application_helper.rb
- app/views/comments/edit.html.haml
- app/views/discussions/_add_comment.html.haml
- app/views/discussions/_form.html.haml
> Revert "provide minimum translation of markdown help"

- features/step_definitions/view_marketing_page_steps.rb
- features/view_marketing_page.feature
> Add cukes for viewing marketing page

- app/views/layouts/angular.html.haml
- lineman/app/modules/settings.scss
Had a few people venture into the angular interface and not know how to get out. So added this link
> add "turn off angular" link so stuck people can get out easily

- app/controllers/api/discussions_controller.rb
- lineman/app/modules/base.scss
- lineman/app/modules/dashboard_page/dashboard_page.haml
- lineman/app/modules/dashboard_page/dashboard_page.scss
- lineman/app/modules/dashboard_page/dashboard_page_controller.coffee
- lineman/app/modules/dashboard_page/dashboard_page_thread.haml
- lineman/app/modules/discussion_page/thread.scss
- lineman/app/modules/discussion_page/thread_card/thread_card.haml
- spec/controllers/api/discussions_controller_spec.rb
Incremental improvements to dashboard page
> Dashboard deux

- app/assets/javascripts/main.js.coffee
- app/views/application/_header.html.haml
- app/views/application/_user_profile_options.html.haml
- config/initializers/intercom.rb
> Revert "restore Intercom default messenger"

- lineman/app/services/message_channel_service.coffee
Seems live updating's been broken in prod for some time now. :wrench:
> Fix live updating for discussions

- config/locales/client.en.yml
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
> explain what the privacy and volume settings mean

- app/views/layouts/angular.html.haml
- lineman/app/app.coffee
- lineman/app/components/navbar/navbar_search.coffee
- lineman/app/components/navbar/navbar_search.haml
- lineman/app/services/key_event_service.coffee
Okay, this looks pretty good to me now. The angular / DOM interaction stuff is a bit suspect, but it does feel really nice to be able to arrow around the search interface.
Next step is to make the search dropdown scroll with the highlighted item.
> Infrastructure for key event service

- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/discussions_card/discussions_card_controller.coffee
- lineman/app/components/group_page/group_page.scss
> put a start thread button on the group page

- lineman/app/components/base.scss
- lineman/app/components/dropdown/dropdown.scss
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/navbar/navbar_notifications.haml
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/navbar/search_result.haml
- lineman/app/components/selector_list/selector_list.scss
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/thread_page.haml
All dropdowns work the same now, apart from the group privacy dropdown which is waiting to be turned into a form just like the volume dropdown.
> standardise hover states on all dropdowns

- config/locales/client.en.yml
- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/dashboard_page/dashboard_page.scss
- lineman/app/components/dropdown/dropdown.scss
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/navbar/navbar.haml
- lineman/app/components/navbar/navbar.scss
- lineman/app/components/navbar/navbar_notifications.haml
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
- lineman/app/components/selector_list/selector_list.scss
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/current_proposal_card/proposal_actions_dropdown/proposal_actions_dropdown.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/utilities.scss
Use %button for interactive elements, %a for links to a new page.
> distinguish buttons and links

- lineman/app/app.coffee
- lineman/app/components/proposal_redirect/proposal_redirect_controller.coffee
- lineman/app/components/thread_lintel/thread_lintel.coffee
- lineman/app/components/thread_page/activity_card/activity_card.coffee
- lineman/app/components/thread_page/activity_card/activity_card.haml
- lineman/app/components/thread_page/activity_card/activity_card.scss
- lineman/bower.json
- lineman/config/files.coffee
still need to set focus for screenreaders
> implement scroll to

- app/controllers/api/discussions_controller.rb
- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/discussions_card/discussions_card_controller.coffee
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/memberships_page/memberships_page_controller.coffee
- lineman/app/components/thread_page/activity_card/activity_card.coffee
- lineman/app/components/thread_page/activity_card/activity_card.haml
- lineman/app/models/discussion_records_interface.coffee
- lineman/app/models/group_model.coffee
Also incidentally fixes the activity card not display a loading symbol while it's loading
> Integrate loading service

- app/assets/stylesheets/unstructured/_pages.scss
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- config/locales/en.yml
Ready for smoke test and merge
> add welcome message to login screen. fix ToS message

- app/controllers/start_group_controller.rb
- db/migrate/20150410025815_add_is_referral_to_group.rb
- db/schema.rb
I think this is right but I have been a bit distracted so it needs a proper QA before deploy
> add is_referral to groups

- app/controllers/discussions_controller.rb
- config/locales/en.yml
- config/locales/pt-BR.yml
Hello Loomio Team, 
This is a simple commit for a message that was not included on languages YML files.
Thanks in advance.
> Updates on Translations

- .translation_coverage.yml
- config/locales/frontpage.hr.yml
- config/locales/frontpage.it.yml
- config/locales/help.hr.yml
- config/locales/help.hu.yml
- config/locales/help.pt-BR.yml
- config/locales/help.sr.yml
- config/locales/hu.yml
- config/locales/ml.yml
- config/locales/pt-BR.yml
> locale updated: hr, it, hu, pt-BR, sr, hu, ml

- app/extras/notification_item.rb
- app/models/comment.rb
- app/models/group.rb
- app/models/membership_request.rb
- app/services/message_channel_service.rb
- deploy.sh
commit ac7c99a927b9f9786358542774c7e3ce3b932244
Author: Robert Guthrie <rob@guthr.ie>
Date:   Mon Apr 13 12:07:25 2015 +1200
ok
commit 8f45a04327114844e21060c622827055d503fadc
Author: Robert Guthrie <rob@guthr.ie>
Date:   Mon Apr 13 11:09:51 2015 +1200
make sure deleting membership request deletes events -> notifications
commit e1775d12ef04413b97a6102495c4eca55bf07a7e
Author: Robert Guthrie <rob@guthr.ie>
Date:   Mon Apr 13 10:33:24 2015 +1200
fix
commit 9087a91fcef7fc69b8d97bced9c674349efed876
Author: Robert Guthrie <rob@guthr.ie>
Date:   Mon Apr 13 10:24:17 2015 +1200
bg
commit 14e987e85a9b0e1256776568aa883e242941c755
Author: Robert Guthrie <rob@guthr.ie>
Date:   Mon Apr 13 10:18:28 2015 +1200
lets see some debug
> squashin de bugz

- app/controllers/help_controller.rb
- app/views/comments/edit.html.haml
- app/views/discussions/_add_comment.html.haml
- app/views/discussions/_form.html.haml
- app/views/help/markdown.html.erb
- config/locales/help.en.yml
- config/routes.rb
The beginnings of a simple markdown tutorial.
> markdown help page. needs translation applied to the strings

- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown_controller.coffee
Converts group privacy dropdown to a form.
> Convert group privacy dropdown to form

- app/helpers/application_helper.rb
- spec/controllers/groups_controller_spec.rb
> Don't error when certain query parameters are passed when logged out

- config/locales/client.en.yml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/new_motion.haml
- lineman/app/components/thread_page/activity_card/new_vote.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page.scss
Some tweaks from DB's latest feedback. @robguthrie as soon as you get this merged I will send him another email.
> add labels to all articles

- app/assets/javascripts/print.js
- app/assets/javascripts/print_discussion.js.coffee
- app/assets/javascripts/tooltips.js.coffee
- app/assets/stylesheets/print.scss
- app/assets/stylesheets/unstructured/_avatar.scss
- app/assets/stylesheets/unstructured/_discussions.scss
- app/assets/stylesheets/unstructured/_motion_graph.scss
- app/assets/stylesheets/unstructured/_motions.scss
- app/assets/stylesheets/unstructured/_users.scss
- app/assets/stylesheets/unstructured/index.scss
- app/controllers/discussions_controller.rb
- app/helpers/discussions_helper.rb
- app/models/ability.rb
- app/views/discussions/_title.html.haml
- app/views/discussions/print.html.haml
- app/views/layouts/print.html.haml
- config/initializers/assets.rb
- config/locales/en.yml
- config/routes.rb
- spec/models/ability_spec.rb
> Print discussion

- lineman/app/components/navbar/navbar_user_options.coffee
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/thread_page/discussion_form/discussion_form_controller.coffee
- lineman/app/components/user_avatar/user_avatar.coffee
- lineman/app/components/user_avatar/user_avatar.haml
- lineman/app/components/user_avatar/user_avatar.scss
- lineman/app/models/discussion_model.coffee
This fixes the navbar dropdown and replaces the hamburger icon with your beautiful, beautiful face
> User options navbar fix

- app/controllers/admin/stats_controller.rb
- app/views/admin/stats/group_activity.html.haml
> Link to group from activity calculator

- .translation_coverage.yml
- config/locales/cs.yml
- config/locales/de.yml
- config/locales/el.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/hu.yml
- config/locales/nl-NL.yml
- config/locales/pt-BR.yml
- config/locales/zh-TW.yml
> locales update

- lineman/app/components/dropdown/dropdown.scss
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/utilities.scss
braindead so doing housekeeping
> BEM-ify group page

- app/assets/stylesheets/print.scss
- app/views/discussions/print.html.haml
> Add formatting to print page

- lineman/app/components/mixins.scss
- lineman/app/components/thread_preview_collection/thread_preview_collection.haml
- lineman/app/components/thread_preview_collection/thread_preview_collection.scss
- lineman/app/models/proposal_model.coffee
Highlight proposals closing soon, don't display closing at date on others on dashboard
> Proposal closing soon style

- config/initializers/intercom.rb
I feel like this is fine to merge but I haven't tested it
> send more params to intercom

- config/locales/en.yml
Fixes comment replied notification on loomio beta
> Add translation for beta comment replied to

- app/extras/username_generator.rb
- app/models/user.rb
- app/queries/username_conflicts_query.rb
- spec/extras/username_generator_spec.rb
Clean up the generate_username method on user, and run it before validation
> Generate username method cleanup

- app/controllers/api/discussion_readers_controller.rb
- app/controllers/api/events_controller.rb
- app/controllers/api/groups_controller.rb
- app/controllers/api/memberships_controller.rb
- app/controllers/api/motions_controller.rb
- app/controllers/api/restful_controller.rb
- app/controllers/api/votes_controller.rb
- app/extras/model_locator.rb
- spec/extras/model_locator_spec.rb
Hey I did this over the weekend because it was bugging me.
The API controllers are quite well tested, so it's a pretty low risk refactor imho.
> Add Model Locator class for loading via params

- app/controllers/angular_support_controller.rb
- app/controllers/api/discussions_controller.rb
- app/serializers/group_serializer.rb
- config/locales/client.en.yml
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/discussions_card/discussions_card_controller.coffee
- lineman/app/components/group_page/group_actions_dropdown/leave_group.haml
- lineman/app/components/group_page/group_actions_dropdown/leave_group_controller.coffee
- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/models/group_records_interface.coffee
- lineman/app/models/user_model.coffee
- lineman/spec/directives/activity_card_spec.coffee
- lineman/spec/directives/discussions_card_spec.coffee
- lineman/spec/helpers/directive.js
- lineman/spec/helpers/factory.js
- spec/controllers/api/discussions_controller_spec.rb
Please don't merge, I really need to write e2e tests for this.
> Messaging for empty discussions list on group page.

- app/extras/username_generator.rb
- app/models/user.rb
- spec/extras/username_generator_spec.rb
> fix username errors

- app/controllers/discussions_controller.rb
Considering this has in prod for a while now and we haven't seen it come through errbit, I'm pretty sure it's safe to take out.
> Remove discussions#index

- app/controllers/motions_controller.rb
- spec/controllers/motions_controller_spec.rb
- spec/services/motion_service_spec.rb
> Update outcome of proposal fix

- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/invitation_modal.haml
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/memberships_page/memberships_page.haml
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
- lineman/app/components/notifications/notifications.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.haml
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.haml
- lineman/app/components/thread_page/start_proposal_card/start_proposal_card.haml
- lineman/app/components/thread_page/vote_form/vote_form.haml
this is more correct.. and prevents a bug exibited by the screen jumping when you press "Like" on a comment
> use href='' rather than href='#'

- app/assets/stylesheets/unstructured/_groups.scss
- app/controllers/start_group_controller.rb
- app/views/start_group/new.html.haml
- config/locales/en.yml
- features/step_definitions/start_new_group_steps.rb
Logged in:
______________
Logged out:
> Update start group in rails

- lineman/app/models/group_model.coffee
- lineman/app/services/lmo_url_service.coffee
- lineman/spec/services/lmo_url_service_spec.coffee
Don't merge me just yet
This should add support for swapping around subdomains when navigating... will be interesting to test it out a little more in practice to see what further needs to be done.
> add subdomain support to LmoUrlService w/ specs

- app/views/layouts/angular.html.haml
- config/locales/client.en.yml
- lineman/app/components/mixins.scss
- lineman/app/components/start_menu/start_menu.coffee
- lineman/app/components/start_menu/start_menu.haml
- lineman/app/components/start_menu/start_menu.scss
- lineman/app/components/start_menu/start_menu_option.coffee
- lineman/app/components/start_menu/start_menu_option.haml
- lineman/app/components/thread_page/discussion_form/discussion_form_controller.coffee
- lineman/app/services/modal_service.coffee
> Angular start button

- lineman/app/components/mixins.scss
- lineman/app/components/star_toggle/star_toggle.scss
- lineman/app/components/start_menu/start_menu.scss
My dev environment is broken so this is untested but I'm pretty confident in these little css tweaks
> fix lintel and star alignment

- app/models/motion.rb
- app/views/motions/_motion.html.haml
- spec/models/motion_spec.rb
> try to fix incorrect voters count

- app/controllers/dashboard_controller.rb
- app/controllers/email_actions_controller.rb
- app/controllers/group_base_controller.rb
- app/controllers/groups_controller.rb
- app/controllers/inbox_controller.rb
- app/controllers/network_membership_requests_controller.rb
- app/controllers/networks_controller.rb
- app/controllers/users/sessions_controller.rb
- app/helpers/discussion_index_cache_helper.rb
- app/queries/thread_search_query.rb
Some quick refactoring I did on the plane wee! (Don't merge me yet)
> Spring cleaning

- db/migrate/20150618214752_add_memberships_index_wtf.rb
- db/schema.rb
- lineman/app/components/groups_page/groups_page.scss
- lineman/app/components/invitation_form/invitation_form.haml
- lineman/app/components/mixins.scss
- lineman/app/components/navbar/navbar.scss
- lineman/app/components/notifications/user_added_to_group.haml
- lineman/app/components/thread_page/comment_form/comment_form.scss
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.haml
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.scss
- lineman/app/components/thread_page/proposal_outcome_panel/proposal_outcome_panel.haml
@robguthrie here are your changes from this morning + couple wee css adjustments
> little style tweaks + perf improvement

- .translation_coverage.yml
- config/locales/es.yml
> small locale update (es)

- app/controllers/api/events_controller.rb
- app/extras/model_locator.rb
- lineman/app/components/thread_page/activity_card/activity_card.coffee
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/models/event_records_interface.coffee
- lineman/app/services/lmo_url_service.coffee
- lineman/app/services/scroll_service.coffee
- lineman/spec/services/lmo_url_service_spec.coffee
- spec/controllers/api/events_controller_spec.rb
> Comment from email

- app/controllers/api/memberships_controller.rb
- app/controllers/api/restful_controller.rb
- app/models/membership.rb
- app/models/permitted_params.rb
- app/serializers/membership_serializer.rb
- app/serializers/user_serializer.rb
- lineman/app/components/invitation_form/invitation_form.coffee
- spec/controllers/api/memberships_controller_spec.rb
Allow searching for users by email without serializing out their email addresses
> Membership by email

- lineman/app/components/group_page/discussions_card/discussions_card.coffee
- lineman/app/components/start_menu/start_menu.haml
- lineman/app/components/start_menu/start_menu_option.coffee
- lineman/app/services/key_event_service.coffee
Adds hotkey actions for start menu items
'T' for start a new thread
'G' for start a new group
'I' for invite people
> Add hotkeys for start menu actions

- app/views/layouts/angular.html.haml
- config/initializers/airbrake.rb
- deploy.sh
- lineman/app/app.coffee
- lineman/app/services/exception_handler.coffee
- lineman/config/files.coffee
> try to add js exception handling

- Gemfile
- Gemfile.lock
See https://github.com/ohler55/oj
> use oj for json serialization

- app/controllers/api/membership_requests_controller.rb
- app/controllers/development_controller.rb
- app/services/membership_request_service.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/app.coffee
- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/components/group_page/membership_requests_card/membership_requests_card.coffee
- lineman/app/components/group_page/membership_requests_card/membership_requests_card.haml
- lineman/app/components/group_page/membership_requests_card/membership_requests_card.scss
- lineman/app/components/membership_requests_page/membership_requests_page.haml
- lineman/app/components/membership_requests_page/membership_requests_page.scss
- lineman/app/components/membership_requests_page/membership_requests_page_controller.coffee
- lineman/app/components/user_avatar/user_avatar.coffee
- lineman/app/models/group_model.coffee
- lineman/app/models/membership_request_model.coffee
- lineman/app/models/membership_request_records_interface.coffee
- lineman/app/services/ability_service.coffee
- lineman/spec-e2e/helpers/groups_helper.coffee
- lineman/spec-e2e/helpers/membership_requests_helper.coffee
- lineman/spec-e2e/manage_membership_requests_spec.coffee
- spec/controllers/api/membership_requests_controller_spec.rb
- spec/factories.rb
- Need to use MembershipRequestsService in 'approve' controller action
- Need to extend MembershipRequestsService.approve to authorize with CanCan
> Membership requests

- app/controllers/development_controller.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/components/leave_group_form/leave_group_form.coffee
- lineman/app/components/leave_group_form/leave_group_form.haml
- lineman/app/components/navbar/navbar.haml
- lineman/spec-e2e/group_spec.coffee
- lineman/spec-e2e/helpers/groups_helper.coffee
- lineman/spec-e2e/helpers/memberships_helper.coffee
Also prevents last coordinator from leaving group. Code review appreciated!
> Add e2ez for leaving group

- lineman/app/components/navbar/navbar.scss
This was left out of my last PR in a last minute refactor
> Re-add float right for search div in navbar

- app/controllers/development_controller.rb
- app/serializers/comment_serializer.rb
- config/routes.rb
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/new_motion.haml
- lineman/app/components/thread_page/activity_card/new_vote.haml
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/thread_page/thread_page.scss
- lineman/spec-e2e/discussion_spec.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
This style is making our thread view look like crap and, after searching for a reason for it to be there for some amount of time, I couldn't find one. So let's ditch it. :tada:
> Fix thread actions spacing

- config/locales/client.en.yml
- lineman/app/components/flash/flash.haml
- lineman/app/components/flash/flash.scss
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form_controller.coffee
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form_controller.coffee
- lineman/app/components/thread_page/vote_form/vote_form.coffee
- lineman/spec-e2e/email_settings_spec.coffee
- lineman/spec-e2e/group_spec.coffee
@gdpelican, @robguthrie, could probs do with some eyez :eyes:
> Snackify flash messages

- .translation_coverage.yml
- config/locales/client.lt.yml
- config/locales/client.pl.yml
- config/locales/client.pt-BR.yml
- config/locales/frontpage.he.yml
- config/locales/frontpage.pl.yml
- config/locales/help.lt.yml
- config/locales/help.pl.yml
- config/locales/language_names.en.yml
- config/locales/lt.yml
- config/locales/native_language_names.yml
- config/locales/pl.yml
- config/loomio_i18n.yml
@robguthrie  translation updates 
Note, **Polish has completed 1.0**, and is going live in this deploy.
their current stats are : 
```diff
+  frontpage: 61
+  help docs: 11
+  main: 54
+  main_1_0: 100
```
@HSalmon you might want to reach out to the polish translator(s) and tell them what the process is. Tell them how to see their translations live, and that because the app is always evolving new translations will be added and old ones will be removed (so translation is an ongoing thing)
> Polish is LIVE

- lineman/app/components/groups_page/groups_page.haml
- lineman/app/components/groups_page/groups_page_controller.coffee
Wonder if anyone ever uses this button, heh.
> Fix new group button on groups page

- lineman/app/components/group_page/group_page.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page.scss
- lineman/app/components/utilities.scss
I tested with giant kitteh pix! :cat2:
> Fix overwidth markdown images

- lineman/app/components/navbar/navbar.scss
Avatar size has changed so this PR repads the container
> tweak avatar padding

- .translation_coverage.yml
- config/locales/client.es.yml
- config/locales/client.pl.yml
- config/locales/frontpage.lt.yml
- config/locales/frontpage.pl.yml
- config/locales/help.pl.yml
- config/locales/lt.yml
- config/locales/pl.yml
> locale update

- lineman/app/components/pie_chart/pie_chart.scss
- lineman/app/components/thread_preview_collection/thread_preview_collection.scss
Pie chart is still a bit buggy, but this makes it less buggy.
> css tweak to mini pie chart

- app/views/layouts/angular.html.haml
- lineman/app/components/mixins.scss
I love that we're versioning so much, I wanna show it to the world!
Also, since we're getting a bit closer to showing this to a slightly wider circle, thought the ugly pink thing in the corner could use just a little attention.
> Display version in-app

- README.md
- app/models/events/comment_replied_to.rb
- app/models/events/discussion_description_edited.rb
- app/models/events/discussion_title_edited.rb
- app/models/events/motion_close_date_edited.rb
- app/models/events/motion_closed.rb
- app/models/events/motion_closed_by_user.rb
- app/models/events/motion_description_edited.rb
- app/models/events/motion_name_edited.rb
- app/models/events/new_comment.rb
- app/models/events/new_discussion.rb
- app/models/events/new_motion.rb
- app/models/events/new_vote.rb
- app/models/memo.rb
- app/services/message_channel_service.rb
- lineman/app/app.coffee
- lineman/app/components/thread_preview/thread_preview.haml
- lineman/app/models/discussion_model.coffee
- lineman/app/models/discussion_reader_model.coffee
- lineman/app/services/message_channel_service.coffee
I think this is ready for review. Works well for me.. New discussions and comments come up for any discussions in my dashboard. Also notificaitons come up instantly too.
> All activity in your group happens live

- config/initializers/rack_attack.rb
@gdpelican is this ok to merge? Just wanna see more data.
> get more info from rack attack

- .translation_coverage.yml
- config/locales/client.da.yml
- config/locales/client.es.yml
- config/locales/client.it.yml
- config/locales/client.mi.yml
- config/locales/es.yml
- config/locales/help.es.yml
- config/locales/mi.yml
where it = italian
@robguthrie
> locales update - it mostly done in 1.0

- app/assets/stylesheets/email.scss
- app/serializers/user_serializer.rb
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/discussions_card/discussions_card.scss
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/group_page/members_card/members_card.scss
- lineman/app/components/group_page/subgroups_card/subgroups_card.scss
- lineman/app/components/inbox_page/inbox_page.haml
- lineman/app/components/inbox_page/inbox_page.scss
- lineman/app/components/mixins.scss
- lineman/app/components/notifications/membership_requested.haml
- lineman/app/components/selector_list/selector_list.scss
- lineman/app/components/thread_preview/thread_preview.haml
- lineman/app/components/thread_preview/thread_preview.scss
- lineman/app/components/thread_preview_collection/thread_preview_collection.scss
- lineman/app/components/user_avatar/user_avatar.haml
- lineman/app/components/utilities.scss
- lineman/spec-e2e/helpers/groups_helper.coffee
This little puppy is pretty much good to go.  (fixed ellipse issue) 
I really hope you all like this!!!  It was just about a whole days work.
- hover buttons are now positioned absolutely
- this allows longer titles
- increased font-weight of thread title to allow for smaller line-heights
- more text in less space
- voting icons are now visually associated with the pie.  Which helps understand what they mean.
- mobile experience is clearer too
iphone5:
iphone6:
> enlarge graph and layer position

- app/controllers/api/invitations_controller.rb
Tested this in the browser and it works, but it's hard to write tests because we still don't have a good method for checking the content of emails...maybe this is something we can look into?
> Fix invitation message bug

- lineman/app/components/discussion_form/discussion_form.haml
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/inbox_page/inbox_page.scss
- lineman/app/components/profile_page/profile_page.haml
- lineman/app/components/proposal_form/proposal_form.haml
sits on top of maxlength PR.. but it's only really 2 lines.
@gdpelican I've not tested this yet.. but is adding %validation_errors like so the only thing we need do to use that directive?
> Add validation to forms

- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form_controller.coffee
- lineman/spec-e2e/proposal_spec.coffee
Think this is the last of the missing flash messages
> Fix proposal outcome flash

- app/serializers/group_serializer.rb
- config/locales/client.en.yml
- lineman/app/components/archive_group_form/archive_group_form.haml
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/models/group_model.coffee
- lineman/app/models/group_records_interface.coffee
- lineman/app/models/user_model.coffee
- lineman/spec-e2e/group_spec.coffee
- lineman/spec-e2e/helpers/groups_helper.coffee
> Fix deactivate group

- lineman/app/components/navbar/navbar.coffee
- lineman/app/components/navbar/navbar.scss
> Fix broken underline on active page

- lineman/app/components/notifications/notification_controller.coffee
- lineman/app/components/proposal_form/closing_at_field.coffee
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.coffee
- lineman/app/services/message_channel_service.coffee
- lineman/spec/models/discussion_model_spec.coffee
Remove stay console.log statements (the subscribed response on MessageChannel is particularly rough.)
> Remove stray console logs

- lineman/app/components/archive_group_form/archive_group_form.haml
- lineman/app/components/deactivate_user_form/deactivate_user_form.haml
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/invitation_form/invitation_form.haml
- lineman/app/components/leave_group_form/leave_group_form.haml
- lineman/app/components/profile_page/profile_page.haml
- lineman/app/components/profile_page/profile_page.scss
- lineman/app/components/proposal_form/proposal_form.haml
- lineman/app/components/start_group_form/start_group_form.haml
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form.haml
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/thread_page/comment_form/comment_form.scss
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form.haml
Adds a nice white overlay to forms while they're processing.
> Disable forms while processing

- lineman/app/components/memberships_page/admin_memberships_panel/admin_memberships_panel_controller.coffee
These are careless mistakes, guys. I thought we had a test around adding / removing a coordinator?
> Fix toggle coordinator

- lineman/spec-e2e/helpers/memberships_helper.coffee
- lineman/spec-e2e/manage_memberships_spec.coffee
> Add e2ez for removing coordinator etc

- app/assets/stylesheets/unstructured/_pages.scss
- app/controllers/angular_controller.rb
- app/views/angular/index.html.haml
- app/views/application/_header.html.haml
- app/views/layouts/angular.html.haml
- config/locales/client.en.yml
TODO:
Only show "Try the new Loomio" to selected users.
Make sure the screen after that explains what the new Loomio is
In beta you will see:
Then:
Then:
Then:
> nice enough interface switcher

- Gemfile
- Gemfile.lock
just want to see if the tests pass.. cant remember where we use this.
> remove country select, where is it used? it takes 30megs of memory!

- Gemfile
- Gemfile.lock
- app/controllers/api/comments_controller.rb
- app/controllers/api/restful_controller.rb
I just wanna see if this passes..
> Extract restful controller

- app/controllers/development_controller.rb
- config/routes.rb
- lineman/app/components/groups_page/groups_page.haml
- lineman/app/components/groups_page/groups_page.scss
- lineman/app/components/groups_page/groups_page_controller.coffee
- lineman/app/models/group_records_interface.coffee
- lineman/spec-e2e/helpers/membership_requests_helper.coffee
- lineman/spec-e2e/manage_membership_requests_spec.coffee
...even when user is not member of parent group
> Ensure subgroups display on groups page

- lineman/app/components/utilities.scss
First attempt at Markdown header styles...@rdbartlett, @robguthrie
> Header styles first pass

- app/controllers/development_controller.rb
- config/locales/client.en.yml
- lineman/app/components/membership_requests_page/membership_requests_page.haml
- lineman/app/components/membership_requests_page/membership_requests_page.scss
- lineman/app/models/group_model.coffee
- lineman/spec-e2e/helpers/groups_helper.coffee
- lineman/spec-e2e/helpers/membership_requests_helper.coffee
- lineman/spec-e2e/manage_membership_requests_spec.coffee
> Add message when no pending membership requests

- app/serializers/comment_serializer.rb
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/models/comment_model.coffee
Remove empty comment authors when parent is not loaded
> Serialize parent author name with comment

- lineman/app/components/dashboard_page/dashboard_page.haml
[Trello card](https://trello.com/c/9SITwwSH/657-0-5-a11y-headings-on-dashboard)
Is this all there is @rdbartlett?
> Add h2 to dashboard

- lineman/app/components/change_password_form/change_password_form.haml
- lineman/app/components/contact_page/contact_page.haml
- lineman/app/components/discussion_form/discussion_form.haml
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/membership_request_form/membership_request_form.haml
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
- lineman/app/components/profile_page/profile_page.haml
- lineman/app/components/proposal_form/closing_at_field.haml
- lineman/app/components/proposal_form/proposal_form.haml
- lineman/app/components/start_group_form/start_group_form.haml
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form.haml
[Trello card](https://trello.com/c/oQEjV78v/650-2-a11y-forms-input-ids-for-labels)
> Add input ids for labels

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pricing_table.scss
- app/views/pages/pricing.html.haml
- config/locales/en.yml
> Add new pricing page

- app/views/admin/stats/aaarrr.html.haml
Hey @robguthrie I have just made a little tweak to make the AAARRR table more valuable. I know it is hacky, but it is cheap and useful. Soon we will be pulling this straight out of Chargify but this makes me happy for now :)
> tweak AAARRR

- app/controllers/base_controller.rb
- app/serializers/group_serializer.rb
- app/views/angular/_google_analytics.html.haml
- app/views/angular/_intercom.html.haml
- app/views/layouts/angular.html.haml
- lineman/app/app.coffee
- lineman/app/components/navbar/navbar_user_options.coffee
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/services/intercom_service.coffee
ready for review please. Tested and works.
> Add intercom to angular

- app/models/cohort.rb
- app/views/admin/stats/aaarrr.html.haml
I can't test this locally but I think it is good. @robguthrie can you verify?
> show retention of groups over time

- lineman/app/components/group_page/subgroups_card/subgroups_card.haml
I think bind once is a really dumb optimisation and developing a really good memoization system will be way better in the long run.
> this is why we were getting travis failures intermittantly

- app/views/application/_header.html.haml
moves from about ~336 users to about ~776 users
> double the audience for the Try New Loomio link

- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
Disable privacy form when privacy form is not useable
> Add disabled overlay to group privacy form

- app/controllers/api/groups_controller.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/components/flash/flash.coffee
- lineman/app/components/flash/flash.haml
- lineman/app/components/group_page/cover_photo_form/cover_photo_form.coffee
- lineman/app/components/group_page/cover_photo_form/cover_photo_form.haml
- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/components/group_page/logo_photo_form/logo_photo_form.coffee
- lineman/app/components/group_page/logo_photo_form/logo_photo_form.haml
- lineman/app/components/utilities.scss
- lineman/app/models/group_model.coffee
- lineman/app/services/form_service.coffee
- lineman/package.json
This feature rocks!
Would love to hear some feedback and get this bit ready to be merged so we can move on to default cover images
> Group images

- app/serializers/group_serializer.rb
- lineman/app/components/group_page/group_page.haml
- lineman/app/models/group_model.coffee
- Fix spacing issue (don't push down logo / title so far)
- Make subgroups display correct cover photo
> Minor fixes for group page cover photo

- config/locales/client.en.yml
- lineman/app/components/thread_page/comment_form/comment_form.haml
> link to markdown help page from comment form

- config/locales/client.en.yml
- lineman/app/components/invitation_form/invitation_form.haml
- lineman/app/components/invitation_form/invitation_form.scss
> Tidy form, make custom message field collapsible

- lineman/app/components/invitation_form/invitation_form.coffee
- lineman/app/components/invitation_form/invitation_form.haml
- lineman/spec-e2e/helpers/invitations_helper.coffee
- lineman/spec-e2e/invitations_spec.coffee
@gdpelican, would you mind taking a look?
> Fix invitation form add message button

- lineman/app/components/groups_page/groups_page.scss
[Trello card](https://trello.com/c/Rklb7sXl/700-underline-parent-groups-in-groups-page)
> Add underline to parent groups on groups page

- app/controllers/development_controller.rb
- config/routes.rb
- lineman/app/components/notification_volume/notification_volume_dropdown.coffee
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/new_comment.scss
- lineman/app/components/thread_page/activity_card/new_comment_item_controller.coffee
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/thread_page/proposal_positions/proposal_positions.scss
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.coffee
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/services/ability_service.coffee
- lineman/spec-e2e/discussion_spec.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
Still writing tests but could maybe do with preliminary review?
[Trello card](https://trello.com/c/VdXrTc9p/677-hide-members-actions-from-non-members-e-g-comment-like-reply-on-public-threads)
> Hide member actions from visitors

- lineman/app/services/ability_service.coffee
Eeeeep, sorry, I think I broke this when I hid the member actions from visitors
> Hide start proposal button when active proposal

- app/controllers/api/discussions_controller.rb
- app/controllers/development_controller.rb
- app/models/ability.rb
- app/services/discussion_service.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/components/move_thread_form/move_thread_form.coffee
- lineman/app/components/move_thread_form/move_thread_form.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/models/discussion_model.coffee
- lineman/app/services/ability_service.coffee
- lineman/app/services/form_service.coffee
- lineman/spec-e2e/discussion_spec.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
- spec/controllers/api/discussions_controller_spec.rb
- spec/services/discussion_service_spec.rb
Now with testing!
--------------
--------------
> Move discussion

- lineman/app/components/thread_page/vote_form/vote_form.coffee
- lineman/app/components/thread_page/vote_form/vote_form.haml
thanks to @gdpelican for the mighty FormService
> use formservice on vote form so it disables on submit

- app/controllers/pages_controller.rb
- app/views/application/_heap_analytics.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/pages.html.haml
- app/views/marketing/index.html.haml
(untested)
after deploy:
- remove Heap ID from ENV 
- update Third Party Privacy thread to let folks know we have closed another third party data pipe
> remove heap

- app/controllers/api/events_controller.rb
- app/controllers/base_controller.rb
- app/helpers/discussions_helper.rb
- app/models/discussion.rb
- app/services/discussion_service.rb
- lineman/app/components/thread_page/activity_card/activity_card.coffee
- spec/models/discussion_spec.rb
Fix unwieldy unread count for threads
> Inbox reliableness

- lineman/app/components/dashboard_page/dashboard_page.scss
- lineman/app/components/group_page/group_theme/group_theme.haml
- lineman/app/components/group_page/group_theme/group_theme.scss
- lineman/app/components/inbox_page/inbox_page.scss
- lineman/app/components/mixins.scss
- lineman/app/components/navbar/navbar.scss
- lineman/app/components/notifications/membership_requested.haml
- lineman/app/components/thread_page/activity_card/new_comment.scss
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/thread_page/thread_page.scss
- lineman/app/components/thread_preview/thread_preview.scss
- lineman/app/components/utilities.scss
* link group logo to group on thread page
* tidy up markdown styles: list + blockquote + headings
* fix margins on thread items
* remove broken group logo from membership request notification
* make all the icons in the user dropdown line up
**Before:**
**After:**
---
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
> Little style fixes

- app/views/thread_mailer/_motion.html.haml
- app/views/thread_mailer/_motion_with_positions.html.haml
- app/views/thread_mailer/new_motion.html.haml
I have not tested this but I think it is good. Can someone smoke it please?
> render proposal descriptions with Markdown in emails

- app/controllers/contact_messages_controller.rb
- app/views/contact_messages/new.html.haml
- lineman/app/components/navbar/navbar_user_options.coffee
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/services/intercom_service.coffee
> Add contact us option to user dropdown

- lineman/app/components/discussion_form/discussion_form.coffee
- lineman/app/components/discussion_form/discussion_form.haml
Now shows the correct privacy form in new thread and edit thread form
> Fix thread privacy form

- app/mailers/base_mailer.rb
- app/mailers/group_mailer.rb
- app/mailers/invite_people_mailer.rb
- app/mailers/thread_mailer.rb
- app/mailers/user_mailer.rb
- app/models/events/motion_closed.rb
- app/models/events/motion_closing_soon.rb
- app/models/events/motion_outcome_created.rb
- app/models/events/new_comment.rb
- app/models/events/new_discussion.rb
- app/models/events/new_motion.rb
- app/models/events/new_vote.rb
Just want to see how this fares in test land; not quite ready for review yet.
> Allow email interceptors to be defined

- lineman/app/services/message_channel_service.coffee
@gdpelican tiny typo in otherwise wonderful work. FYI then forget.
> use correct method to subscribe to message channel

- app/views/application/_header.html.haml
* Signed up more than 120 days ago and active this month: 5,926 people
* Signed up more than 14 days ago and active this month: 9,927 people
> show Try New Loomio link to more people

- lineman/app/components/base.scss
- lineman/app/components/group_page/discussions_card/discussions_card.scss
- lineman/app/components/group_page/group_help_card/group_help_card.haml
- lineman/app/components/mixins.scss
- lineman/app/components/proposal_accordian/proposal_accordian.scss
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.scss
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.scss
- lineman/app/components/thread_page/thread_page.scss
- lineman/app/components/utilities.scss
Rich and I went through and did a bunch of text styling changes. 
Please merge so that RDB can keep going on the timestamp stuff.
Cheers!
> Typography

- lineman/app/components/thread_page/activity_card/discussion_edited.haml
- lineman/app/components/thread_page/activity_card/motion_closed.haml
- lineman/app/components/thread_page/activity_card/motion_closed_by_user.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_created.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_updated.haml
- lineman/app/components/thread_page/activity_card/new_motion.haml
- lineman/app/components/thread_page/activity_card/new_vote.haml
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/utilities.scss
> Inline timestamps

- lineman/app/components/proposal_closing_time/proposal_closing_time.haml
- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.haml
- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.scss
> inline timestamp on collapsed proposal

- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/utilities.scss
> different margins on different screens

- lineman/app/components/thread_preview/thread_preview.scss
Good to merge.
Bad Rich, forgot to check how the new star positioning would look with long lines, even though you Rob told me to. Fixed now :)
> add margin to thread preview to handle new star positioning

- lineman/app/components/mixins.scss
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.haml
- lineman/app/components/thread_page/proposal_outcome_panel/proposal_outcome_panel.haml
- lineman/app/components/thread_page/proposal_pie_chart/proposal_pie_chart.scss
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- lineman/app/components/utilities.scss
> Fix proposal legend for mobile, update design

- app/models/motion.rb
- features/motions/proposal_outcome.feature
- features/step_definitions/close_elapsed_motions_steps.rb
- features/step_definitions/notifications_steps.rb
- features/step_definitions/user_steps.rb
- lineman/app/components/proposal_form/closing_at_field.coffee
- lineman/app/components/proposal_form/closing_at_field.haml
- lineman/app/components/thread_page/extend_proposal_form/extend_proposal_form.haml
- lineman/app/components/thread_page/extend_proposal_form/extend_proposal_form_controller.coffee
- lineman/app/services/ability_service.coffee
- spec/controllers/api/motions_controller_spec.rb
- spec/models/motion_spec.rb
validate proposal closing in future if open.
fix time select am/pm.
fix permission for canEditProposal so "change closing time" dropdown action is available at the right time
> fix proposal closing at issues

- lineman/app/components/group_page/group_volume_card/group_volume_card.coffee
- lineman/app/components/group_page/group_volume_card/group_volume_card.haml
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
@gdpelican just wanted to share that we don't want to use angular single binding.. it always ends up ruining things in my experience, and the perf improvement is not measurable.
You probably knew this but wanted to be sure. 
Also I'm finding that putting records directly onto the scope is just as bad as single binding for causing these timing issues. If we access records via methods on the scope then we don't have to check that 'membershipsLoaded' has happened etc.
> fix issues with async timing

- lineman/app/components/edit_group_form/edit_group_form.coffee
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/start_group_form/start_group_form.coffee
- lineman/app/components/start_group_form/start_group_form.haml
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/services/form_service.coffee
- lineman/app/services/key_event_service.coffee
- Also applies FormService to comment form
> Fix cmd + enter for forms, expand submit on enter to group forms

- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/timeago/timeago.coffee
No styling..  it only shows underline on hover (pictured) @rdbartlett ?
> link to comment via timestamp

- config/locales/client.en.yml
- config/locales/en.yml
- lineman/app/components/email_settings_page/email_settings_page.scss
- lineman/app/components/flash/flash.scss
- lineman/app/components/mixins.scss
- lineman/app/components/utilities.scss
Before
=====
After
====
Other stuff
========
* fixed a bit of alignment trouble at /email_preferences
* added really gentle animation to flash messages and the feedback card. I wanted to understand a bit about how angular & animation work
> Onboarding language & formatting tweaks

- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.scss
> Fix the error of my ways

- lineman/app/app.coffee
Now we need to find where animations occur so we can add the "animated" class.
Check http://www.bennadel.com/blog/2935-enable-animations-explicitly-for-a-performance-boost-in-angularjs.htm for details
> big performance win: Only animate elements with animated class (not ready)

- app/models/webhooks/slack/base.rb
- lineman/app/components/proposal_accordian/proposal_accordian.coffee
- lineman/app/components/proposal_form/proposal_form.coffee
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form_controller.coffee
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.haml
- lineman/app/models/discussion_model.coffee
With active proposal:
With recent closed proposal:
> Expand latest proposal on thread page

- app/services/message_channel_service.rb
> fix a whoopse with message channel name/model confusion

- lineman/app/components/group_page/group_theme/group_theme.haml
[Trello card](https://trello.com/c/hZCpK0ZW/945-hide-update-coverphoto-logo-box-from-nonadmins)
> Ensure grey box does not display for non-admins

- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
fix for when dashboard says "you have no recent threads"
> fix dashboard race condition

- lineman/app/components/thread_page/activity_card/thread_item.scss
> Fix timestamp padding

- lineman/app/components/contact_page/contact_page.haml
- lineman/app/components/deactivate_user_form/deactivate_user_form.haml
- lineman/app/components/thread_page/proposal_outcome_panel/proposal_outcome_panel.haml
- lineman/app/css/1_buttons.scss
added a couple of missing classes;
shifted cancel button to the left:
> button tweak

- app/models/model_cache.rb
- app/queries/thread_search_query.rb
- spec/controllers/api/search_results_controller_spec.rb
These are minor improvements, but have made me excited about building the search results page, and putting in some advanced search functionality as we find it necessary.
I've tweaked the search weights so that discussion title is king, and comment bodies are very low valued (primarily so that they show up if there's nothing else, but they won't outweigh anything else if it exists)
> Search improvements

- app/models/comment.rb
- app/serializers/comment_serializer.rb
- app/services/comment_service.rb
- lineman/app/app.coffee
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/comment_form/edit_comment_form.coffee
- lineman/app/models/comment_model.coffee
- spec/services/comment_service_spec.rb
Hi, this is a much saner way to detect and render @mention links.
> Fix at mention inconsistency on angular

- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.haml
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.scss
> remove started at and add proposal perma link

- lineman/app/components/thread_page/comment/attachment.scss
@rdbartlett can you pls review?
Before
=====
After
====
> Improve the look of attachments

- lineman/app/models/discussion_model.coffee
@rdbartlett this fixes the lag. I'll deploy after tests pass
> fix mark as read lag

- lineman/app/components/user_page/user_page.scss
- lineman/app/css/1_utilities.scss
> remove outline from user page h1

- config/locales/client.en.yml
- lineman/app/components/group_page/group_welcome_modal/group_welcome_modal.coffee
- lineman/app/components/group_page/group_welcome_modal/group_welcome_modal.haml
- lineman/app/components/group_page/group_welcome_modal/group_welcome_modal.scss
> Add video to welcome modal

- lineman/app/app.coffee
> Fix oversanitized translate parameters

- config/locales/client.en.yml
- lineman/app/components/angular_feedback_card/angular_feedback_card.coffee
- lineman/app/components/angular_feedback_card/angular_feedback_card.haml
- lineman/app/components/angular_feedback_card/angular_feedback_card.scss
- lineman/app/css/0_mixins.scss
- lineman/app/css/1_layout.scss
Thread page:
Group page:
Inbox:
Expanded:
> Feedback 2.0

- lineman/app/models/group_model.coffee
> Bring it closer

- app/views/motions/_motion.html.haml
- app/views/motions/_motion_preview.html.haml
- app/views/motions/_outcome_statement.html.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_created.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_updated.haml
- lineman/app/components/thread_page/proposal_outcome_panel/proposal_outcome_panel.haml
Renders proposal texts as markdown :)
> Markdown proposal

- app/models/events/comment_replied_to.rb
> check email_when_mentioned before sending replied to you email

- Gemfile
- Gemfile.lock
- app/controllers/api/memberships_controller.rb
- app/extras/queries/visible_discussions.rb
- app/extras/queries/visible_motions.rb
- app/models/concerns/beta_features.rb
- app/models/concerns/deprecated_group_features.rb
- app/models/user.rb
- app/serializers/group_serializer.rb
- app/services/discussion_reader_cache.rb
- config/environments/development.rb
- spec/extras/discussion_items/discussion_description_edited_spec.rb
- spec/extras/discussion_items/discussion_title_edited_spec.rb
- spec/extras/discussion_items/motion_close_date_edited_spec.rb
- spec/extras/discussion_items/motion_closed_by_user.spec.rb
- spec/extras/discussion_items/motion_closed_spec.rb
- spec/extras/discussion_items/new_discussion_spec.rb
- spec/extras/discussion_items/new_motion_spec.rb
- spec/extras/discussion_items/new_vote_spec.rb
- spec/models/user_spec.rb
Fix N+1 / unused eager loading queries as suggested by bullet
> Perf improvements

- lineman/app/components/inbox_page/inbox_page_controller.coffee
- lineman/app/models/user_model.coffee
[Trello card](https://trello.com/c/s7NW4mlH/941-unread-bug)
> Fix subgroups unread bug

- lineman/app/components/group_page/discussions_card/discussions_card.coffee
- lineman/app/services/loading_service.coffee
> Fix experience for subgroup member visiting parent they're not a member of

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/marketing/splash.scss
- app/controllers/marketing_controller.rb
- app/models/blog_story.rb
- app/views/marketing/_story.html.haml
- app/views/marketing/index.html.haml
- db/migrate/20151118012830_create_blog_stories.rb
- lib/tasks/loomio.rake
- spec/factories.rb
- spec/models/blog_story_spec.rb
[Trello card](https://trello.com/c/ON6rsMTN/954-5-display-stories-on-homepage)
> Add stories to marketing page

- app/admin/subscriptions.rb
- app/models/subscription.rb
@mhjb Watch the PR, once it gets merged into master I'd like to smoke test it on clone / test to make sure that it meets your needs alright before we deploy
> Fix admin subscription handling

- app/controllers/redirect_controller.rb
- spec/controllers/redirect_controller_spec.rb
not ready but we gotta fix the redirect controller after i broken it
> add redirect controller spec

- app/models/event.rb
- spec/models/events/new_motion_spec.rb
> Don't send slack webhooks to parent group

- app/controllers/api/discussions_controller.rb
- app/controllers/api/events_controller.rb
- app/controllers/api/motions_controller.rb
- app/controllers/api/restful_controller.rb
- app/controllers/api/votes_controller.rb
- lineman/app/components/group_page/group_previous_proposals_card/group_previous_proposals_card.coffee
- lineman/app/components/previous_proposals_page/previous_proposals_page.coffee
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- lineman/app/components/thread_page/proposals_card/proposals_card.coffee
- lineman/app/models/vote_records_interface.coffee
- spec/controllers/api/votes_controller_spec.rb
Allow filtering by group and discussion for my_votes action on votes_controller
More better than #2766
> More proper fix for my votes not appearing

- config/locales/client.en.yml
Okay @rdbartlett ?
I can't test it as I haven't got a working dev environment at ze mo.
> Make gift card language more about the groups doing cool stuff

- app/models/discussion_reader.rb
- app/serializers/discussion_serializer.rb
- app/serializers/simple/discussion_serializer.rb
- app/services/discussion_service.rb
- spec/models/discussion_reader_spec.rb
Am I nuts? I think this might be all we need to make live updating of read content work across tabs.
I'm going to spin up a faye server later hopefully and give this a spin.
> Live update mark as read

- lib/tasks/bootstrap.rake
Good day, 
James invited me to contribute to project and I got annoyed by project setup process. As a developer, I can managed with most of those annoyances, but it's impossible to create user from interface and there is not a single mention about that in a documents. Dropping to console just to do that seemed like a horrible hack. 
So, i've decided to create this 'bootstrap' task. In ideal world it would automatically set everything up and lunch the project. But current version has some limitations (installing ruby, which is managed by rbenv/rvm, bundler gem, npm and PG database).
i've hacked this together in couple of hours i've had free. And decided to put this for discussion as a Pull Request, i'm not really sure if this is needed for a project and if i should continue my work on …
> Bootstrap task: installing dependencies and lunching project with one line (hopefully)

- app/assets/javascripts/angular_ahoy.js
- app/controllers/development_controller.rb
- app/helpers/angular_helper.rb
- app/views/layouts/angular.html.haml
- config/initializers/assets.rb
- lineman/app/components/group_page/subscription_success_modal/subscription_success_modal.coffee
- lineman/app/components/legacy_trial_expired_modal/legacy_trial_expired.coffee
- lineman/app/services/ahoy_service.coffee
- lineman/app/services/modal_service.coffee
Track activity with our own tracking server, Ahoy. I expect we can remove Ahoy from the Loomio code tomorrow, running it own it's own app.
> Track encouragement

- app/controllers/api/translations_controller.rb
- app/extras/model_locator.rb
- app/helpers/angular_helper.rb
- app/serializers/translation_serializer.rb
- app/serializers/user_serializer.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/new_comment_item_controller.coffee
- lineman/app/components/thread_page/activity_card/new_vote.haml
- lineman/app/components/thread_page/activity_card/new_vote_item_controller.coffee
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.coffee
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/components/translate_button/translate_button.coffee
- lineman/app/components/translate_button/translate_button.haml
- lineman/app/components/translate_button/translate_button.scss
- lineman/app/components/translation/translation.coffee
- lineman/app/components/translation/translation.haml
- lineman/app/components/translation/translation.scss
- lineman/app/css/1_buttons.scss
- lineman/app/models/records.coffee
- lineman/app/models/translation_model.coffee
- lineman/app/models/translations_records_interface.coffee
- lineman/app/services/ability_service.coffee
- lineman/app/services/translation_service.coffee
Raised this baby from the grave last night on a whim, and didn't take too much work to get it going again.
Don't merge me yet, but I think it'll be cool to do a little work on getting everything translatable and get it in there.
Also, a gif:
http://g.recordit.co/9G1I2q0H30.gif
> Inline translation

- lineman/app/components/navbar/navbar.scss
> Red notifications badge, border around both badges

- config/locales/client.en.yml
- lineman/app/components/memberships_page/admin_memberships_panel/admin_memberships_panel.haml
- lineman/app/components/thread_page/activity_card/discussion_edited.haml
- lineman/app/components/thread_page/activity_card/motion_closed_by_user.haml
- lineman/app/components/thread_page/activity_card/motion_edited.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_created.haml
- lineman/app/components/thread_page/activity_card/motion_outcome_updated.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/activity_card/new_comment.scss
- lineman/app/components/thread_page/activity_card/new_motion.haml
- lineman/app/components/thread_page/activity_card/new_vote.haml
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/app/components/thread_page/proposal_positions/proposal_positions.scss
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- lineman/app/models/comment_model.coffee
[Trello card](https://trello.com/c/PGqPVdTk/1135-link-authors-to-profile-page)
> Link actors to profile in thread

- app/controllers/api/message_channel_controller.rb
- app/models/ability.rb
- app/models/concerns/message_channel.rb
- app/models/discussion.rb
- app/models/global_message_channel.rb
- app/models/group.rb
- app/models/user.rb
- app/services/message_channel_service.rb
- config/locales/client.en.yml
- config/routes.rb
- lib/tasks/deploy.rake
- lib/tasks/loomio.rake
- lineman/app/components/flash/flash_service.coffee
- lineman/app/services/boot_service.coffee
- lineman/app/services/message_channel_service.coffee
- spec/services/message_channel_service_spec.rb
Notify users on update that they should refresh:
(it's not that pretty... but it works!)
> Global message channel

- config/locales/client.en.yml
- config/locales/en.yml
- lineman/app/components/group_page/trial_card/choose_plan_modal/choose_plan_modal.haml
- lineman/spec-e2e/subscription_spec.coffee
Before | After
--- | ---
@rdbartlett
> Pricing language tweaks; remove broken get in touch link

- config/locales/client.en.yml
- lineman/app/components/memberships_page/admin_memberships_panel/admin_memberships_panel.haml
- lineman/app/components/memberships_page/memberships_panel/memberships_panel.haml
- lineman/app/components/memberships_page/pending_invitations_card/pending_invitations_card.coffee
- lineman/app/components/memberships_page/pending_invitations_card/pending_invitations_card.haml
- lineman/app/components/memberships_page/pending_invitations_card/pending_invitations_card.scss
[Trello card with designs](https://trello.com/c/lDApiXvC/1136-add-date-to-pending-invitations)
> Add date to pending invitations, improve formatting

- config/locales/client.en.yml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/models/comment_model.coffee
@robguthrie, I think this should do the trick
> Remove link for recipient of comment reply

- lineman/app/components/group_page/subgroups_card/subgroups_card.haml
> Order subgroups by name on subgroup card

- app/models/motion.rb
- app/models/vote.rb
- app/serializers/motion_serializer.rb
- app/services/motion_service.rb
- db/migrate/20151211044552_add_members_not_voted_count.rb
- db/schema.rb
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- lineman/app/models/proposal_model.coffee
- spec/controllers/api/motions_controller_spec.rb
- spec/models/motion_spec.rb
> Hide panel when no undecided members

- lineman/app/css/1_utilities.scss
@mhjb @rdbartlett Am I crazy for doing this?
For #2816
> Disallow manual text area resize

- app/models/events/comment_replied_to.rb
- spec/models/events/comment_replied_to_spec.rb
> Don't email the parent author if it's the same as the comment author

- app/controllers/api/translations_controller.rb
For http://errbit.loomio.org/apps/550f39ab5b229ba9b8000002/problems/5674b4a2e305f7d2aa000177
> Don't error if translation yml file not found

- lib/tasks/bootstrap.rake
I decided to create a last pull request to loomio project this year to fix couple of wording mistakes I made myself :)
Happy new year loomio team :P
> fixing wording mistakes in bootstrap.rake file

- app/controllers/api/attachments_controller.rb
- app/models/ability.rb
- app/services/attachment_service.rb
- spec/controllers/api/attachments_controller_spec.rb
> 403 on logged out user creating attachment

- app/controllers/api/translations_controller.rb
- spec/controllers/api/translations_controller_spec.rb
Sometimes we were responding with the wrong locale translation for inline translations
> Inline translation locale

- lineman/app/components/proposal_form/proposal_form.coffee
- lineman/app/components/proposal_form/proposal_form.haml
- lineman/app/models/draft_model.coffee
- lineman/app/models/draftable_model.coffee
- lineman/app/models/proposal_model.coffee
> Allow storing of drafts for proposals

- app/admin/subscriptions.rb
...that was easier than I thought.
> Allow deleting subscriptions from admin

- lineman/app/components/discussion_form/discussion_form.coffee
- lineman/app/components/discussion_form/discussion_form.haml
> Update privacy message on group change for thread form

- lineman/app/models/proposal_model.coffee
> Fix misnamed count

- lineman/app/components/attachment_preview/attachment_preview.scss
> Fix big images for FF users

- lineman/app/components/thread_page/activity_card/new_comment_item_controller.coffee
- lineman/app/models/comment_records_interface.coffee
Instantly update UI to show liked-ness:
http://g.recordit.co/e1VtMi370A.gif
If the request fails, revert to previous state:
http://g.recordit.co/PKUbx28BiF.gif
(Error message would be good, but happy with this for now.)
> Instalike!

- app/models/ability.rb
http://errbit.loomio.org/apps/550f39ab5b229ba9b8000002/problems/569f198de305f76f5f000114
> Ensure group exists for validating discussion creation

- config/locales/client.en.yml
- lineman/app/components/group_page/group_help_card/group_help_card.haml
@robguthrie, not entirely sure of the best way to proceed here...Nati said she's up for adding the appropriate links on Transifex, and communicating with the other translators (to ensure they don't try and translate the link)...does that sound like an ok course of action?
> Add translation key for blog links

- app/controllers/groups/memberships_controller.rb
- config/locales/client.en.yml
- lineman/app/services/privacy_string_service.coffee
- spec/controllers/groups/memberships_controller_spec.rb
[Trello card](https://trello.com/c/qHUJr5wY/1158-3-member-visibilty)
[PR for update to help manual](https://github.com/loomio/user-manual/pull/23)
> Update group privacy language to reflect reality

- .gitignore
- .travis.yml
- angular/tasks/paths.coffee
- app/helpers/angular_helper.rb
- app/views/layouts/angular.html.haml
- lib/tasks/deploy.rake
- lib/tasks/travis.rake
- lib/tasks/travis_upload_screenshots.rb
move assets to `/client/{version}/` folder for deployed (test / production) environments
> Build system improvements

- angular/core/components/group_page/gift_card/gift_card.coffee
- angular/core/components/group_page/group_page_controller.coffee
- angular/core/components/group_page/trial_card/choose_plan_modal/choose_plan_modal.coffee
- angular/core/components/group_page/trial_card/donation_modal/donation_modal.coffee
- angular/core/services/chargify_service.coffee
- app/helpers/angular_helper.rb
> Pull chargify params out into service; use unique reference

- angular/core/components/invitation_form/team_link_modal/team_link_modal.haml
- angular/test/protractor/invitations_spec.coffee
Fix for https://github.com/loomio/loomio/issues/2926
> Fix broken copy functionality for team link

- angular/core/components/thread_page/activity_card/new_comment.haml
- angular/core/components/thread_page/activity_card/new_comment_item_controller.coffee
- angular/core/components/thread_page/activity_card/thread_item.scss
- angular/core/components/thread_page/revision_history_modal/revision_history_modal.coffee
- angular/core/components/thread_page/revision_history_modal/revision_history_modal.haml
- angular/core/components/thread_page/revision_history_modal/revision_history_modal.scss
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/models/comment_model.coffee
- angular/core/models/discussion_model.coffee
- angular/core/models/user_model.coffee
- angular/core/models/version_model.coffee
- angular/core/models/version_records_interface.coffee
- angular/test/protractor/discussion_spec.coffee
- app/controllers/api/restful_controller.rb
- app/controllers/api/versions_controller.rb
- app/models/comment.rb
- app/models/discussion.rb
- app/serializers/comment_serializer.rb
- app/serializers/discussion_serializer.rb
- app/serializers/version_serializer.rb
- config/initializers/event_bus.rb
- config/locales/client.en.yml
- config/routes.rb
- db/migrate/20160209032652_add_version_count_to_discussion.rb
- db/migrate/20160210023408_add_versions_count_to_comments.rb
- db/schema.rb
- lib/tasks/loomio.rake
> Add revision history for discussion title and context

- app/views/discussions/print.html.haml
I couldn't find a spec for this so I hope you'll forgive me if I don't add one :)
Also Emojis don't work yet but it looks like [you're already aware of that](https://github.com/loomio/loomio/commit/dac61c8e58dee0454e6b2f9f06e4b0c9a3a6ea67).
> Render Markdown in print version

- angular/core/components/group_form/group_form.haml
- angular/core/components/start_menu/start_menu.haml
- angular/core/components/start_menu/start_menu.scss
- angular/core/components/start_menu/start_menu_option.haml
- angular/core/models/group_model.coffee
- angular/core/services/privacy_string_service.coffee
- angular/test/protractor/group_spec.coffee
- app/controllers/development_controller.rb
- config/locales/client.en.yml
I'm writing tests and fixing the behaviour of group form. This is the first part.
I'll add more to this PR as I go.
> add e2es to group form

- angular/core/components/group_form/group_form.haml
- config/locales/client.en.yml
> Add placeholders to in-app start new group form

- angular/core/components/discussion_form/discussion_form.coffee
- angular/core/components/discussion_form/discussion_form.haml
- angular/core/components/emoji_picker/emoji_picker.coffee
- angular/core/components/proposal_form/proposal_form.coffee
- angular/core/components/proposal_form/proposal_form.haml
- angular/core/components/thread_page/comment_form/comment_form.coffee
- angular/core/components/thread_page/comment_form/comment_form.haml
- angular/core/components/thread_page/comment_form/edit_comment_form.coffee
- angular/core/components/thread_page/comment_form/edit_comment_form.haml
- angular/core/components/thread_page/proposal_outcome_form/proposal_outcome_form.haml
- angular/core/components/thread_page/proposal_outcome_form/proposal_outcome_form_controller.coffee
- angular/core/components/thread_page/vote_form/vote_form.coffee
- angular/core/components/thread_page/vote_form/vote_form.haml
- angular/core/services/emoji_service.coffee
http://g.recordit.co/IxWvEhqqSu.gif
> Emoji fixes

- angular/core/components/invitation_form/invitation_form.coffee
@robguthrie, is this an ok fix for the bug you mentioned?
> Prevent form submit if no invitees

- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/services/message_channel_service.coffee
- app/models/discussion_reader.rb
- app/models/event.rb
- app/serializers/discussion_serializer.rb
- app/serializers/marked_as_read/discussion_serializer.rb
- config/initializers/event_bus.rb
- spec/models/events/new_comment_spec.rb
- spec/models/events/new_discussion_spec.rb
- spec/models/events/new_motion_spec.rb
- spec/models/events/new_vote_spec.rb
> clean up eventbus stuff, syndicate mark as read

- angular/core/components/notifications/invitation_accepted.haml
- angular/core/components/notifications/notifications.coffee
- angular/core/components/notifications/notifications.scss
- angular/core/models/event_model.coffee
- angular/core/models/notification_model.coffee
- angular/core/services/lmo_url_service.coffee
- angular/test/protractor/notifications_spec.coffee
- app/controllers/development_controller.rb
- app/controllers/notifications_controller.rb
- app/helpers/development/ninties_movies_helper.rb
- app/models/event.rb
- app/models/events/invitation_accepted.rb
- app/models/notification.rb
- app/serializers/event_serializer.rb
- config/initializers/event_bus.rb
- config/locales/client.en.yml
- spec/models/events/invitation_accepted_spec.rb
> Notify inviter when invitation is accepted

- lib/tasks/loomio.rake
Someone tell me if this is crazy? @rdbartlett @robguthrie
> Make sure blog images are https

- angular/core/components/invitation_form/add_members_modal/add_members_modal.coffee
- angular/core/components/invitation_form/add_members_modal/add_members_modal.haml
- config/locales/client.en.yml
Addresses https://github.com/loomio/loomio/issues/2977
> Change language and functionality for close button on add members modal

- angular/core/components/thread_page/vote_form/vote_form.haml
- angular/core/components/thread_page/vote_form/vote_form.scss
- config/locales/client.en.yml
Addresses https://github.com/loomio/loomio/issues/2979
Suggested improvements to language welcome
> Add explanation for when position statement is too long and submit fails

- app/controllers/subscriptions_controller.rb
- spec/controllers/subscriptions_controller_spec.rb
> Fix subscription webhook call

- angular/core/components/group_page/group_privacy_button/group_privacy_button.haml
- angular/core/components/thread_page/activity_card/activity_card.haml
- angular/core/components/thread_preview/thread_preview.haml
- config/locales/client.en.yml
Implementation of: https://trello.com/b/skuMQvLJ/loomio-sprint-board
> Implement accessibility feedback

- angular/core/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- angular/test/protractor/helpers/proposals_helper.coffee
- angular/test/protractor/proposal_spec.coffee
Addresses https://github.com/loomio/loomio/issues/2991
> Ensure most recent closed proposal remains expanded

- app/assets/stylesheets/email.scss
Addresses https://github.com/loomio/loomio/issues/2971
May need to test on clone?
> Remove problematic width for email images

- angular/core/components/start_menu/start_menu.coffee
- angular/test/protractor/invitations_spec.coffee
Addresses https://github.com/loomio/loomio/issues/3007
> Fix group select on invitations form

- angular/core/components/notifications/new_coordinator.haml
- angular/core/components/notifications/notifications.coffee
- angular/core/models/event_model.coffee
- angular/test/protractor/notifications_spec.coffee
- app/helpers/development/ninties_movies_helper.rb
- app/models/event.rb
- app/models/events/new_coordinator.rb
- app/serializers/event_serializer.rb
- app/services/membership_service.rb
- config/initializers/event_bus.rb
- config/locales/client.en.yml
- spec/models/events/new_coordinator_spec.rb
[Trello card](https://trello.com/c/1nygVRew/1208-3-i-want-to-be-notified-when-i-am-made-a-coordinator-of-an-existing-group)
> Notify user when they have been made coordinator of a group

- app/helpers/email_helper.rb
- app/views/user_mailer/missed_yesterday.html.haml
- config/locales/server.en.yml
- features/step_definitions/mark_summary_email_as_read_steps.rb
Friendly devs, could you either test this, or give me a hint about how I can test it? 
I can't see in the tech manual how to play with emails, nor a relevant route in /development/.
Fixes #3017
> Remove mark as read link from Yesterday on Loomio

- app/models/invitation.rb
Addresses https://github.com/loomio/loomio/issues/3031
> Delegate name to inviter, allow inviter to be nil.

- app/mailers/thread_mailer.rb
- config/locales/server.en.yml
Address https://github.com/loomio/loomio/issues/3021
Alternative subject will be sent to users if they're not following the discussion
> Update subject for user mentioned email

- angular/core/components/thread_page/activity_card/activity_card.coffee
- angular/core/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page_controller.coffee
Allows loading of correct activity window when passing through comment id
> Pass active comment id through to activity card

- angular/test/protractor/group_spec.coffee
- app/controllers/start_group_controller.rb
- features/groups/start_new_group.feature
- spec/controllers/start_group_controller_spec.rb
Addresses https://github.com/loomio/loomio/issues/3002
> Logged in angular users should be redirected when starting group

- app/models/cohort.rb
Addresses https://github.com/loomio/loomio/issues/3045
> Put activated_organisations method back in

- angular/core/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- angular/core/components/thread_page/proposal_positions_panel/proposal_positions_panel.scss
Addresses https://github.com/loomio/loomio/issues/3046
> Remove padding to align vote and position statement

- angular/core/components/discussion_form/discussion_form.haml
- angular/core/components/discussion_form/discussion_form.scss
Addresses https://github.com/loomio/loomio/issues/3049
> Add formatting help link to discussion form

- angular/core/components/previous_proposals_page/previous_proposals_page.coffee
- app/controllers/api/motions_controller.rb
- app/serializers/closed_motion_serializer.rb
- app/services/vote_cache.rb
- spec/controllers/api/motions_controller_spec.rb
Need to test this more but looks good at first blush. A little unsure about the duplication in ClosedMotionSerializer
> Allow closed proposals to load their own discussions / votes

- angular/core/components/notifications/notifications.coffee
- angular/core/components/notifications/notifications.haml
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/models/discussion_model.coffee
- app/controllers/development_controller.rb
Addresses https://github.com/loomio/loomio/issues/3034
> Scroll to relevant content

- app/helpers/email_helper.rb
- app/views/user_mailer/missed_yesterday.html.haml
this was taken out when it should not have been.
> replace the mark summary as read img

- angular/core/components/memberships_page/memberships_panel/memberships_panel.haml
- angular/test/protractor/manage_memberships_spec.coffee
- app/controllers/development_controller.rb
> Fix membership invite people

- angular/core/components/thread_page/revision_history_modal/revision_history_modal.coffee
- angular/core/components/thread_page/revision_history_modal/revision_history_modal.haml
[Trello card](https://trello.com/c/B6xWgoEn/1294-1-add-loading-indicator-for-revision-history)
> Add loading indicator for revision history modal

- app/models/invitation.rb
- spec/controllers/groups_controller_spec.rb
Addresses https://github.com/loomio/loomio/issues/3062
> Remove inviter_name method from invitation.rb

- angular/core/components/profile_page/profile_page.haml
- angular/core/components/profile_page/profile_page.scss
Addresses https://github.com/loomio/loomio/issues/3058
> Remove left right padding for profile page button links

- angular/core/components/discussion_form/discussion_form.haml
- angular/core/components/discussion_form/discussion_form.scss
> Tab directly to submit button from edit discussion form

- angular/core/components/thread_page/activity_card/new_comment.haml
> Order attachments by when they were created

- angular/core/services/user_help_service.coffee
Includes link to Arabic translation of help manual as well
Addresses https://github.com/loomio/loomio/issues/3060
> Add links to zh-TW and ar help manual translations

- angular/core/components/thread_page/activity_card/activity_card.scss
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page.scss
- angular/core/components/thread_page/thread_volume_card/thread_volume_card.scss
Addresses https://github.com/loomio/loomio/issues/3085
> Make cursor a pointer on thread page links

- angular/core/css/1_utilities.scss
|Before|After|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/1380991/13664886/86fcb1c0-e70e-11e5-8d9d-48fd37f1e2e7.png)|![image](https://cloud.githubusercontent.com/assets/1380991/13664835/3d391f74-e70e-11e5-92fd-24128e737d0f.png)|
> Github style markdown table styling

- angular/core/models/discussion_model.coffee
Addresses https://github.com/loomio/loomio/issues/3097
> Update last read sequence id when discussion read

- angular/core/components/star_toggle/star_toggle.coffee
> Fix thread starring

- .gitignore
- Dockerfile
- lib/tasks/deploy.rake
- lib/tasks/loomio.rake
@gdpelican nothing too crazy here. Can I merge please?
> Build angular client in Dockerfile

- app/admin/users.rb
Very minor — needs smoke test @gdpelican ?
> User admin panel: link group memberships to groups

- angular/core/components/thread_preview/thread_preview.scss
> Increase size of vote indicator in thread preview

- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.coffee
- angular/core/services/ability_service.coffee
- angular/test/protractor/group_spec.coffee
- app/controllers/api/motions_controller.rb
- app/controllers/development_controller.rb
- app/serializers/closed_motion_serializer.rb
> Display previous proposals card for open groups when logged out

- angular/core/components/thread_preview/thread_preview.scss
> Fix undecided thread preview icon

- config/initializers/delayed_job.rb
The last attempt will be 2 hours after it was created.
> increase the number of attempts allowed for a job to 10.

- Dockerfile
- lib/tasks/deploy.rake
@gdpelican FYI I've moved the versioning of the client assets into the build method.
> fix angular on docker image

- app/services/motion_service.rb
http://errbit.loomio.org/apps/56ef80443132390011000000/problems/570945d6657272000e000031
> fix api/motions#create errors while logged out

- angular/core/app.coffee
not just group creator
for #3178
> Show trial expired modal to all coordinators

- angular/core/components/angular_welcome_modal/angular_welcome_modal.coffee
- angular/core/components/angular_welcome_modal/angular_welcome_modal.haml
- angular/core/components/angular_welcome_modal/angular_welcome_modal.scss
- angular/core/services/boot_service.coffee
- app/assets/stylesheets/unstructured/_beta_banner.scss
- app/assets/stylesheets/unstructured/index.scss
- app/controllers/angular_controller.rb
- app/helpers/application_helper.rb
- app/views/application/_beta_banner.html.haml
- app/views/layouts/application.html.haml
- config/locales/client.en.yml
- config/locales/server.en.yml
> Add switch over to angular banner for beta

- angular/core/components/proposal_accordian/proposal_accordian.haml
- angular/core/components/proposal_closing_time/proposal_closing_time.haml
- angular/core/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- angular/core/models/discussion_model.coffee
- app/serializers/motion_serializer.rb
This is to address the "Invalid date" thing you sometimes see on recently closed proposals.
Also maybe to address #3203
> fix closedAt/closingAt clientside issues

- app/models/motion.rb
- app/services/motion_service.rb
- features/step_definitions/proposal_outcome_steps.rb
- spec/mailers/previews/thread_mailer_preview.rb
- spec/services/motion_service_spec.rb
> close motion before validation if necessary

- .travis.yml
- app/email_processors/email_params.rb
- spec/email_processors/email_params_spec.rb
http://errbit.loomio.org/apps/56ef80443132390011000000/problems/570eb4b665727200670003f5
> Ensure email params don't blow up as often

- .env.development
- .env.test
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/delayed_job.rb
- spec/mailers/user_mailer_spec.rb
pulled this out of the email preview branch. All environments set SMTP settings the same way.
> clean up smtp config

- angular/core/components/thread_page/activity_card/thread_item.scss
Address: https://github.com/loomio/loomio/issues/3173
> Align vote activity item components

- config/initializers/event_bus.rb
…d_item
Address: https://github.com/loomio/loomio/issues/3143
> Add outcome created/updated events to events calling author_thread_item!

- angular/core/components/group_page/group_help_card/group_help_card.coffee
- angular/core/components/group_page/group_help_card/group_help_card.haml
- angular/core/services/user_help_service.coffee
- config/locales/client.en.yml
- config/locales/client.es.yml
- config/locales/client.fr.yml
Addresses: https://github.com/loomio/loomio/issues/3208
> Link help card articles to correct locale on blog

- app/admin/groups.rb
Addresses: https://github.com/loomio/loomio/issues/3254
@gdpelican
> Remove visible_on_explore_front_page scope

- angular/core/components/proposal_form/proposal_form.haml
- app/models/motion.rb
- config/locales/server.en.yml
#3256 
http://recordit.co/oBoULE0uAg.gif
> Add validation errors for proposal closing at

- angular/core/components/group_page/group_help_card/group_help_card.haml
- angular/core/components/proposal_form/proposal_form.coffee
- angular/core/components/proposal_form/proposal_form.haml
- angular/core/components/proposal_form/proposal_form.scss
- config/locales/client.en.yml
see https://www.loomio.org/d/jWEAarxg/solution-candidate-hints-for-proposals
looks like:
and 
@HSalmon @natiloomio care to smoke test?
> Add proposal writing tips to new proposal form; language tweaks

- angular/core/components/thread_page/thread_page_controller.coffee
Supposed to address issue discussed here: https://github.com/loomio/loomio/issues/3169
Not sure if this is the best implementation. @gdpelican, would be good to get your thoughts
> Remove query string after requested model id set

- angular/core/components/explore_page/explore_page.haml
- angular/core/components/explore_page/explore_page.scss
Addresses: https://github.com/loomio/loomio/issues/3269
> Add motions count to explore groups

- angular/core/components/group_page/membership_request_form/membership_request_form.haml
Addresses: https://github.com/loomio/loomio/issues/3279
> Add validation error for email field onmembership requests form

- angular/core/components/explore_page/explore_page.haml
- angular/core/components/explore_page/explore_page_controller.coffee
- angular/core/models/group_records_interface.coffee
- app/controllers/api/groups_controller.rb
- app/controllers/development_controller.rb
- config/routes.rb
- spec/controllers/api/groups_controller_spec.rb
Addresses: https://github.com/loomio/loomio/issues/3268
> Ensure explore results count includes all matches

- angular/core/components/thread_page/thread_page_controller.coffee
Addresses: https://github.com/loomio/loomio/issues/3262
> Fix publish outcome modal bug

- angular/core/services/form_service.coffee
> Don't submit form again on cmd+enter if already submitted

- app/assets/stylesheets/pricing_table.scss
> Fix pricing bullets

- angular/core/components/thread_page/comment_form/comment_form.haml
Addresses: https://github.com/loomio/loomio/issues/3309
Look! No errors:
> Update translate-values attribute to fix reply to bug

- angular/core/models/discussion_model.coffee
- angular/package.json
I couldn't help myself from ripping out `clientReadSequenceId`. This should be a nice tight implementation now.
> Unread fix

- angular/core/components/angular_welcome_modal/angular_welcome_modal.haml
- angular/core/components/group_page/subscription_success_modal/subscription_success_modal.haml
- angular/core/components/invitation_form/invitable.haml
- angular/core/components/navbar/navbar.haml
- app/views/layouts/angular.html.haml
Because there are some browsers out there not smart enough to account for "img/image.jpg" as a url.
> Ensure all img links are relative to root url

- app/controllers/groups_controller.rb
This one's a beaut!
PS is there anything out there more confusing to a beginner (also me) than that
```
respond_to do |format|
format.thing
end
```
syntax?
> Make xls export work properly

- app/models/ability.rb
Is this the right thing for this @robguthrie? 
https://errbit.loomio.io/apps/57215524657272000e000001/problems/5731bf2765727200130011f5
> Don't allow logged out users to create groups

- app/extras/queries/users_to_email_query.rb
- features/volume.feature
- spec/extras/queries/users_to_email_query_spec.rb
Addresses: https://github.com/loomio/loomio/issues/3327
> Update UsersByVolumeQuery to include normal and loud for motion closed

- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.coffee
- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.haml
- app/models/discussion.rb
- app/models/group.rb
- app/models/motion.rb
- app/serializers/group_serializer.rb
- db/migrate/20160524034714_add_closed_motions_count_to_groups.rb
- db/schema.rb
- spec/models/discussion_spec.rb
- spec/models/group_spec.rb
Addresses: https://github.com/loomio/loomio/issues/3334
> Add closed_motions_count to group

- angular/core/components/group_page/join_group_button/join_group_button.coffee
- angular/core/components/group_page/join_group_button/join_group_button.haml
- angular/core/services/ability_service.coffee
- angular/test/protractor/join_group_spec.coffee
- config/locales/client.en.yml
> Disable ask to join if membership requested already

- angular/core/app.coffee
- angular/core/components/email_settings_page/email_settings_page.haml
- angular/core/components/email_settings_page/email_settings_page_controller.coffee
- angular/core/services/ability_service.coffee
- angular/test/protractor/email_settings_spec.coffee
- app/controllers/development_controller.rb
- app/helpers/current_user_helper.rb
> Don't prefer restricted user

- app/controllers/api/groups_controller.rb
- app/controllers/api/restful_controller.rb
- app/serializers/group_serializer.rb
- spec/controllers/api/groups_controller_spec.rb
> Serialize out parent groups for groups controller

- angular/core/components/discussion_form/discussion_form.coffee
- angular/core/components/discussion_form/discussion_form.haml
- angular/core/components/thread_page/comment_form/attachment_form.coffee
- angular/core/components/thread_page/comment_form/comment_form.coffee
- angular/core/components/thread_page/comment_form/comment_form.haml
- angular/core/services/attachment_service.coffee
Now you can paste attachments with ctrl+v, from anywhere in the form!
(Works for comments and discussions)
http://recordit.co/ErjHJsxUEf.gif
> Allow pasting of attachments

- app/assets/stylesheets/email.css
> Fix accept invitation button for mobile

- app/helpers/email_helper.rb
- app/views/thread_mailer/user_mentioned.html.haml
> Match user_mentioned url path to new_comment and user_replied_to

- angular/core/components/thread_page/comment_form/delete_comment_form.coffee
> Correctly remove deleted comment

- angular/core/components/thread_page/activity_card/thread_item.scss
> Style ordered lists like unordered lists

- Gemfile
- Gemfile.lock
Premailer-rails fix here: https://github.com/gdpelican/premailer-rails/commit/4f9b591e85c7ca7a7683e4d14e3dd8aa05411d17
PR against premailer-rails here: https://github.com/fphilipe/premailer-rails/pull/166
https://github.com/loomio/loomio/issues/3442
> Fix non-romanic email encoding

- app/views/thread_mailer/_motion.text.haml
- app/views/thread_mailer/_new_comment.text.haml
- app/views/thread_mailer/_new_vote.text.haml
- app/views/thread_mailer/_vote_buttons.text.haml
- app/views/user_mailer/missed_yesterday.text.haml
- app/views/user_mailer/missed_yesterday/_discussion.text.haml
- app/views/user_mailer/missed_yesterday/_headlines.text.haml
This resolves https://github.com/loomio/loomio/issues/1737
> add plain text missed_yesterday email

- config/locales/marketing.en.yml
> Update start group language on frontpage

- app/assets/stylesheets/unstructured/_pages.scss
- app/views/devise/sessions/new.html.haml
- config/locales/en.yml
> Add link to sign up to sign in page

- lib/plugins/base.rb
Reverts loomio/loomio#3472
Heroku does not like this. I'll have to figure out some other way to do this.
> Revert "Serialize out commit hash with installed plugins"

- angular/core/components/group_page/trial_card/choose_plan_modal/choose_plan_modal.haml
- angular/core/components/group_page/trial_card/choose_plan_modal/choose_plan_modal.scss
> Fix pricing modal styling

- app/serializers/events/motion_serializer.rb
- spec/controllers/api/notifications_controller_spec.rb
> Ensure serializing out discussions with motion events

- app/models/events/comment_liked.rb
- config/initializers/event_bus.rb
- spec/services/comment_service_spec.rb
> Only notify author of comment like if still in group

- angular/core/components/invitation_form/add_members_modal/add_members_modal.coffee
- angular/core/components/invitation_form/add_members_modal/add_members_modal.haml
- angular/test/protractor/invitations_spec.coffee
> Order add members modal, load all parent members

- angular/core/components/navbar/navbar_user_options.coffee
- angular/core/components/signed_out_modal/signed_out_modal.coffee
- angular/core/components/signed_out_modal/signed_out_modal.haml
- angular/core/services/message_channel_service.coffee
- angular/core/services/session.coffee
- app/controllers/api/sessions_controller.rb
- config/locales/client.en.yml
Once you log out, all other sessions will see this modal, and after clicking 'ok' will be logged out.
for #3068
> Log out all sessions on signout

- app/views/application/_google_analytics.html.haml
switch marketing layout to google tag manager
> switch to google tag manager

- angular/core/components/discussion_form/discussion_form.haml
> Fix ampersand trouble

- angular/core/components/thread_page/activity_card/discussion_edited.haml
- angular/core/components/thread_page/activity_card/discussion_moved.haml
- angular/core/components/thread_page/activity_card/motion_closed_by_user.haml
- angular/core/components/thread_page/activity_card/motion_edited.haml
- angular/core/components/thread_page/activity_card/motion_outcome_created.haml
- angular/core/components/thread_page/activity_card/motion_outcome_updated.haml
- angular/core/components/thread_page/activity_card/new_motion.haml
- angular/core/components/thread_page/activity_card/new_vote.haml
- angular/core/components/thread_page/activity_card/thread_item.scss
For #3505 
I found a little css 💩 !
On the plus side, it's pretty much the only one I remember having to clean up in this whole codebase, which is pretty impressive.
> Make vote links have color in thread items

- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.coffee
- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.haml
- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.scss
1. Fix old styling which is not support on safari
2. Apply truncate in case on long string
> fix broken styling on safari and apply truncated for super long string

- angular/core/services/scroll_service.coffee
> Fix scroll to content

- angular/core/components/sign_up_form/sign_up_form.coffee
- angular/core/components/sign_up_form/sign_up_form.haml
- angular/core/components/sign_up_form/sign_up_form.scss
- angular/core/models/records.coffee
- angular/core/models/registration_model.coffee
- angular/core/models/registration_records_interface.coffee
- app/controllers/api/registrations_controller.rb
- app/controllers/api/sessions_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
- config/locales/client.en.yml
- spec/models/user_spec.rb
NB: This does not change _any_ current in-app behaviour. It simply adds the ability to pop a sign up modal, for later on when our onboarding flow needs it.
> Sign up modal

- angular/core/components/attachment_preview/attachment_preview.scss
- angular/core/components/thread_page/thread_page.scss
- db/schema.rb
|Before|After|
|----|----|
|<img width="369" alt="screen shot 2016-07-26 at 11 51 59 am" src="https://cloud.githubusercontent.com/assets/1380991/17121398/a401cd98-5327-11e6-8e51-faa38e7b6a5a.png"> <img width="375" alt="screen shot 2016-07-26 at 11 51 46 am" src="https://cloud.githubusercontent.com/assets/1380991/17121404/aa9f9d24-5327-11e6-8672-9f50b5e5539a.png"> <img width="653" alt="screen shot 2016-07-26 at 11 51 38 am" src="https://cloud.githubusercontent.com/assets/1380991/17121409/b0c0e104-5327-11e6-9ec6-ec341fc3564f.png"> <img width="644" alt="screen shot 2016-07-26 at 11 51 21 am" src="https://cloud.githubusercontent.com/assets/1380991/17121413/bb604780-5327-11e6-91ac-82ee0f11c4a6.png">|<img width="361" alt="screen shot 2016-07-26 at 11 48 50 am" …
> Improve the look of thread attachments

- app/assets/stylesheets/pages/header.scss
> Fix mobile header

- angular/core/components/membership_requests_page/membership_requests_page.haml
- angular/core/components/membership_requests_page/membership_requests_page.scss
- angular/core/components/memberships_page/memberships_page.haml
- angular/core/components/memberships_page/memberships_page.scss
- angular/core/components/previous_proposals_page/previous_proposals_page.haml
- angular/core/css/1_utilities.scss
> Fix group theme padding

- angular/core/services/intercom_service.coffee
- app/serializers/group_serializer.rb
> fix intercom

- angular/core/components/dashboard_page/dashboard_page.haml
- angular/core/components/dashboard_page/dashboard_page_controller.coffee
- angular/core/components/navbar/navbar.coffee
- angular/core/services/thread_query_service.coffee
- angular/test/protractor/dashboard_spec.coffee
- config/locales/client.en.yml
Addresses https://github.com/loomio/loomio/issues/3557
> Remove filter threads dropdown from dashboard

- angular/core/components/inbox_page/inbox_page.haml
Is this a thing we can do?
This is a mockup, I haven't fired up my dev env:
> celebrate user for reading all their threads

- angular/core/css/1_base.scss
> Use correct css rule for word breaking

- app/views/thread_mailer/_motion_with_positions.html.haml
> Render emojis in votes in email

- angular/core/components/group_page/group_page_controller.coffee
- angular/test/protractor/group_spec.coffee
- angular/test/protractor/helpers/page_helper.coffee
- app/controllers/development_controller.rb
- app/views/layouts/angular.html.haml
- config/initializers/event_bus.rb
- features/following_logic.feature
- spec/services/discussion_service_spec.rb
> Don't set to loud unless site setting

- angular/core/components/group_page/group_page_controller.coffee
- angular/test/protractor/group_spec.coffee
- angular/test/protractor/helpers/page_helper.coffee
- app/controllers/development_controller.rb
- app/views/layouts/angular.html.haml
> [WIP] Only show welcome modal once

- angular/core/services/intercom_service.coffee
- angular/core/services/lmo_url_service.coffee
> Namespace LmoUrlService for intercom urls

- angular/core/components/sidebar/sidebar.haml
> Fix unread spacing

- app/extras/time_zone_to_city.rb
on marketing#index
https://errbit.loomio.io/apps/57215524657272000e000001/problems/57a8a56a6572720f72000454
> fix NoMethodError: undefined method `formatted_offset'

- .env.test
- angular/core/components/thread_page/thread_page_controller.coffee
Fix for: https://github.com/loomio/loomio/issues/3594
I introduced this bug when I tried to fix issue https://github.com/loomio/loomio/issues/3169 with this PR: https://github.com/loomio/loomio/pull/3273
> Fix vote by email

- angular/core/services/intercom_service.coffee
detect changes to group immediately and update intercom
> Intercom detect group change

- angular/core/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- angular/core/models/proposal_model.coffee
- app/models/motion.rb
> use safe values for membersCount and votersCount

- .env.development
- angular/core/services/intercom_service.coffee
fixes #3615 - tested on loomioclone
> fix the latest intercom issue

- angular/core/components/proposal_redirect/proposal_redirect_controller.coffee
- angular/test/protractor/proposal_spec.coffee
- app/controllers/development_controller.rb
> Ensure proposal redirect for visitor

- angular/core/services/attachment_service.coffee
Fixes: https://github.com/loomio/loomio/issues/3627
> Tweak attachment service to fix attachment removal

- Gemfile.lock
- angular/core/components/deactivate_user_form/deactivate_user_form.haml
- angular/core/components/deactivation_modal/deactivation_modal.coffee
- angular/core/components/deactivation_modal/deactivation_modal.haml
- angular/core/components/only_coordinator_modal/only_coordinator_modal.coffee
- angular/core/components/only_coordinator_modal/only_coordinator_modal.haml
- angular/core/components/only_coordinator_modal/only_coordinator_modal.scss
- angular/core/components/profile_page/profile_page.haml
- angular/core/components/profile_page/profile_page_controller.coffee
- angular/test/protractor/helpers/static_page_helper.coffee
- angular/test/protractor/profile_spec.coffee
- config/locales/client.en.yml
Addresses: https://github.com/loomio/loomio/issues/3629
> Reveal deactivate account option to all

- angular/core/models/session_model.coffee
> Remember me for in-app login

- app/jobs/proposals_closing_soon_job.rb
- app/models/motion.rb
- spec/jobs/proposals_closing_soon_job_spec.rb
> Fix multiple proposal closing soon events

- config/locales/marketing.en.yml
Fix for: https://github.com/loomio/loomio/issues/3651
PR for loomio_org_plugin repo: https://github.com/loomio/loomio_org_plugin/pull/17
> Translate image alt tags

- angular/core/components/dashboard_page/dashboard_page.haml
- angular/core/components/dashboard_page/dashboard_page_controller.coffee
> Wait for dashboard to load before displaying threads

- angular/core/models/user_model.coffee
- angular/test/protractor/group_spec.coffee
- app/controllers/development_controller.rb
- app/helpers/development/ninties_movies_helper.rb
Attempted fix for: https://github.com/loomio/loomio/issues/3667#issuecomment-243876497
> Remove duplicate values from groups

- app/extras/queries/users_to_email_query.rb
- spec/extras/queries/users_to_email_query_spec.rb
> Don't double email mentionees

- docs/en/development_handbook/qa_checklist.md
The intention is that this file provides a template, which you can paste into the discussion context of a QA check thread so that people can check off what they have tested, and we can see what level of QA we have achieved before pressing deploy.
> QA Checklist Template

- angular/core/components/thread_page/activity_card/activity_card.coffee
- angular/core/components/thread_page/print_modal/print_modal.coffee
- angular/core/components/thread_page/print_modal/print_modal.haml
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/css/print/main.scss
- app/controllers/development_controller.rb
- config/locales/client.en.yml
[Trello card](https://trello.com/c/QN4zkV62/1764-load-all-records-before-printing)
> Load all event records before print

- app/mailers/group_mailer.rb
- app/views/group_mailer/membership_request.html.haml
- app/views/group_mailer/membership_request.text.haml
- config/locales/server.en.yml
[Trello card](https://trello.com/c/HWWTmO2A/1819-2-style-membership-requested-email)
Subject:
> Style membership requested email

- angular/core/components/navbar/navbar.haml
- config/locales/client.en.yml
Address: https://github.com/loomio/loomio/issues/3684
> Make in-app navbar logo link to home page

- angular/core/services/scroll_service.coffee
> Explicitly check in view after scroll

- angular/core/components/group_page/group_theme/group_theme.haml
[Trello card](https://trello.com/c/YpojVpAH/1919-1-add-breadcrumb-to-thread-page)
> Add breadcrumb and role to thread page

- app/assets/stylesheets/marketing/index.scss
- app/assets/stylesheets/pages/crowdfunding_celebration.scss
PR on loomio org plugin: https://github.com/loomio/loomio_org_plugin/pull/20
Fixes: https://github.com/loomio/loomio/issues/3697
> Fix styling on crowdfunding page

- docs/en/development_handbook/setup_environment.md
you're now ready to install Loomio :sunflower:
> minor: fix typo that changes meaning (not vs. now)

- angular/core/components/group_page/choose_plan_modal/choose_plan_modal.haml
- config/locales/client.en.yml
- config/locales/server.en.yml
[Trello card](https://trello.com/c/imVBG7Wn/1936-1-change-csv-export-to-data-export-in-pricing-tables)
> Change pricing table language from csv to data export

- angular/core/components/mute_explanation_modal/mute_explanation_modal.coffee
- angular/core/components/mute_explanation_modal/mute_explanation_modal.haml
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/components/thread_preview/thread_preview.coffee
- angular/core/components/thread_preview/thread_preview.haml
- angular/core/components/thread_preview/thread_preview.scss
- angular/core/services/thread_service.coffee
- angular/test/protractor/discussion_spec.coffee
- config/locales/client.en.yml
[Trello card](https://trello.com/c/T65WQNie/1888-2-add-mute-to-thread-page)
> Add ability to mute thread from thread page

- angular/core/css/1_utilities.scss
> Add markdown table margin

- angular/core/components/group_page/group_page_controller.coffee
> Don't show Choose Plan Modal when chargify params aren't defined

- app/models/motion.rb
- docs/en/development_handbook/qa_checklist.md
temporary fix for https://errbit.loomio.io/apps/57215524657272000e000001/problems/57eb6ada657272003a0002ca
until we merge "merge user accounts" and fix the constraint issue.
> Fix motion close

- app/extras/model_locator.rb
- config/routes.rb
> Update model locator and route for comments

- angular/core/components/thread_page/print_modal/print_modal.haml
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/models/discussion_model.coffee
Addresses https://github.com/loomio/loomio/issues/3737 and https://github.com/loomio/loomio/issues/3736
> Only load records if they are not already loaded

- angular/core/services/ability_service.coffee
- app/helpers/angular_helper.rb
- app/models/translation.rb
- app/services/translation_service.rb
- spec/controllers/api/translations_controller_spec.rb
> Only allow translation of supported languages

- app/extras/example_content.rb
- config/locales/server.en.yml
- spec/extras/example_content_spec.rb
[Trello card](https://trello.com/c/F7qLR06k/1987-update-automatic-discussions-content-example-discussions)
[Loomio discussion](https://www.loomio.org/d/O3uqRpHT/comment/1144217/)
> Update example threads

- angular/core/css/1_utilities.scss
> markdown table layout

- app/services/invitation_service.rb
- config/initializers/event_bus.rb
I've run this on loomio test and emails come through.. just testing master on loomio-test to confirm it's the code not env
> just guessing what might fix start_group emails

- app/extras/model_locator.rb
The metadata tries to load the group but cannot and 404's via exception.
Resulting in this:
> fix 404 on chargify return

- angular/core/components/thread_page/comment_form/comment_form.coffee
- angular/core/services/key_event_service.coffee
> Don't allow submit while attachments uploading

- angular/core/components/thread_page/thread_page_controller.coffee
> Show thread dropdown for all members

- angular/core/components/thread_preview/thread_preview.haml
> Disable dismiss when thread is read

- angular/core/components/thread_page/thread_page.haml
> Fix old comment linking

- angular/core/services/intercom_service.coffee
> Intercom API fix

- app/serializers/metadata/discussion_serializer.rb
- app/serializers/metadata/group_serializer.rb
- app/serializers/metadata/motion_serializer.rb
For #3033 
I just found out Redcarpet comes bundled with a markdown stripper! 🍰 🎉
> Strip markdown for meta tags

- app/controllers/development_controller.rb
- config/plugins.yml
Companion PR in loomio_tags: https://github.com/loomio/loomio_tags/pull/4
> Tags refactor

- docs/en/development_handbook/qa_checklist.md
as discussed at last product meeting:
Test on production after deploy of code which touches core workflows.
> update qa checkist

- angular/core/components/group_page/membership_request_form/membership_request_form.haml
- angular/core/models/membership_request_model.coffee
- app/models/membership_request.rb
- config/locales/client.en.yml
- spec/models/membership_request_spec.rb
[Trello card](https://trello.com/c/gD1klyvH/2046-2-tweak-ask-to-join-form-language-add-character-count)
> Tweak language + add character count

- app/admin/groups.rb
|old|new|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/1380991/19789372/ae073a2a-9d0b-11e6-9980-b8a3c92a1d5d.png)|![image](https://cloud.githubusercontent.com/assets/1380991/19789355/948afe56-9d0b-11e6-9b02-b8e4b601d5cb.png)|
> Add link to metabase stats report, remove unneeded group_request line

- app/jobs/send_bulk_email_job.rb
- config/initializers/event_bus.rb
Delay bulk mail by ENV-set seconds to allow for 'ninja edits'
Also, don't error when event has been deleted.
> Delay bulk job

- angular/core/components/thread_page/position_buttons_panel/position_buttons_panel.scss
> Fix zoomed vote button size

- angular/core/components/user_avatar/user_avatar.coffee
- angular/core/components/user_avatar/user_avatar.haml
> Flexible gravatar size for profile page

- angular/core/components/proposal_form/proposal_form.haml
So that I can use ahoy to see if anyone uses this bit of contextual help
> Add BEM class to proposal tips link

- app/controllers/api/notifications_controller.rb
- app/extras/queries/notifications.rb
- app/models/current_user_data.rb
- app/services/notification_service.rb
- config/initializers/event_bus.rb
> Notify other tabs when notifications have been viewed

- angular/core/components/group_page/members_card/members_card.haml
- app/models/group.rb
- app/models/invitation.rb
- app/serializers/group_serializer.rb
- config/locales/client.en.yml
- db/migrate/20161103000505_add_pending_invitations_count_to_groups.rb
- db/schema.rb
[Trello card](https://trello.com/c/0cRYbzql/2059-1-add-of-invites-to-members-card)
> Add pending invitations count to members card

- angular/core/components/group_page/discussions_card/discussions_card.coffee
> Only show thread placeholder for members

- config/locales/es.yml
we had a missing translation for the commitment alt button and then i noticed the others were in english :)
> missing translations for vote buttons

- angular/core/services/draft_service.coffee
- app/helpers/angular_helper.rb
> Increase draft debounce

- app/assets/stylesheets/email.css
- app/views/group_mailer/membership_request.html.haml
- app/views/invite_people_mailer/_avatar.html.haml
- app/views/invite_people_mailer/after_membership_request_approval.html.haml
- app/views/invite_people_mailer/to_join_group.html.haml
- app/views/thread_mailer/_avatar.html.haml
- app/views/user_mailer/added_to_group.html.haml
- app/views/user_mailer/group_membership_approved.html.haml
[Trello card](https://trello.com/c/YOH1LQVl/2042-5-add-inviter-s-avatar-if-set-to-email-invites)
> Add avatars to join group invitations

- angular/core/components/sidebar/sidebar.haml
- angular/core/components/sidebar/sidebar.scss
- angular/core/components/thread_preview/thread_preview.scss
- angular/core/components/user_avatar/user_avatar.haml
- angular/core/components/user_avatar/user_avatar.scss
https://trello.com/c/geb3ybqy/2122-1-make-person-s-own-avatar-in-sidebar-link-to-edit-profile
https://trello.com/c/OwYEwgyB/2135-1-link-profile-photos-in-activity-panel-to-profile-page
> Link sidebar avatar and activity panel avatars to profiles

- app/admin/groups.rb
[Trello card](https://trello.com/c/fagAnVVy/2141-problem-it-s-hard-to-see-group-privacy-from-the-admin-panel)
> Simplify privacy in admin panel

- app/admin/group_requests.rb
- app/admin/groups.rb
- app/models/group_request.rb
- app/models/permitted_params.rb
- db/migrate/20161116013510_remove_unused_columns_and_tables.rb
- db/schema.rb
- spec/factories.rb
[Trello card](https://trello.com/c/EQdlhFCQ/2187-remove-unused-db-tables-and-columns)
> Remove unused db columns and tables

- angular/core/components/thread_page/thread_page_controller.coffee
> Fix vote on page load

- app/controllers/api/notifications_controller.rb
- app/controllers/api/profile_controller.rb
- config/routes.rb
- spec/controllers/api/profile_controller_spec.rb
This is to allow for a particular Zapier integration for Malcolm :+1:
> Add /notifications and /me for Zapier integration

- angular/core/components/group_page/group_actions_dropdown/group_actions_dropdown.coffee
- angular/core/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- config/plugins.yml
> Fix manage group subscription link

- angular/core/components/thread_page/vote_form/vote_form.haml
- angular/core/components/thread_page/vote_form/vote_form.scss
- angular/core/css/1_layout.scss
- config/locales/client.en.yml
Addresses: https://github.com/loomio/loomio/issues/3874
> Make modal widths consistent, update charater limit message for vote form

- config/locales/server.en.yml
Addresses: https://github.com/loomio/loomio/issues/3843
PR on https://github.com/loomio/loomio_org_plugin/pull/27
> Update csv export to data export

- angular/core/components/pie_chart/pie_chart.coffee
- angular/core/components/pie_with_position/pie_with_position.haml
- angular/core/components/thread_lintel/thread_lintel.haml
- angular/core/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- angular/core/components/thread_preview/thread_preview.haml
Primary change here is removing the `$timeout` and using `watchCollection` instead of `watch` (which halves the number of times the pie chart painting code is run)
> Pie chart rendering

- .env.development
- angular/core/components/flash/flash.haml
- angular/core/components/flash/flash.scss
Looks like this: https://drive.google.com/open?id=0B7rFWNdVhCDFNVFXUmp0N0JUUFU
> Add animations to toast message

- angular/core/components/group_page/description_card/description_card.coffee
- angular/core/components/group_page/description_card/description_card.haml
- angular/core/components/group_page/description_card/description_card.scss
- angular/core/components/group_page/group_page.haml
- angular/core/components/group_page/group_page.scss
- angular/core/components/group_page/group_page_controller.coffee
- angular/test/protractor/group_spec.coffee
- angular/test/protractor/helpers/groups_helper.coffee
- config/locales/client.en.yml
[Trello card](https://trello.com/c/bwCIXNzw/2152-add-link-to-edit-group-description)
> Add link to edit group description

- angular/core/components/group_page/description_card/description_card.coffee
- angular/core/components/group_page/description_card/description_card.haml
- angular/test/protractor/group_spec.coffee
@gdpelican - forgot this part!
> Ensure edit option only shows up for coordinators

- config/initializers/event_bus.rb
- spec/services/comment_service_spec.rb
> Nullify parent_id on replies after parent delete

- angular/core/components/thread_page/comment_form/mentio_menu.scss
> Fix z index for mentio menu on modals

- angular/core/components/navbar/navbar.haml
- angular/core/components/navbar/navbar_search.haml
- angular/core/components/sidebar/sidebar.haml
- config/locales/client.en.yml
[Trello card](https://trello.com/c/PWyhZcV8/2115-in-app-a11y-tweaks)
> In app a11y tweaks

- angular/core/components/thread_lintel/thread_lintel.scss
Address: https://github.com/loomio/loomio/issues/3868
> Fix thread lintel padding

- app/serializers/user_serializer.rb
[PR on loomio_onboarding repo](https://github.com/loomio/loomio_onboarding/pull/4)
Addresses: https://github.com/loomio/loomio/issues/3918
> Add created_at to user serializer

- app/serializers/user_serializer.rb
Reverts loomio/loomio#3923
Whoops, need to take care of that failing test; I'll do that now.
> Revert "Add created_at to user serializer"

- angular/core/components/thread_page/context_panel/context_panel.coffee
Address: https://github.com/loomio/loomio/issues/3897
> Close sidebar when user selects print option

- app/models/logged_out_user.rb
- app/serializers/user_serializer.rb
> Only show carousel to new accounts

- angular/core/components/navbar/navbar.scss
|Before|After|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/1380991/21001314/854facf4-bd84-11e6-9cb5-4b30deae0e0a.png)|![image](https://cloud.githubusercontent.com/assets/1380991/21001290/6ca1f982-bd84-11e6-8883-08b2be15be5e.png)|
> Bump navbar up the z-order

- angular/core/components/proposal_accordian/proposal_accordian.haml
- angular/core/components/proposal_accordian/proposal_accordian.scss
- angular/core/components/thread_page/proposal_expanded/proposal_expanded.scss
> Fix proposal padding

- angular/core/components/thread_page/comment_form/edit_comment_form.coffee
Addresses: https://github.com/loomio/loomio/issues/3937
> Enable mentions for edit comment form

- angular/core/components/thread_page/comment_form/comment_form.coffee
- angular/core/components/thread_page/proposal_expanded/proposal_expanded.scss
- angular/core/components/thread_page/undecided_panel/undecided_panel.coffee
- angular/core/components/thread_page/undecided_panel/undecided_panel.haml
- angular/core/components/thread_page/undecided_panel/undecided_panel.scss
- angular/core/models/proposal_model.coffee
- angular/test/protractor/helpers/proposals_helper.coffee
- angular/test/protractor/helpers/thread_helper.coffee
- angular/test/protractor/proposal_spec.coffee
- config/locales/client.en.yml
[Trello card](https://trello.com/c/lrEGaiBg/1867-mention-undecided-members)
> Add functionality for reminding undecided members

- angular/core/components/thread_page/context_panel/context_panel.haml
- angular/core/components/thread_page/context_panel/context_panel.scss
- angular/core/models/discussion_model.coffee
> Update styles for thread context add comment option

- angular/core/components/proposal_accordian/proposal_accordian.scss
- angular/core/components/thread_page/proposal_collapsed/proposal_collapsed.scss
Addresses: https://github.com/loomio/loomio/issues/3914
Not sure that this is _the_ solution but it is _a_ solution...
> Hide overflow on previous proposal body

- app/helpers/current_user_helper.rb
I think this is the right thing to do for this error: https://errbit.loomio.io/apps/57215524657272000e000001/problems/58cf70fd6572720011004a2c
> fix for undefined method `restricted=' for nil:NilClass

- app/extras/queries/explore_groups.rb
- spec/extras/queries/explore_groups_spec.rb
> Don't include archived groups in explore page

- angular/core/components/emoji_picker/emoji_picker.scss
> Fix emoji picker widget

- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.coffee
- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.haml
- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.scss
> Prettier buttons for dot voting

- angular/core/components/poll/meeting/form/poll_meeting_form.coffee
- angular/core/components/poll/meeting/time_field/poll_meeting_time_field.coffee
Also saves the previously submitted option in the input field for the next option 💃
> Add option on submit for meetings

- angular/core/models/poll_model.coffee
- angular/package.json
- angular/yarn.lock
I've also added an 'afterImport' hook to the baseRecordsInterface here, but we can fix this problem simply by looking at the correct value on stance
> Fix poll voters method

- angular/core/components/poll/count/chart_panel/poll_count_chart_panel.coffee
- angular/core/components/poll/count/chart_panel/poll_count_chart_panel.haml
- angular/core/components/progress_chart/progress_chart.coffee
- app/helpers/dev/polls_helper.rb
- config/colors.yml
> Add declined counts to progress chart

- angular/core/components/thread_page/comment_form/mentio_menu.scss
> Fix mentio styling

- angular/core/components/polls_page/polls_page.coffee
- angular/core/components/polls_page/polls_page.haml
- app/controllers/api/polls_controller.rb
- app/extras/poll_search.rb
- spec/controllers/api/polls_controller_spec.rb
Plz don't merge yet, I have not tested AT ALL *<3*
> Order by closed_at descending on activity page

- angular/core/components/poll/common/card/poll_common_card.haml
- angular/core/components/poll/common/percent_voted/poll_common_percent_voted.coffee
- angular/core/components/poll/common/percent_voted/poll_common_percent_voted.haml
- angular/core/components/poll/common/percent_voted/poll_common_percent_voted.scss
- angular/core/models/poll_model.coffee
- config/locales/client.en.yml
> Add percent voted to charts

- angular/README.md
Task 'deploy' is not in the gulpfile
> Task 'deploy' should be 'compile'

- app/services/translation_service.rb
proposed fix for https://www.loomio.org/d/nceoSVZ1/error-on-loomio-docker-container-at-startup
> support translation api key not present

- angular/gulpfile.coffee
- angular/tasks/app.coffee
- angular/tasks/execjs.coffee
- angular/tasks/minify_css.coffee
- angular/tasks/minify_js.coffee
- angular/tasks/scss.coffee
- angular/tasks/vendor.coffee
- app/helpers/angular_helper.rb
- app/views/layouts/angular.html.haml
this
[11:17:42] Finished 'vendor' after 767 ms
[11:17:44] Finished 'scss' after 2.75 s
[11:17:44] Finished 'app' after 3.55 s
rather than this
[11:20:08] Finished 'vendor' after 13 s
[11:20:12] Finished 'scss' after 18 s
[11:20:14] Finished 'app' after 20 s
> move minify/uglify to a later stage, fast build and easier debug

- angular/test/protractor/notifications_spec.coffee
- app/helpers/dev/ninties_movies_helper.rb
- app/models/notification.rb
- db/migrate/20170521053302_polymorph_notification_actor.rb
- db/schema.rb
- spec/models/event_spec.rb
> Fix notification actor

- app/controllers/api/memberships_controller.rb
- app/models/membership.rb
- app/models/poll_email_info.rb
- app/models/visitor.rb
- app/views/poll_mailer/common/_undecided.html.haml
- app/views/poll_mailer/poll_closing_soon.html.haml
- config/locales/server.en.yml
> Undecided in email

- angular/core/components/group_page/group_page.haml
- angular/core/components/install_slack/card/install_slack_card.coffee
- angular/core/components/install_slack/card/install_slack_card.haml
- angular/core/components/install_slack/card/install_slack_card.scss
- angular/core/components/install_slack/invite_form/install_slack_invite_form.coffee
- angular/core/models/group_model.coffee
- app/controllers/api/groups_controller.rb
- app/models/communities/loomio_group.rb
- app/models/group.rb
- app/serializers/full/group_serializer.rb
- app/services/group_service.rb
- config/locales/client.en.yml
> Install slack card

- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.coffee
- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.haml
> change dot vote bars as you vote

- angular/core/components/poll/common/closing_at/poll_common_closing_at.coffee
- angular/core/components/poll/common/closing_at/poll_common_closing_at.haml
[Issue #4319](https://github.com/loomio/loomio/issues/4319)
> Add verbose proposal hover timestamp

- angular/core/components/auth/signin_form/auth_signin_form.coffee
- angular/core/components/auth/signin_form/auth_signin_form.haml
- angular/core/services/auth_service.coffee
- angular/test/protractor/login_spec.coffee
- angular/test/protractor/verify_stance_spec.coffee
- app/controllers/api/sessions_controller.rb
- app/controllers/dev/main_controller.rb
- app/controllers/login_tokens_controller.rb
- app/helpers/pending_actions_helper.rb
- app/models/permitted_params.rb
- app/serializers/pending/token_serializer.rb
- config/locales/client.en.yml
- spec/controllers/api/sessions_controller_spec.rb
- spec/controllers/login_tokens_controller_spec.rb
Ready for a review, @robguthrie . There are protractor tests to cover the new cases, which describe the new behaviour quite well.
> Make users click link to sign in via email

- angular/core/components/email_settings_page/email_settings_page.haml
- config/locales/client.en.yml
> make email settings learn more string translateable

- angular/core/components/lmo_textarea/lmo_textarea.coffee
- angular/core/components/lmo_textarea/lmo_textarea.haml
- angular/core/components/poll/count/vote_form/poll_count_vote_form.haml
- angular/core/components/poll/dot_vote/vote_form/poll_dot_vote_vote_form.haml
- angular/core/components/poll/meeting/vote_form/poll_meeting_vote_form.haml
- angular/core/components/poll/poll/vote_form/poll_poll_vote_form.haml
- angular/core/components/poll/proposal/vote_form/poll_proposal_vote_form.haml
- angular/core/components/poll/ranked_choice/vote_form/poll_ranked_choice_vote_form.haml
- angular/test/protractor/poll_spec.coffee
Fixes bug where we were wiping reasons of stances submitted with > 250 characters
> Add maxlength option to lmotextarea; generalize for stance forms

- angular/core/components/reactions/display/reactions_display.scss
- app/helpers/dev/ninties_movies_helper.rb
> fix reactions wrapping

- angular/core/components/navbar/navbar.haml
- angular/core/components/sidebar/sidebar.coffee
- angular/core/components/sidebar/sidebar.haml
- angular/core/components/sidebar/sidebar.scss
- angular/core/components/user_avatar/user_avatar.coffee
- angular/core/components/user_avatar/user_avatar.haml
- angular/core/components/user_dropdown/user_dropdown.coffee
- angular/core/components/user_dropdown/user_dropdown.haml
- angular/core/components/user_dropdown/user_dropdown.scss
- angular/core/css/0_boxes.scss
- angular/test/protractor/email_settings_spec.coffee
- angular/test/protractor/poll_spec.coffee
- angular/test/protractor/profile_spec.coffee
- config/locales/client.en.yml
> Create user dropdown for navbar

- config/locales/client.fr.yml
Just reusing existing translations in this new context
> move existing fr translations from sidebar to navbar/user_dropdown

- config/locales/client.en.yml
> corrects tool-tip: on a check, there is no dash option

- app/controllers/dev/base_controller.rb
- app/mailers/base_mailer.rb
WIP - need to unbreak for routes which actually do require emails
> Don't send emails during testing

- app/controllers/api/groups_controller.rb
- app/views/errors/400.json
- app/views/errors/404.json
- app/views/errors/429.json
- app/views/errors/500.json
- spec/controllers/api/groups_controller_spec.rb
..so that we don't get lots of errors about loading things for them.
We'll also want to figure out _why_ people are visiting guest groups, and fix that UI hiccup as well.
> 404 on guest groups

- angular/core/components/sidebar/sidebar.scss
> removes @include truncateText on sidebar menu items to allow text-wrap

- angular/core/components/user_dropdown/user_dropdown.coffee
- angular/core/components/user_dropdown/user_dropdown.haml
- config/locales/client.en.yml
FYI @gdpelican we don't code "Loomio" into any templates anymore :)
> Remove hard coded "Loomio" from contact label

- angular/core/components/poll/common/ranked_choice_chart/poll_common_ranked_choice_chart.coffee
- angular/core/components/poll/common/ranked_choice_chart/poll_common_ranked_choice_chart.scss
should fix https://github.com/loomio/loomio/issues/4339
> removes white-space:nowrap to allow long option wrapping

- docs/en/development_handbook/quickstart.md
- docs/en/development_handbook/setup_environment.md
updates versions in doc and helping to check for updates, and adds instructions for linux psql
> update versions and add a few details for installing on linux

- lib/plugins/repository.rb
> Revert "Only serialize plugin information in development mode"

- angular/core/components/explore_page/explore_page.scss
- angular/core/components/group_page/group_theme/group_theme.scss
- angular/core/css/1_layout.scss
- angular/core/root_controller.coffee
Reverts loomio/loomio#4430
We're seeing a couple of minor visual problems:
> Revert "keep aspect ratio of group banner and show all of it in all screen sizes"

- config/locales.yml
These languages are all being actively translated and have more than 33% completion on https://www.transifex.com/rdbartlett/loomio-1/languages/. It will help translators to improve translations in context and will be a good incentive to continue the efforts.
> adds language support for pt_BR, it, cs

- angular/core/components/document/management/document_management.haml
- angular/core/components/documents_page/documents_page.haml
- angular/core/models/document_model.coffee
- config/locales/client.en.yml
Visual changes I made yesterday.. not ready for the main branch as we need to resolve the model title thing.
I think we need a full document serializer for the management pages, then maybe we dont need any associations in the simple serializer used when documents are delivered inline in the app.
> Documents evolution - robs changes

- angular/core/components/document/card/document_card.coffee
- angular/core/components/document/card/document_card.haml
- angular/core/components/document/list/document_list.coffee
- angular/core/components/document/list/document_list.haml
- angular/core/components/group_page/description_card/description_card.haml
- angular/core/components/group_page/group_page.haml
- angular/core/models/document_records_interface.coffee
- app/controllers/api/documents_controller.rb
- app/models/document.rb
- config/locales/client.en.yml
> Documents card

- app/controllers/api/documents_controller.rb
- app/models/ability/group.rb
- app/models/formal_group.rb
- app/models/group.rb
- spec/controllers/api/documents_controller_spec.rb
Don't show private attachments in closed groups
> Better document privacy for closed groups

- client/shared/models/discussion_model.coffee
- client/shared/services/range_set.coffee
This should fix the memory errors leaking from subtractRanges on complicated discussions
Could you CR please @robguthrie ?
> add firstMissing for RangeSet

- app/views/user_mailer/_unsubscribe_link.html.haml
- config/locales/server.en.yml
> adds string and reference for click_here in user emails

- client/angular/components/thread_page/comment_form/comment_form.coffee
- client/angular/components/thread_page/comment_form/edit_comment_form.coffee
- client/angular/components/thread_page/comment_form_actions/comment_form_actions.coffee
- client/angular/setup.coffee
- client/shared/helpers/keyboard.coffee
- client/shared/services/event_bus.coffee
> Don't submit comment form when modal present

- Gemfile
- Gemfile.lock
We've been granted free [Skylight](https://www.skylight.io/) usage. Hooray.
> add skylight gem so we can see perf

- app/models/events/reaction_created.rb
- app/models/notification.rb
- config/locales/client.en.yml
- db/migrate/20180305031829_add_notification_model.rb
- db/schema.rb
> Reaction notification

- client/angular/components/thread_page/add_comment_panel/add_comment_panel.coffee
- client/angular/components/thread_page/event_children/event_children.coffee
- client/angular/components/thread_page/thread_item/new_comment.coffee
There's a bug that when you reply to a nested comment, the comment's parent is actually the "surface" comment, this fixes that.
> ensure that comment replies are pointing to the right comment.

- client/angular/components/change_picture_form/change_picture_form.haml
- client/angular/components/user_avatar/user_avatar.scss
> fix for gravatar image not fitting in it's spot

- app/models/event.rb
following on from supporting Hugi to fix his Loomio install - this bug was found in this method.
> minor fix so that records with dangling references get fixed

- client/angular/components/emoji_picker/emoji_picker.haml
- client/angular/components/poll/common/details_panel/poll_common_details_panel.coffee
- client/angular/components/thread_page/thread_item/poll_created.coffee
- config/emojis.yml
- config/locales/client.en.yml
following on from the discussion here: #4590
> add thumb up down reactions, remove reactions from polls

- db/migrate/20180501200550_add_index_to_events_kind.rb
- db/schema.rb
Saw a few traces which showed event select could be improved by this index. It's one of the cheapest indexes we can put on that table given the low number of kinds.
> index events on kind, we select by kind all the time

- app/mailers/group_mailer.rb
to address https://sentry.loomio.io/sentry/loomio-6y/issues/4144/
> return if membership destroyed before mailer was sent

- config/routes.rb
they raise errors, which is good, but we don't need to expose them in the first place.
> don't expose dev routes in prod

- client/angular/components/discussion/edit_modal/discussion_edit_modal.haml
- client/angular/components/discussion/start_modal/discussion_start_modal.haml
- client/angular/components/lmo_textarea/lmo_textarea.haml
- client/angular/components/lmo_textarea/lmo_textarea.scss
- client/angular/css/1_layout.scss
- client/angular/css/1_lmo_md.scss
see #4442 for explanations and captures
> removes scrollbars on textarea to avoid 2 scrollbars and widens modals

- app/models/event.rb
- app/models/events/discussion_closed.rb
- app/models/events/discussion_reopened.rb
we do this successfully in discussion readers, so I wonder if we want to do it here too for situations like: https://sentry.loomio.io/sentry/loomio-6y/issues/4389/
> retry create if event not unique

- app/serializers/simple/user_serializer.rb
- app/serializers/user_serializer.rb
- client/shared/helpers/listen.coffee
- spec/controllers/api/memberships_controller_spec.rb
- spec/controllers/api/profile_controller_spec.rb
Fix for #4703 undefined usernames
> Remove search fragment, include label on simple user serializer

- app/helpers/locales_helper.rb
- app/models/boot/site.rb
- client/shared/interfaces/locale_records_interface.coffee
> fix locales with dialects and moment locales

- app/extras/queries/visible_discussions.rb
> maybe fix inbox not displaying some unread content

- client/angular/components/poll/proposal/chart_panel/poll_proposal_chart_panel.coffee
- client/angular/components/poll/proposal/chart_panel/poll_proposal_chart_panel.haml
A user asked, and I came up with this:
> add percentages to proposal vote legend

- app/controllers/api/boot_controller.rb
- app/models/boot/site.rb
- client/shared/services/session.coffee
client reported that we don't detect the browser locale until the user is signed in.
> use browser detected locale when not signed in.

- app/models/stance.rb
- client/angular/components/poll/common/stance_reason/poll_common_stance_reason.haml
- spec/models/stance_spec.rb
We've had a few people say the stance limit is too low recently. Going to give this a go and see what happens. In the future we make make stance limit more configurable, but it would be great if we don't have to.
> allow up to 500 chars in a stance statement.

- CONTRIBUTING.md
Fixes the dead link mentioned in #4930
> CONTRIBUTING.md: fix link to dev docs

- db/migrate/20181130030519_remove_unused_indexes.rb
- db/migrate/20181130030859_remove_low_read_indexes.rb
- db/schema.rb
> remove low read indexes

- client/angular/components/poll/meeting/time_field/poll_meeting_time_field.coffee
- client/angular/components/poll/meeting/time_field/poll_meeting_time_field.haml
- client/angular/test/nightwatch/core/poll.js
- client/shared/models/poll_model.coffee
Adds E2E tests for starting / participating in polls
> E2e coverage for poll types

- client/angular/components/auth/complete/auth_complete.haml
- client/angular/components/auth/signin_form/auth_signin_form.haml
- config/locales/client.en.yml
> add check spam folder message

- client/angular/components/thread_preview_collection/thread_preview_collection.haml
- client/angular/config/vue.coffee
- client/tasks/paths.coffee
- client/vue/components/bar_chart/bar_chart.coffee
- client/vue/components/bar_chart/bar_chart.scss
- client/vue/components/matrix_chart/matrix_chart.coffee
- client/vue/components/poll_common_bar_chart/poll_common_bar_chart.coffee
- client/vue/components/poll_common_bar_chart/poll_common_bar_chart.scss
- client/vue/components/poll_common_chart_preview/poll_common_chart_preview.coffee
- client/vue/components/poll_proposal_chart/poll_proposal_chart.coffee
- client/vue/components/poll_proposal_chart/poll_proposal_chart.scss
- client/vue/components/poll_proposal_chart_preview/poll_proposal_chart_preview.coffee
- client/vue/components/poll_proposal_chart_preview/poll_proposal_chart_preview.scss
- client/vue/components/progress_chart/progress_chart.coffee
- client/vue/components/progress_chart/progress_chart.scss
- client/vue/components/thread_preview/thread_preview.coffee
- client/vue/components/user_avatar/user_avatar.coffee
- client/vue/components/user_avatar/user_avatar.scss
- client/vue/components/user_avatar_body/user_avatar_body.coffee
Adds Vue versions of all components / sub-components under `thread_preview.coffee`
We know socket changes aren't currently propagating into Vue-land, but something to figure out with `ng-vue` we suspect :)
> Vue2 thread preview

- client/angular/components/discussion/form/discussion_form.coffee
- client/angular/components/discussion/form/discussion_form.haml
> allow edit thread when thread limit reached

- vue/package-lock.json
- vue/package.json
> Revert "Bump emojione from 2.2.7 to 4.5.0 in /vue"

- app/models/user.rb
- app/serializers/announcement_recipient_serializer.rb
- client/angular/components/announcement/form/announcement_form.coffee
- client/angular/components/announcement/form/announcement_form.haml
- client/package-lock.json
> fix send multiple invitations and don't reveal email addresses

- app/mailers/base_mailer.rb
> support custom notifications email address

- vue/package-lock.json
- vue/package.json
> Revert "build(deps-dev): bump @mdi/font from 3.8.95 to 3.9.97 in /vue"

- Gemfile.lock
> Revert "build(deps): bump puma from 4.2.1 to 4.3.0"

- vue/package-lock.json
- vue/package.json
> upgrade vue lib

- app/controllers/api/groups_controller.rb
- app/controllers/groups_controller.rb
- app/extras/model_locator.rb
- app/extras/queries/explore_groups.rb
- app/helpers/load_and_authorize.rb
- app/views/groups/index.html.haml
- config/locales/client.en.yml
- config/routes.rb
- spec/controllers/groups_controller_spec.rb
- vue/src/components/explore/page.vue
- vue/src/shared/services/lmo_url_service.coffee
- vue/src/shared/services/thread_service.coffee
6. group setting regarding closed (not showing options around requests/approval/invitation; how do people join; mention possible appearance on explore page?)
> SSR explore page + misc

- app/serializers/group_serializer.rb
- config/locales/client.en.yml
- vue/src/components.js
- vue/src/components/group/settings_panel.vue
- vue/src/components/group/subscription_card.vue
- vue/src/components/modal/launcher.vue
- vue/src/shared/services/group_service.coffee
> subscription card for group settings

- config/locales/client.en.yml
- vue/package-lock.json
- vue/src/components/document/list.vue
- vue/src/components/group/page.vue
- vue/src/components/thread/attachment_list.vue
- attachments and documents list have same style
- documents can be deleted from group page
- clicking delete icon for attachment opens group settings modal, from which attachment can be deleted
> documents can be deleted

- app/models/contact.rb
- app/models/poll_poll_option.rb
- app/models/poll_reference.rb
- app/models/theme.rb
- app/workers/migrate_attachment_worker.rb
- lib/migrate_paperclip.rb
this converts the records only, the changes to the app are in a separate migration, mostly done already
> convert paperclip attachments to activestorage attachments in parallel

- vue/src/components/common/translation.vue
…d format column; in these situations, fall back to html
> fix thread title disappearing after translated

- vue/src/components/discussion/form.vue
- vue/src/components/discussion/move_comments_modal.vue
- vue/src/components/poll/add_to_thread_modal.vue
- vue/src/components/poll/common/add_option_modal.vue
- vue/src/components/poll/common/modal.vue
- vue/src/components/poll/common/move_form.vue
- vue/src/components/poll/common/outcome_modal.vue
- vue/src/components/poll/common/reopen_modal.vue
- vue/src/components/poll/common/set_outcome_panel.vue
- vue/src/components/poll/common/vote_form.vue
- vue/src/components/poll/dot_vote/vote_form.vue
- vue/src/components/poll/form_page.vue
- vue/src/components/poll/meeting/vote_form.vue
- vue/src/components/poll/poll/vote_form.vue
- vue/src/components/poll/ranked_choice/vote_form.vue
- vue/src/components/poll/score/vote_form.vue
- vue/src/components/profile/page.vue
> add :loading to lots of btns, mostly poll voting forms

- app/models/ability/comment.rb
- app/models/concerns/null/group.rb
- app/models/group.rb
- app/models/permitted_params.rb
- app/serializers/group_serializer.rb
- config/locales/client.en.yml
- db/migrate/20210305013157_add_members_can_delete_comments.rb
- db/schema.rb
- spec/controllers/api/v1/comments_controller_spec.rb
- vue/src/components/group/form.vue
- vue/src/shared/models/group_model.coffee
- vue/src/shared/models/null_group_model.coffee
- vue/src/shared/services/ability_service.coffee
add option so members can delete comments
> members_can_delete_comments

- vue/src/components/common/action_button.vue
- vue/src/components/common/action_dock.vue
- vue/src/components/common/action_menu.vue
- vue/src/components/poll/common/outcome_panel.vue
- vue/src/components/reaction/input.vue
- vue/src/components/strand/item/new_comment.vue
- vue/src/components/strand/item/new_discussion.vue
- vue/src/components/strand/item/outcome_created.vue
- vue/src/components/strand/item/poll_created.vue
- vue/src/components/strand/item/stance_created.vue
- vue/src/components/strand/list.vue
- vue/src/components/strand/nav.vue
- vue/src/components/thread/item/stance_created.vue
- vue/src/shared/loaders/thread_loader.coffee
- vue/src/shared/models/comment_model.coffee
- vue/src/shared/models/discussion_model.coffee
- vue/src/shared/models/outcome_model.coffee
- vue/src/shared/models/poll_model.coffee
- vue/src/shared/models/stance_model.coffee
- vue/src/shared/services/ability_service.coffee
- vue/src/shared/services/thread_service.coffee
[] fix scrolling up UX
[] show loading when loading page for the first time
[x] support icons for dock actions
[] move notifications: subscribe/unsubscribe to sidebar. sell it
[x] load more per fetch
[] timeline should not change size/be bigger than viewport, should feel snappy
[] attempt to predictively load more
> finish strand renderer

- vue/package-lock.json
- vue/package.json
> Revert "Bump marked from 3.0.4 to 3.0.6 in /vue"

- app/models/discussion.rb
- app/models/event.rb
- app/services/event_service.rb
- app/services/sequence_service.rb
- db/migrate/20220304213244_convert_poll_stances_in_discussion.rb
- db/migrate/20220304235224_add_partition_sequences.rb
- db/schema.rb
- vue/src/components/common/formatted_text.vue
- vue/src/components/poll/common/chart/bar.vue
rather that use database sequence objects (it will result in too many db objects), make a sequences table for row level sequences.
> Use sequences table

- app/models/concerns/group_export_relations.rb
- app/models/concerns/readable_unguessable_urls.rb
- app/services/group_export_service.rb
- app/workers/download_attachment_worker.rb
- spec/services/group_export_service_spec.rb
the breakthrough in migration: now we can support data migration from any server to any server!
> importing gives records new ids, then updates references

- app/models/concerns/has_rich_text.rb
- config/locales/client.en.yml
- vue/src/components/common/formatted_text.vue
- vue/src/components/lmo_textarea/collab_editor.vue
- vue/src/components/thread/comment_form.vue
- vue/src/shared/record_store/base_model.coffee
> Add a bright error message if a comment fails to save.

- vue/package-lock.json
- vue/package.json
> Revert "Bump @vue/cli-plugin-e2e-nightwatch from 4.5.15 to 5.0.6 in /vue"

- app/services/discussion_service.rb
- app/services/poll_service.rb
> Discard polls with discussions

- db/migrate/20230530043504_add_enqueue_tags_migration_job.rb
From the comments on https://github.com/loomio/loomio/issues/9809
> Run workers synchronously from migration

- .github/workflows/tests.yml
- app/controllers/api/v1/tags_controller.rb
- app/models/concerns/has_tags.rb
- app/models/permitted_params.rb
- app/models/tag.rb
- app/services/tag_service.rb
- app/workers/destroy_tag_worker.rb
- app/workers/migrate_tags_worker.rb
- app/workers/update_tag_worker.rb
- spec/controllers/api/v1/tags_controller_spec.rb
- spec/factories.rb
- vue/src/app.vue
- vue/src/components/group/discussions_panel.vue
- vue/src/components/group/tags_panel.vue
- vue/src/components/lmo_textarea/task_item_component.vue
- vue/src/components/tags/display.vue
- vue/src/components/tags/field.vue
- vue/src/components/tags/modal.vue
- vue/src/components/tags/select.vue
- vue/src/components/thread/preview.vue
- vue/src/shared/models/tag_model.coffee
- vue/src/shared/services/group_service.coffee
- vue/src/shared/services/thread_service.coffee
Restore tag management functions
> restore ability to rename and delete tags.

- app/controllers/api/b1/base_controller.rb
- app/controllers/api/b2/base_controller.rb
- app/controllers/api/b2/discussions_controller.rb
- app/controllers/api/b2/memberships_controller.rb
- app/controllers/api/b2/polls_controller.rb
- app/controllers/help_controller.rb
- app/models/permitted_params.rb
- app/models/user.rb
- app/services/announcement_service.rb
- app/views/help/api.html.haml
- app/views/help/api2.html.haml
- config/locales/client.en.yml
- config/routes.rb
- db/migrate/20231010024438_add_api_key_to_users.rb
- db/migrate/20231010213156_add_last_used_at_to_webhooks.rb
- db/schema.rb
- spec/controllers/api/b1/discussions_controller_spec.rb
- spec/controllers/api/b2/discussions_controller_spec.rb
- spec/controllers/api/b2/memberships_controller_spec.rb
- spec/controllers/api/b2/polls_controller_spec.rb
- vue/src/components/group/members_panel.vue
- vue/src/components/profile/page.vue
- vue/src/components/webhook/list.vue
- vue/src/shared/services/group_service.coffee
This is a new set of endpoints, similar to api/b1 but authenticated with a user.api_key.
> New API: api/b2 for users.api_key

- app/controllers/api/v1/discussions_controller.rb
- app/models/ability/comment.rb
- app/models/ability/poll.rb
- app/models/comment.rb
- app/models/discussion.rb
- app/serializers/discussion_serializer.rb
- app/services/discussion_service.rb
- db/migrate/20231024081138_add_closer_id_to_discussions.rb
- db/schema.rb
- spec/models/ability_spec.rb
- vue/src/components/strand/actions_panel.vue
- vue/src/shared/models/discussion_model.coffee
- vue/src/shared/services/ability_service.coffee
- vue/src/shared/services/event_service.coffee
- vue/src/shared/services/stance_service.coffee
- vue/src/shared/services/thread_service.coffee
also stop creating thread opened closed thread items
> prevent comments when thread is closed.

- app/services/received_email_service.rb
> emailing in to public only groups will create public discussion

- app/controllers/email_actions_controller.rb
- app/helpers/email_helper.rb
- app/mailers/event_mailer.rb
- app/models/notification.rb
- app/views/event_mailer/common/_footer.html.haml
- config/routes.rb
- spec/controllers/email_actions_controller_spec.rb
> track when user reads a notification email and mark as read

- app/services/newsletter_service.rb
- app/services/user_service.rb
- app/workers/redact_user_worker.rb
> Add NewsletterService to subscribe/unsubscribe users from our newsletter

- vue/src/components/group/form.vue
- vue/src/components/group/new_form.vue
- vue/src/shared/helpers/helptext.js
- vue/src/shared/models/group_model.js
we had some hangover around allowPublicThreads in a closed group. we never want to allow this and mentions of it in the code should be removed.
There was also some janky logic around the group_form which I've fixed here
> fix group_form privacy options.

- app/admin/users.rb
- app/extras/app_config.rb
- app/models/concerns/events/notify/by_email.rb
- app/models/concerns/null/user.rb
- app/models/received_email.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- app/services/received_email_service.rb
- config/locales/client.en.yml
- db/migrate/20241104023432_add_complaints_count_to_users.rb
- db/schema.rb
- vue/src/components/group/members_panel.vue
read email reports and mark users with a complaint_count
> Handle bounce complaints from amazon ses

- config/locales/client.de.yml
- config/locales/server.de.yml
> Fixing de locale spacing

- app/services/discussion_service.rb
- app/services/poll_service.rb
this is really important, crazy I was not doing it earlier. it prevents invalid and corrupt records and dangling incomplete changes
> use transactions within discussion and poll service
