loomio/loomio

- app/assets/stylesheets/unstructured/_discussions.css.scss
there's a problem with the styling on markdown. 
I've extended what looks like a patch-job.
this needs testing in browser. I don't have time to update ruby atm :(
> small stylefix for nested bullet-point markdown lists

- private_pub.ru
Fix path calculation for ``config/private_pub.yml`` in ``private_pub.ru``.
Fixes the following error while attempting to run
``rackup private_pub.ru -s thin -E production``:
/home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/private_pub-875b3de1711b/lib/private_pub.rb:23:in `read': Not a directory @ rb_sysopen - /home/dev/git/loomio/private_pub.ru/private_pub.yml (Errno::ENOTDIR)
from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/private_pub-875b3de1711b/lib/private_pub.rb:23:in `load_config'
from /home/dev/git/loomio/private_pub.ru:9:in `block in <main>'
from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
from /home/dev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder. …
> Fix path calculation for config/private_pub.yml in private_pub.ru

- .travis.yml
- db/seeds.rb
- spec/models/vote_spec.rb
This is a continuation of #1870.
With these changes, it will be possible to setup a functioning database solely from schema.rb without running a single migration, which is the best practice for Active Record.
This PR:
* Adds a SQL statement to `db/seeds.rb` to ensure that the `vote_age_per_user_per_motion` constraint is deferrable. This would normally happen as part of the relevant migration but not when using `rake db:schema:load`.
* Adds specs to ensure the original scenario from #1870 works.
* Reverts a recent work-around to .travis.yml as it's no longer necessary.
Possible follow-ups:
* Delete old migrations so that we don't rely on them for bootstrapping of the database. Not necessarily a good idea given the sheer user base of Loomio and the non-zero likelihood of someone wanting to …
> Make the database initialisable from `schema.rb` alone

- app/mailers/user_mailer.rb
- spec/mailers/user_mailer_spec.rb
Add test to ensure that group.full_name is in the subject of an email when user is added to a group.  Change mailer to pass test.
Fixes issue #1865
> Modify mailer when added to group to include group full name in subject.

- app/controllers/explore_controller.rb
Simple fix to add a default to the translating system so that this behaviour never manifests.
see  #1882
> Admin created categories are never translated.

- app/models/invitation.rb
- app/views/user_mailer/added_to_group.html.haml
- app/views/user_mailer/added_to_group.text.haml
- spec/mailers/user_mailer_spec.rb
we've QA'd this as well @HSalmon and I
> update invitation+added_to_group emails to use group.full_name fixes#1865

- app/models/ability.rb
- app/services/move_discussion_service.rb
- spec/controllers/discussions_controller_spec.rb
- spec/models/ability_spec.rb
- spec/services/move_discussion_service_spec.rb
This should fix the user being able to move discussions they're not able to.
Before, the UI would allow the author of a discussion to attempt to move a discussion, but it would fail on submit.
The logic (as I understand it should be): If a user is an admin of a group, they can move any discussion in that group to any other group they are a member of.
> Fix move discussion for #1647

- app/controllers/marketing_controller.rb
- app/views/marketing/index.html.haml
We currently do this with JS in the marketing index. It's not necessary to do that because we don't do app level caching now. Redirect based on cookies will prevent the "flash of marketing page before redirect" issue we've put up with for ages.
> redirect to dashboard at controller level

- app/assets/stylesheets/unstructured/_help.scss
- app/views/help/_comments.html.haml
- app/views/help/_coordination.html.haml
- app/views/help/_dashboard.html.haml
- app/views/help/_discussion_threads.html.haml
- app/views/help/_faq.html.haml
- app/views/help/_getting_started.html.haml
- app/views/help/_group_settings.html.haml
- app/views/help/_how_to.html.haml
- app/views/help/_inviting_members.html.haml
- app/views/help/_keeping_up_to_date.html.haml
- app/views/help/_leaving_group.html.haml
- app/views/help/_proposals.html.haml
- app/views/help/_subgroups.html.haml
- app/views/help/_user_profile.html.haml
+ Added links to the feedback discussion happening in the Loomio Community to the bottom of each section (see image below):
+ Added additional information to create more of a cohesive flow between a couple of sections, e.g. "Group settings" leads into the section on invitations etc...
> Include links to feedback discussion in docs

- app/models/group.rb
We have a few places like this where the code is not threadsafe, but we run with threading enabled (indeed loomio.org would need a lot more resources if we did not)
The trick is, if there is a place where you are reading a value, then in another statement writing based on that result, the read and write need to be contained in a transaction so that the value does not get changed by another thread inbetween the read and the write.
In this case I think there is even a rails helper for find_or_create but I kinda remembered that being problematic when I wrote this ages ago, and this makes it super clear we are using a transaction.
> add transaction around membership check and creation

- app/extras/inbox.rb
- app/models/discussion_reader.rb
- app/views/inbox/_discussion_line_item.html.haml
- app/views/inbox/_motion_line_item.html.haml
Only show a discussion if there is no active motion also being shown...
Also.. always show the same value on each line item. In this case, the unread activity count.
> One item per thread in beta inbox

- app/assets/stylesheets/unstructured/_header.scss
- app/controllers/application_controller.rb
- app/controllers/marketing_controller.rb
- app/helpers/application_helper.rb
- app/views/application/_footer.html.haml
- app/views/application/_header.html.haml
- app/views/devise/registrations/_persona_form.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/thread_mailer/_footer.html.haml
- app/views/thread_mailer/_footer.text.haml
- config/locales/en.yml
- features/contact_form.feature
- features/step_definitions/beta_logo_steps.rb
- features/step_definitions/contact_form.steps.rb
- features/step_definitions/web_steps.rb
- features/users/beta_logo.feature
@rob how's this?
here's what I did
- redirect / to /sign_in rather than marketing index
- change all references from 'Loomio' to hostname
- new footer:
"{{hostname}} is running an independent copy of Loomio - [find out more](http://github.com/loomio/loomio)"
- new in-app logo
> make loomio X work

- app/helpers/locales_helper.rb
- app/views/pages/translation.html.haml
- app/views/users/profile.html.haml
- spec/models/vote_spec.rb
make RTL locales that are not complete selectable. This is so that they can post and have the app recognise they are typing in a RTL (right to left) script.
I wanted to make it clear these are not complete in the language dropdown menu, so added a section for them at the bottom 
looks like this :
> make RTL languages profile options even though incomplete

- app/views/user_mailer/added_to_group.html.haml
- app/views/user_mailer/added_to_group.text.haml
a translator pointed out an email that didn't make sense : 
This translation:
```ruby
content: "%{who} has added you to %{which_group} on Loomio. Click here to go to the group:"
```
was not followed by a link in the email. I've just changed the order of the email so it reads correctly
> fix the added_to_group email readability sense

- app/helpers/application_helper.rb
- app/views/comments/edit.html.haml
- app/views/discussions/_add_comment.html.haml
- app/views/discussions/_form.html.haml
check out this!
**the problem**: we're linking all users to an english-only markdown help doc
**the solution**: uses google page translate url instead of just serving the plain url
> provide minimum translation of markdown help

- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- spec/mailers/user_mailer_spec.rb
adds config for using https links in emails
> use FORCE_SSL to determine http(s) email links

- app/assets/javascripts/main.js.coffee
- app/views/application/_header.html.haml
- app/views/application/_user_profile_options.html.haml
- config/initializers/intercom.rb
I've put the default Intercom messenger back in because it makes it easier for people to get hold of us. Sorry for the hassle before, there was something wrong with my brain.
> restore Intercom default messenger

- config/locales/client.en.yml
- lineman/app/modules/discussion_page/discussion_page.haml
- lineman/app/modules/discussion_page/proposals_card/proposals_card.haml
Don't show a lonely 'proposals' label when no proposal exists on a discussion. Also translates that card correctly.
> Angular hide proposals

- config/locales/client.en.yml
- lineman/app/components/navbar/navbar_controller.coffee
- lineman/app/components/navbar/navbar_notifications.haml
- lineman/app/components/navbar/navbar_notifications_controller.coffee
- lineman/app/components/navbar/navbar_user_options.haml
Fixes angular dropdown menus on navbar
Main issue was that the new angular router requires controllers to return a value, otherwise b0rktown when trying to load controllers (since coffeescript returns the last value)
Secondary issue was missing 'dropdown-menu-right' css class
> Fix dropdowns

- lineman/app/app.coffee
- lineman/app/components/group_form/group_form.haml
- lineman/app/components/group_form/group_form_controller.coffee
- lineman/app/components/group_page/group_form_controller.coffee
This makes the group form workflow work again, including:
- Creating a new group (`/g/new`)
- Creating a new subgroup (`/g/new?parentId=xxx`)
- Editing an existing group (`/g/xxx/edit`)
todo before merge: 
- Privacy options (I've got a good idea of how to do this)
- Add some integration testing around group creation / editing
- Design and implement some buttons to make this an actual workflow, instead of just urls
> Group form

- lineman/app/components/group_page/group_page.scss
- lineman/app/components/inbox/inbox.scss
- lineman/app/components/mixins.scss
- lineman/app/components/navbar/navbar.scss
- lineman/app/components/navbar/navbar_search.scss
- lineman/app/components/selector_list/selector_list.scss
- lineman/app/components/thread_lintel/thread_lintel.scss
- lineman/app/components/thread_page/activity_card/activity_card.scss
- lineman/app/components/thread_page/proposal_collapsed/proposal_collapsed.scss
- lineman/app/components/thread_page/proposal_expanded/proposal_expanded.scss
- lineman/app/components/thread_page/proposal_form/closing_at_field.scss
- lineman/app/components/thread_page/proposals_card/proposals_card.scss
Yee haw! Only semantic colors in teh mixins file!
Also I killed metaText because we kept overriding it. Also I think it is good for you to think about if you want $grey-on-grey or $grey-on-white when you are placing de-emphasised text around the place.
> removed non-semantic greys. killed metaText

- lineman/app/components/group_page/discussions_card/discussions_card_controller.coffee
- lineman/app/services/discussion_form_service.coffee
- lineman/app/services/key_event_service.coffee
Clicking 'new thread' on a group page will now default the new thread's group to that group.
Also added a 'T' keyboard shortcut to it as proof of super easiness.
> Apply group to new thread

- app/views/layouts/angular.html.haml
- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/navbar/navbar_search.haml
- lineman/app/components/navbar/search_result.haml
- lineman/app/components/profile_page/profile_page.haml
- lineman/app/components/thread_lintel/thread_lintel.haml
- lineman/app/components/thread_page/comment/attachment.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/user_avatar/user_avatar.haml
This fixed all of the image 404's in angular for me locally; problem was using the `src` attribute instead of `ng-src`
There's likely some lingering issues around things like default group logos, I'll check that out next.
> Use ng-src for attachment/user images

- app/controllers/users/omniauth_callbacks_controller.rb
Resolves 'found unpermitted parameter: Facebook'
Resolves 'found unpermitted parameters: first_name, last_name, verified'
> Fix Facebook OAuth2 signin not working

- app/controllers/api/discussions_controller.rb
- app/extras/queries/visible_discussions.rb
I was getting some really really old threads coming through the dashboard query; turns out we're not sorting discussions at all server side, which means we're not getting the right discussions back.
> Sort discussions by latest activity

- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
- lineman/app/components/navbar/navbar.coffee
- lineman/app/components/navbar/navbar.haml
- lineman/spec/controllers/dashboard_page_controller_spec.coffee
- lineman/spec/controllers/thread_page_controller_spec.coffee
- lineman/spec/helpers/controller.js
Don't merge me!
Angular router has a bug, which will be fixed in the next release, around injecting $scope into component controllers. ([linky linky](http://stackoverflow.com/questions/30167898/how-can-we-watch-expressions-inside-the-controller-in-angular-1-4))
I don't think it's a good idea to start tracking the new router from master, so I'd rather just wait until the next angular router release before we merge this (it's a weeny bug anyway).
> Reload dashboard filter on home click

- app/models/group.rb
This PR addresses #2039.
The changes I reverted were introduced by @robguthrie on 26th February. We should double check with his help why this was introduced.
Somebody: Please review.
> Fixes default group logo and cover photo broken

- lineman/app/components/thread_page/activity_card/activity_card.coffee
- lineman/app/components/thread_page/activity_card/activity_card.haml
- lineman/app/components/thread_page/activity_card/activity_card.scss
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- lineman/app/components/thread_page/thread_page_controller.coffee
- lineman/app/models/event_records_interface.coffee
- lineman/spec/directives/activity_card_spec.coffee
- Ensure page scroll happens after events & proposals are loaded
- Take out support for location hashes for now
- Ensure record is in clientside db before scrolling
> Ensure page load thread position

- lineman/app/components/group_page/discussions_card/discussions_card_controller.coffee
- lineman/spec/directives/discussions_card_spec.coffee
- lineman/spec/helpers/factory.js
This fixes the js errors when logged as a group admin on the group page
Also fixes a bug with creating multiple records with the lineman specs
> Fix example discussions js error

- lineman/spec/services/lmo_url_service_spec.coffee
I dunno why these were passing then failing, but this should fix it. :heart_decoration:
> Fix lmo url service specs

- config/locales/client.en.yml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page.scss
Having thread actions on the same line as the thread title looks stupid on mobile. So I've added a heading to the context card, which I have wanted to do for a while anyway, and pushed the thread actions up and to the right to make room for the thread title to have its own line. 
There's another pass to do to make this great, but this is an improvement at least.
> add heading and move thread actions on context card

- lineman/app/services/key_event_service.coffee
prevents the annoying 'invite modal shows up when you open chrome dev console' issue
> Don't fire hotkey events when ctrl/alt are pressed

- lineman/app/components/thread_page/position_buttons_panel/position_buttons_panel.scss
- lineman/app/components/thread_page/proposal_pie_chart/proposal_pie_chart.scss
Here is an easy little one that has been annoying me for a long time.
- decreases spacing between buttons
- reduces size of legend squares slightly
- positions legend bottom right of graph on screen less than 480px wide
before: (iphone5)
after: (iphone5)
after: (nexus5)
after: (web)
> adjust spacing so layout doesnt break on iphone5

- app/controllers/development_controller.rb
- lineman/app/components/archive_group_form/archive_group_form.coffee
- lineman/app/components/change_password_form/change_password_form.coffee
- lineman/app/components/deactivate_user_form/deactivate_user_form.coffee
- lineman/app/components/discussion_form/discussion_form.coffee
- lineman/app/components/edit_group_form/edit_group_form.coffee
- lineman/app/components/email_settings_page/email_settings_page_controller.coffee
- lineman/app/components/group_page/membership_request_form/membership_request_form.coffee
- lineman/app/components/leave_group_form/leave_group_form.coffee
- lineman/app/components/profile_page/profile_page_controller.coffee
- lineman/app/components/proposal_form/proposal_form.coffee
- lineman/app/components/proposal_form/proposal_form.haml
- lineman/app/components/start_group_form/start_group_form.coffee
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form.haml
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form_controller.coffee
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form.haml
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form_controller.coffee
- lineman/app/models/base_model.coffee
- lineman/app/models/proposal_model.coffee
- lineman/app/models/proposal_records_interface.coffee
- lineman/app/models/user_records_interface.coffee
- lineman/app/services/form_service.coffee
- lineman/spec-e2e/email_settings_spec.coffee
Here's a first pass at a general form service:
The basic gist is we have a factory which generates a submit function, which does the following:
- Accepts a scope and a model (required)
- Accepts a method to call as a submit function (optional; model.save is the default)
- Accepts a success flash message (optional)
- Accepts a success callback, for additional stuff to do on success (like redirect to a different page; optional)
- Sets an isDisabled switch on the form once it's submitted, and takes it off once a response comes back
- Closes the modal on success, if it's a modal form
- Sets validation errors on the model for a 422 response
- Broadcasts a page error event for other error responses (bad request, resource not found, internal server error, etc.)
Be interesting to see how this …
> Form Service 2: ReFormation.

- app/assets/stylesheets/unstructured/_pages.scss
- app/views/pages/translation.html.haml
- config/locales/language_names.en.yml
- config/locales/native_language_names.yml
adds table headers, and allows translators to see progress of new 1.0 translations:
> add loomio 1.0 progress bars to /translation

- lineman/app/components/navbar/navbar.scss
- lineman/app/components/navbar/navbar_search.scss
- Extend navbar auto centring icons for landscape phone and portrait tablet
- Expand button link to fill .lmo-navbar__item container so it looks prettier.
Before:
After:
> fix for landscape

- lineman/app/components/dashboard_page/dashboard_page.scss
- lineman/app/components/groups_page/groups_page.haml
- lineman/app/components/groups_page/groups_page.scss
- lineman/app/components/inbox_page/inbox_page.scss
- lineman/app/components/mixins.scss
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/thread_page/comment_form/comment_form.scss
- lineman/app/components/thread_page/position_buttons_panel/position_buttons_panel.scss
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page.scss
- lineman/app/components/thread_preview/thread_preview.scss
- lineman/app/components/utilities.scss
Sorry to keep bombarding you all with PRs.
Here is a goodie.  I've been through the entire app on chrome/firefox/safari and a few mobile devices and done all the little tweaks to make the app nice an pretty.
Most of these are just aligning to the inner card margin, which is currently done in some places and not in others.
Here is the gist:
- Move heading in 13px to match padding of discussion card padding
- Move filter in 1px to match padding of discussion card padding
- Move date range headers in 13px to match discussion card padding
- Move 'no discussion message' in 13px to match discussion card padding
- Fix closing_at format wrapping in safari
- Move header in 13 px to match discussion card padding
- Move 'no discussion message' in 13px to match discussion card padding
- Move header …
> general polish

- lineman/app/models/attachment_records_interface.coffee
Sanitising filenames in 1.0 - beta proved more tricky so this is an interim fix for the new interface.
> Sanitize filenames for upload

- lineman/app/components/group_page/group_page.scss
Merging this step now will make the following design + dev steps a lot easier.
Still looks bung on mobile but I'm most of the way to figuring out a nice solution for that.
> increase group page cover photo size to 320px

- lineman/app/components/group_page/discussions_card/discussions_card.coffee
The 'Show more' link was displaying when there were no more discussions to show (confirmed bug report from angular feedback form). This tweak should fix it
> Fix 'show more' functionality for discussions on group page

- lineman/app/components/thread_lintel/thread_lintel.scss
> Don't overflow lintel header

- lineman/app/components/base.scss
This remove the focus which seems to stay on the navbar filter buttons.
Before:
After:
https://trello.com/c/QFbcnDHq/565-remove-blue-focus-highlighting-around-filters-once-selected
> Remove linguring focus from buttons

- lineman/app/components/navbar/navbar.scss
This one keeps the button behaviour consistent with the other buttons in the navbar. That is once you click it and move away the grey hover effect leaves.  The issue is most notable when you change filters from say Unread to Groups where you get a big ugly grey block that doesn't really indicate anything(see attach).
The orange selector pseudo element should be enough to indicate what page you are on.
before:
after:
> Remove background color on filter button focus

- app/controllers/api/discussions_controller.rb
- app/controllers/api/groups_controller.rb
- app/controllers/api/motions_controller.rb
- app/controllers/development_controller.rb
- app/extras/queries/visible_discussions.rb
- app/helpers/development/dashboard_helper.rb
- app/serializers/discussion_serializer.rb
- config/locales/client.en.yml
- config/routes.rb
- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/dashboard_page/dashboard_page.scss
- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
- lineman/app/components/inbox_page/inbox_page.haml
- lineman/app/components/inbox_page/inbox_page_controller.coffee
- lineman/app/components/navbar/navbar.coffee
- lineman/app/components/star_toggle/star_toggle.coffee
- lineman/app/components/star_toggle/star_toggle.haml
- lineman/app/components/thread_preview_collection/thread_preview_collection.coffee
- lineman/app/components/thread_preview_collection/thread_preview_collection.haml
- lineman/app/models/discussion_model.coffee
- lineman/app/models/discussion_records_interface.coffee
- lineman/app/services/current_user.coffee
- lineman/app/services/thread_query_service.coffee
- lineman/spec-e2e/dashboard_spec.coffee
- lineman/spec-e2e/helpers/dashboard_helper.coffee
- lineman/spec-e2e/helpers/inbox_helper.coffee
- lineman/spec-e2e/inbox_spec.coffee
- spec/controllers/api/discussions_controller_spec.rb
Alright, this is ready for a look I think.
Notable things that are still bad at the moment:
- Visit inbox, then visit dashboard. No starred / proposal threads. Hit the 'recent' button again. Starred / proposal threads show up. Weep softly. (EDIT: fixed this, which takes me from `weep` to `wee!`)
- The muted e2e is failing for me because it's saying no muted threads are found. Works perfectly for the participating e2e (which is activated the same way), and works fine manually in the browser. Sigh.
- Need some optimization work on the dashboard query, I think because the discussion_serializer is loading up an author, group, and motion for each of 50 discussions.
> Dashboard shuffle (not for merging yet)

- app/models/event.rb
- app/models/webhooks/slack/base.rb
- app/models/webhooks/slack/motion_closing_soon.rb
- app/models/webhooks/slack/motion_outcome_created.rb
- app/models/webhooks/slack/motion_outcome_updated.rb
- app/models/webhooks/slack/new_motion.rb
- spec/models/events/new_motion_spec.rb
- Add links to proposal and discussion titles
- Don't send payload for subgroups which aren't visible to parent group
> Slack webhook upgrades

- lineman/app/components/navbar/navbar.scss
I hope this PR doesn't get in anybodies way but I would love it if someone could merge this as it bugs me daily.
Finally realised what the issue was that has been bugging me.  The navbar has a border bottom that it doesn't need. Removing this adds the crispness back to the shadow too.
This PR:
- removes border bottom from navbar 
- pads out user profile button to full height of navbar
Before:
After:
> remove border and add padding to user profile btn in nav

- lineman/app/components/thread_page/thread_page_controller.coffee
This comes from a change in behaviour in the find method on the record store
Before, I could get away with `Records.comments.find(NaN)`, which would return undefined
Now, instead, calling find with NaN returns some odd anonymous function thing which b0rks stuff.
We're calling with NaN at times because we need to parse an integer from the query string (we couldn't do it with, say, `Records.comments.find("1")`, and `parseInt(undefined)` is NaN
I figure it's okay to just patch this from my end, tho.
> Fix scroll to latest unread comment

- lineman/app/components/thread_page/activity_card/thread_item.scss
Before:
After:
Wanted to make a PR because I know you are working in the area @robguthrie @HSalmon. Just checking I'm not treading in your jello.
> fix margins around activity item headers

- config/locales/client.en.yml
- lineman/app/components/navbar/navbar_search.haml
- lineman/app/components/navbar/navbar_search.scss
Quick fix to make it so the search dropdown isn't going haywire while loading results / showing the no results found message
> Fix styles while loading / empty search results

- config/locales/client.en.yml
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/models/comment_model.coffee
- lineman/spec-e2e/discussion_spec.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
Toast notifies replier that recipient has been notified:
(+ minor test updates)
> Update toast for comment replies

- app/helpers/stats_helper.rb
- app/views/admin/stats/aaarrr.html.haml
Whoops, trying again. This makes the aaarrr table like:
> add greyscale to aaarrr table

- lineman/app/components/groups_page/groups_page_controller.coffee
- lineman/app/models/group_model.coffee
- lineman/package.json
I just wanted to put this up for a little discussion before I worked on the record store itself @robguthrie 
I think the minimum viable fix here is to add a `vanish` (naming? Something which says 'remove from client database') method to `base_model`, and manually call it for dependant: destroy relationships.
Later on, when we have more use cases, we can put in a more automatic way of dealing with orphans.
```
@remote.patchMember(@key, 'archive').then =>
@vanish()
_.each @memberships(), (m) -> m.vanish()
```
> Temp fix for groups not appearing after deactivate

- config/locales/client.en.yml
- lineman/app/components/start_proposal_button/start_proposal_button.haml
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/thread_page/proposal_positions_panel/proposal_positions_panel.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/undecided_panel/undecided_panel.coffee
- lineman/app/components/thread_page/undecided_panel/undecided_panel.haml
dashboard - replace "starred" with "starred threads"?
Thread page - remove %article from Thread context region
Label (aria-labelledby) the comment textarea by the h2 above it
Question mark dangling in the Start proposal button
Current votes table try role=presentation, use caption element to label
it
add sr-only heading for undecided memebers and focus it when showing
undecided members
> small changes from a11y review 3 sept 2015

- lineman/app/services/lmo_url_service.coffee
- lineman/spec/services/lmo_url_service_spec.coffee
there is still a weird html encoding issue: When these links are sent to the browser they look like this: http://localhost:8000/d/Fxdes1CL/what-star-sign-are-you-%3Fcomment=722017
> fix linking to comments

- lineman/app/components/thread_page/thread_page.haml
Fix extra spacing in thread options dropdown
> Fix thread options dropdown formatting

- config/locales/client.en.yml
- lineman/app/components/thread_page/activity_card/thread_item.scss
- lineman/spec-e2e/activity_item_spec.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
Trello cards:
[Thread activity items should be meta text](https://trello.com/c/84CvhuvO/704-0-5-thread-activity-items-should-be-meta-text)
[ "Matthew updated the thread description" should be "updated the thread context"](https://trello.com/c/0Menges0/703-0-5-matthew-updated-the-thread-description-should-be-updated-the-thread-context)
> Update activity items

- config/initializers/intercom.rb
Minor tweak. Currently beta users turn up in Intercom as "angular=unknown".
> tell intercom which users are on beta

- app/serializers/discussion_serializer.rb
- spec/controllers/api/notifications_controller_spec.rb
The current bug:
- We serialize out discussions in the inbox query, and discussions in the notifications query on page load.
- Discussions on the inbox query have discussion readers attached to them, notifications do not
- [BUG]: the notifications query has discussion_reader_id keys on them set to null  (So, it's `{ id: 101, discussion_reader_id: null }` but should be `{id: 101 }`)
- This means that when notifications serialize out, they're overwriting the existing discussion_reader_id as null, which means we're not including those discussions in inbox (because the inbox won't include any discussions which have a null discussion reader id)
All due to a silly oversight on my part, heh; this is basically a typo fix. :heart:
> Fix inbox unread count

- lineman/app/components/group_page/group_page.haml
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/group_page/group_theme/group_theme.coffee
- lineman/app/components/group_page/group_theme/group_theme.haml
- lineman/app/components/group_page/group_theme/group_theme.scss
- lineman/app/components/membership_requests_page/membership_requests_page.haml
- lineman/app/components/memberships_page/memberships_page.haml
- lineman/app/components/memberships_page/memberships_page.scss
- lineman/app/components/thread_page/thread_page.haml
- lineman/spec-e2e/helpers/groups_helper.coffee
- lineman/spec-e2e/helpers/thread_helper.coffee
This applies a directive to allow an easy way to put the group theme on new pages.
QUESTIONABLE BONUS:
I put the group theme on the thread page as well, per the mockups here:
https://projects.invisionapp.com/share/MV4B7FARB#/screens/103662393
In action:
I know we're thinking about revamping the thread page layout, but it was a small bit of work and looks quite nice imho. #IterateDontIncinerate
> Generalize group theme

- app/controllers/inbox_controller.rb
Currently visiting `loomio.org/inbox` renders a weird half-baked version of the old beta interface, even if you're on angular.
This is what the protractor tests are complaining about... not sure when this broke?
> Don't skip booting angular UI when visiting /inbox

- config/locales/client.en.yml
- lineman/app/components/navbar/navbar.haml
FYI there are a small number of predefined ["Landmark" roles](http://mcdlr.com/wai-aria-cheatsheet/), like banner, search, main, navigation, etc. 
When we have a region that doesn't make sense to be identified with a Landmark role, then we just use aria-label and call it whatever we like. 
That's why there's `role: 'banner'` and `aria-label: 'user-actions'` in this pull request.
> repatriate navbar orphans

- lineman/app/components/navbar/navbar_search.scss
Fixes search results dropdown on desktop. Mobile unaffected.
**Before**
**After**
> align search dropdown with search input on desktop

- config/locales/client.en.yml
- lineman/app/components/group_page/group_help_card/group_help_card.haml
- lineman/app/components/group_page/group_previous_proposals_card/group_previous_proposals_card.haml
- lineman/app/components/group_page/group_previous_proposals_card/group_previous_proposals_card.scss
- lineman/app/components/group_page/group_theme/group_theme.scss
- lineman/app/components/group_page/members_card/members_card.haml
- lineman/app/components/group_page/membership_requests_card/membership_requests_card.haml
- lineman/app/components/group_page/membership_requests_card/membership_requests_card.scss
- lineman/app/components/group_page/subgroups_card/subgroups_card.haml
- lineman/app/components/mixins.scss
- lineman/app/components/navbar/navbar.scss
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/utilities.scss
* add help link to user dropdown
* add help link to group page help card
* make group page previous proposals list items link to previous proposals page
* make group page membership requests list items link to membership requests page
* standardise all the lmo-card-minor-action links on the group page cards
> add help links and tidy up group page cards

- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/group_page/discussions_card/discussions_card.scss
- lineman/app/components/thread_preview_collection/thread_preview_collection.scss
Possibly not the best approach to this? it is a bit tricky because the threads list on Dashboard is it's own card, but the threads list on the Group page is inside a card. This works at least. Good enough to merge?
> reinstate threads card

- app/controllers/api/votes_controller.rb
- app/serializers/discussion_serializer.rb
- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
- lineman/app/components/group_page/group_previous_proposals_card/group_previous_proposals_card.coffee
- lineman/app/components/previous_proposals_page/previous_proposals_page.coffee
- lineman/app/components/thread_page/previous_proposals_card/previous_proposals_card.coffee
- lineman/app/components/thread_page/proposals_card/proposals_card.coffee
- lineman/app/models/vote_records_interface.coffee
- spec/controllers/api/votes_controller_spec.rb
Hey @robguthrie I'd be interested in hearing your thoughts on this, as it relates to side loading records we need from the store.
Here I'm loading up the current user's vote when the discussion a) is being loaded with a reader, and b) has a current proposal, but I wonder if there's a better way?
(This should, btw, fix the weird bug where people's votes aren't being loaded correctly on the dashboard sometimes... basically I don't trust the `my_votes` endpoint very much at the moment.)
(Also don't merge me; I'm just pushing this up now to see how the tests fare)
> Simplify my_votes endpoint

- lineman/app/components/flash/flash.scss
- lineman/app/components/group_page/discussions_card/discussions_card.haml
- lineman/app/components/thread_preview/thread_preview.haml
- lineman/app/components/thread_preview/thread_preview.scss
* Reorder DOM so that the buttons come after the thing they modify. 
* remove labels from mute and mark as ready buttons so they don't look so ugly
> fix up dom order for float:right buttons for a11y

- app/extras/example_content.rb
- config/locales/client.en.yml
- config/locales/en.yml
- lineman/app/components/group_page/trial_card/confirm_gift_plan_modal/confirm_gift_plan_modal.haml
- lineman/app/components/group_page/trial_card/confirm_gift_plan_modal/confirm_gift_plan_modal.scss
Addresses/fixes:
- On the Confirm Gift Plan modal, remove %gift_card and replace the text with "If your group doesn't have the budget to pay for software, you don't need to pay a subscription. Your group members will periodically be invited to make a voluntary donation."
- In the How To Use Loomio thread, the link to the Introductions thread is broken
- Loomio Helper Bot should use the contact@loomio.org gravatar
> New flow ui tweaks

- config/locales/client.en.yml
- lineman/app/components/notification_volume/notification_volume_dropdown.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/thread_page/thread_page.scss
* add the author avatar to the thread context
* remove Context header
* remove label from Volume dropdown (that is about to be turned into a card anyway)
> add avatar to thread context

- lineman/app/components/navbar/navbar_search.coffee
- lineman/app/components/notifications/comment_liked.haml
- lineman/app/components/notifications/comment_replied_to.haml
- lineman/app/components/notifications/membership_request_approved.haml
- lineman/app/components/notifications/membership_requested.haml
- lineman/app/components/notifications/motion_closing_soon.haml
- lineman/app/components/notifications/motion_outcome_created.haml
- lineman/app/components/notifications/notifications.coffee
- lineman/app/components/notifications/notifications.haml
- lineman/app/components/notifications/user_added_to_group.haml
- lineman/app/components/notifications/user_mentioned.haml
- lineman/app/components/selector_list/selector_list.scss
- lineman/app/components/utilities.scss
- lineman/app/models/event_model.coffee
- lineman/app/models/notification_model.coffee
- lineman/app/models/notification_records_interface.coffee
- lineman/app/services/current_user.coffee
- lineman/app/services/lmo_url_service.coffee
- lineman/package.json
- lineman/spec/services/lmo_url_service_spec.coffee
Giving the notifications a little love.
Notable:
- Added a `relevantRecord()` method to event to allow for easier lmo-hreffing
- Added a loading spinny while notifications are loading
- Pushed a fix to our angular router to allow for query param linking (we should smoke test this)
- Simplified the notifications controller some
- Changed lmo-url-service#proposal to redirect straight to the proposal, rather than through the legacy intermediate page.
> Notification links

- lineman/app/app.coffee
- lineman/app/components/discussion_form/discussion_form.haml
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/start_group_form/start_group_form.haml
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/components/utilities.scss
- lineman/bower.json
- lineman/config/files.coffee
Expand comment field automatically for longer comments
Before:
After (at maximum size):
(PS I like that this screenshot suggests that spell check eventually gets bored of accusing you of language massacre.)
> Expandable comment field

- CONTRIBUTING.md
I think it is more appropriate to say:
*add your fork as a new remote* **than** *add your fork as a new branch.*
> Replace outbox branch with outbox remote

- lineman/app/models/discussion_model.coffee
Fixes transitioning to a thread from a search result you haven't seen before.
> Don't mark discussions without readers as unread

- lineman/app/components/thread_page/position_buttons_panel/position_buttons_panel.coffee
For https://trello.com/c/4pyWTzmD/923-vote-buttons-should-be-hidden-from-members-who-don-t-have-permission-to-vote
> Fix for position buttons panel

- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/dropdown/dropdown.scss
- lineman/app/components/group_page/group_actions_dropdown/group_actions_dropdown.haml
- lineman/app/components/group_page/group_privacy_dropdown/group_privacy_dropdown.haml
- lineman/app/components/navbar/navbar_search.haml
- lineman/app/components/navbar/navbar_user_options.haml
- lineman/app/components/notifications/notifications.haml
- lineman/app/components/thread_page/activity_card/new_comment.haml
- lineman/app/components/thread_page/current_proposal_card/proposal_actions_dropdown/proposal_actions_dropdown.haml
- lineman/app/components/thread_page/thread_page.haml
- lineman/app/components/utilities.scss
Standardise different dropdown versions:
Used for the most simple context menus, e.g. thread context, proposal options, comment options.
---
---
These are small on desktop and expand out to full width when you are on a tiny screen:
---
---
Used when you want to illustrate each option with an icon.
---
---
Used when you have to explain what the options mean
---
---
* all of them are aligned right
* Should search and notifications dropdowns use the same pattern? Or is this good enough to merge and we can resolve that when we fix search results.
> clean up dropdowns

- lineman/app/components/dashboard_page/dashboard_page_controller.coffee
- lineman/app/components/inbox_page/inbox_page_controller.coffee
- lineman/app/components/navbar/navbar.coffee
- lineman/app/models/membership_model.coffee
- lineman/app/models/user_model.coffee
- lineman/app/services/thread_query_service.coffee
On dashboard, do not show threads that are in groups you don't belong to.
On group page, do not hide muted threads.
@gdpelican  worked pretty hard to fit in with your design, feedback appreciated.
> fix thread queries

- lineman/app/components/memberships_page/pending_invitations_card/pending_invitations_card.haml
[Trello card](https://trello.com/c/lfc3e5HO/933-pending-invitation-link-is-wrong-has-a-double-slash)
> Remove extra forward-slash in url

- lineman/app/components/dashboard_page/dashboard_page.haml
- lineman/app/components/dashboard_page/dashboard_page.scss
- lineman/app/components/email_settings_page/email_settings_page.haml
- lineman/app/components/email_settings_page/email_settings_page.scss
- lineman/app/components/group_page/group_page.scss
- lineman/app/components/group_page/group_theme/group_theme.haml
- lineman/app/components/group_page/group_theme/group_theme.scss
- lineman/app/components/groups_page/groups_page.haml
- lineman/app/components/groups_page/groups_page.scss
- lineman/app/components/inbox_page/inbox_page.haml
- lineman/app/components/inbox_page/inbox_page.scss
- lineman/app/components/layout.scss
- lineman/app/components/membership_requests_page/membership_requests_page.haml
- lineman/app/components/membership_requests_page/membership_requests_page.scss
- lineman/app/components/mixins.scss
- lineman/app/components/previous_proposals_page/previous_proposals_page.haml
- lineman/app/components/previous_proposals_page/previous_proposals_page.scss
- lineman/app/components/profile_page/profile_page.haml
- lineman/app/components/profile_page/profile_page.scss
- lineman/app/components/thread_lintel/thread_lintel.scss
- lineman/app/components/thread_page/thread_page.haml
This fixes the 48px extra padding seen on the dashboard and inbox pages. `.group-theme` and `.lmo-row` were overwriting each other so I nested one inside the other.
> lose extra padding on one col pages

- lineman/app/components/thread_preview/thread_preview.scss
I'm sorry.
Before
====
After
===
> One more padding fix

- lineman/app/components/archive_group_form/archive_group_form.haml
- lineman/app/components/change_password_form/change_password_form.haml
- lineman/app/components/change_volume_form/change_volume_form.haml
- lineman/app/components/deactivate_user_form/deactivate_user_form.haml
- lineman/app/components/delete_thread_form/delete_thread_form.haml
- lineman/app/components/discussion_form/discussion_form.haml
- lineman/app/components/edit_group_form/edit_group_form.haml
- lineman/app/components/group_page/membership_request_form/membership_request_form.haml
- lineman/app/components/group_page/trial_card/confirm_gift_plan_modal/confirm_gift_plan_modal.haml
- lineman/app/components/invitation_form/invitation_form.haml
- lineman/app/components/leave_group_form/leave_group_form.haml
- lineman/app/components/memberships_page/cancel_invitation_form/cancel_invitation_form.haml
- lineman/app/components/move_thread_form/move_thread_form.haml
- lineman/app/components/proposal_form/proposal_form.haml
- lineman/app/components/remove_membership_form/remove_membership_form.haml
- lineman/app/components/start_group_form/start_group_form.haml
- lineman/app/components/thread_page/close_proposal_form/close_proposal_form.haml
- lineman/app/components/thread_page/comment/delete_comment.haml
- lineman/app/components/thread_page/comment_form/delete_comment_form.haml
- lineman/app/components/thread_page/comment_form/edit_comment_form.haml
- lineman/app/components/thread_page/extend_proposal_form/extend_proposal_form.haml
- lineman/app/components/thread_page/proposal_outcome_form/proposal_outcome_form.haml
- lineman/app/components/thread_page/vote_form/vote_form.haml
This makes no visual change to the ui (due to the float: left on the cancel button), but it means the first button you hit when you tab out of the form is Submit.
> put submit button before cancel button for keyboard users

- lineman/app/components/discussion_form/discussion_form.coffee
[Trello card](https://trello.com/c/xbJCPPNB/846-when-i-open-the-start-thread-modal-from-the-group-page-i-want-to-see-the-group-name-so-i-am-confident-it-is-going-to-start-in-th)
> Add group to start thread modal launched from group page

- app/serializers/comment_serializer.rb
i don't think we use this now.
> remove twitter autolink from comment serializer

- app/controllers/redirect_controller.rb
this causes 404 rather than 500 when group not found by subdomain
> subdomain not found should give 404

- config/locales/en.yml
Provoked by user test revealing user wasn't yet clear that there was such a thing as the comment form.
Before | After
-------- | ----
@rdbartlett please review
> Welcome thread language tweak

- lineman/app/components/angular_feedback_card/angular_feedback_card.coffee
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/css/0_mixins.scss
- lineman/spec-e2e/discussion_spec.coffee
This is an urgent fix to get the feedback card out of the way. We are getting lots of messages from people saying it is in the way. Soon this will be in the sidebar but I wanted to get this fix out in a hurry.
> move feedback card to footer

- config/locales/client.en.yml
- lineman/app/components/group_page/subscription_success_modal/subscription_success_modal.haml
- lineman/app/components/group_page/subscription_success_modal/subscription_success_modal.scss
I can't figure out how to test this. I think it's right, but it does need testing.
> Make subscription success language more appropriate

- app/views/devise/sessions/new.html.haml
- config/locales/en.yml
I recorded a [2.5 minute screencast](https://youtu.be/ga4rQq9TZSk) to look at what happens when you create an account from the log in page. It's an un-designed flow. It's not welcoming. It makes 'start thread' and 'invite people' non-sensical, but relatively prominent actions. It doesn't validate email addresses. It doesn't set the user's locale. You get no email trail that you set up an account. Also if you are invited to a group, and choose 'If you already have a Loomio account, log in here' it's a bit confusing on the next page seeing the option 'Don't have an account? Create one now'.
Before | After
--- | --- 
What chu reckon e.g. @rdbartlett @robguthrie ?
> Remove create account link from log in page

- app/views/groups/memberships/coordinator_index.html.haml
- config/locales/en.yml
[Trello card](https://trello.com/c/J2WVfhLj/1047-2-remove-email-column-from-group-memberships-page-on-beta)
> Remove email addresses from memberships page in beta

- config/locales/client.en.yml
Here's the dialog:
In an ideal world it wouldn't say 'and its subgroups' if there were none, too.
> apostrotweak

- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/services/draft_service.coffee
Whenever we apply the drafty bits (ie, initialize a form, either via modal or page load), fetch the draft from the server and apply it.
> Don't let forms care about getting their drafts

- lineman/app/components/group_page/group_page_controller.coffee
- lineman/app/services/ability_service.coffee
Break out the conditions for the welcome modal to make them a little easier to read, and only show welcome modal to the creator (we don't have memberships loaded at this point, so we don't know that the current user is an admin or not. Also, the welcome modal goes away after anyone's invited to the group, so it's really just the creator that needs to see it.)
> Fix AWOL welcome modal

- lineman/app/components/group_form/group_form.coffee
- lineman/app/components/group_form/group_form.haml
- lineman/app/services/privacy_string_service.coffee
Hey @robguthrie let me know what you think of this fix; the current issue as I understand it:
Currently, we can change from say 'closed' to 'open' privacy without updating the underlying 'discussionPrivacyOptions', meaning it's possible to submit a form which has 'open' privacy and 'private_only' discussions, which = 422.
> Group form tweaking

- app/models/draft.rb
- app/services/comment_service.rb
- lineman/app/components/thread_page/comment_form/comment_form.coffee
- lineman/app/components/thread_page/comment_form/comment_form.haml
- lineman/app/services/key_event_service.coffee
This should fix up the race condition for comments (we were deleting drafts asynchronously... normally brilliant, in this case horrible!)
Also a couple bonus fixes:
- Adding a 'comment is blank' message after trying to submit an empty comment
- Refresh the submitOnEnter key action after comment submit (otherwise it'll submit old comments on cmd+enter)
> Comment drafts fix

- config/locales/client.en.yml
- lineman/app/components/thread_page/activity_card/activity_card.coffee
- lineman/app/components/thread_page/activity_card/activity_card.haml
This has been bugging me for a bit.
Before:
After:
Maybe a prompt in the placeholder to enter a comment below? Other option is to hide the activity card when there isn't activity, but having the empty card feels odd to me.
> Add no activity placeholder

- spec/controllers/api/discussions_controller_spec.rb
I thought one of these tests would fail, since I was experiencing some annoying behaviour around groups not being muted.
Turns out it was a subgroup issue, ie, if I mute the parent group, the subgroups maintain their volume, which is maybe unexpected (but also maybe we want to maintain subgroup volume, I dunno.)
Anyway these tests are good to throw in in any case, since there's not much around the inbox action at the moment.
> Add tests for inbox action

- app/controllers/api/message_channel_controller.rb
This fixes a javascript error which happens on development when Faye isn't running :smile:
> Don't serialize out null subscriptions

- lineman/app/css/1_utilities.scss
Can this be tested on an installation that has Intercom?
> Move Intercom widget to avoid covering FAB

- angular/core/components/attachment_preview/attachment_preview.scss
Before | After
--- | ---
This has Product Owner approval :)
> Add maximum height for attached images to avoid them dominating threads

- config/routes.rb
Allow PUT action to be used in API where we're using PATCH
To tiptoe around this issue:
https://github.com/sandstorm-io/sandstorm/issues/1218
In reference to the Loomio / Sandstorm discussion happening here:
https://www.loomio.org/d/yw0D8Sc6/help-porting-loomio-to-sandstorm
NB: I've also updated the angular record store in 2.3.4 to add a `putMember` method, which will perform a `PUT` rather than `PATCH` request to the server (although I'd still like Loomio to be doing PATCH requests at the moment, since that's the railsy standard)
https://github.com/loomio/angular_record_store/pull/7
> Add companion PUT route to api PATCH actions

- lib/pluck_translations.rb
- lib/tasks/locales.rake
- lib/tasks/pluck_translations.rake
- spec/lib/pluck_translations_spec.rb
`rake loomio:pluck_translations config/locales/en.yml email config/locales/emails.en.yml email`
Will move all translations with they key `email` in en.yml es.yml ... etc to the key email in emails.en.yml emails.es.yml etc
IE: We can move translations around without discarding all the work of our translators. I built this so we can break up our main .yml files into way smaller files.
> tool to rename, move translations

- angular/core/components/thread_page/activity_card/thread_item.scss
should look more like this:
which is what this line of css does
> ensure that votestatements are in primary text colour

- angular/core/components/memberships_page/pending_invitations_card/pending_invitations_card.coffee
To fix: https://github.com/loomio/loomio/issues/2837
> Allow display of up to 1000 pending invitations

- angular/core/components/group_page/discussions_card/discussions_card.coffee
- angular/core/components/group_page/discussions_card/discussions_card.scss
- angular/core/components/group_page/group_page_controller.coffee
- angular/core/css/1_lmo_card.scss
- config/locales/client.en.yml
Resolves #2779 
Before | After
----- | -----
This is an intermittent bug. Worth testing on clone to be sure I've squashed it and there are no side effects.
> Fix vertical mobile card headers; broadcast placeholders further

- angular/core/components/invitation_form/invitation_form.coffee
- app/controllers/api/invitations_controller.rb
Email regex now requires some kind of TLD after the @. It also sees ; and , as seperators rather than part of the address
> improve email regex

- angular/core/components/thread_page/activity_card/discussion_edited.haml
- angular/core/components/thread_page/activity_card/discussion_edited_item_controller.coffee
- angular/core/models/version_model.coffee
- angular/test/protractor/discussion_spec.coffee
- app/models/discussion.rb
- config/locales/client.en.yml
[Trello card](https://trello.com/c/LhOfstmI/707-activity-item-for-changing-thread-privacy)
> Add activity item for when thread privacy is changed

- app/mailers/base_mailer.rb
- config/application.rb
- config/environments/production.rb
- config/initializers/devise.rb
A few tweaks to make S3 and SMTP optional, and avoid using `@loomio.org` when sending mails.
> Tweaks for production deployment

- angular/core/components/group_page/group_page_controller.coffee
- angular/test/protractor/invitations_spec.coffee
Addresses https://github.com/loomio/loomio/issues/3019
> Prevent group welcome modal from showing for subgroups

- app/models/omniauth_identity.rb
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/devise/shared/_omniauth_buttons.html.haml
- config/locales/en.yml
- config/locales/help.en.yml
Addresses https://github.com/loomio/loomio/issues/2993
@mhjb has suggested that instead of putting a message on the sign-in/sign-up pages requesting people reset their passwords if they've been using Persona, we send a message out to all Persona users telling them about the change.
> Remove references to persona

- angular/core/components/group_page/group_welcome_modal/group_welcome_modal.haml
- angular/core/components/group_page/group_welcome_modal/group_welcome_modal.scss
For #3063 
Small screen:
Big screen:
Can't seem to get fullscreen to happen, but linking to watch on youtube does work.
> Fix tiny, tiny video on group welcome modal

- angular/test/protractor/profile_spec.coffee
- app/controllers/development_controller.rb
[Trello card](https://trello.com/c/tQLdMHfm/1049-3-test-coverage-for-user-profile-privacy)
> Add tests for group membership visibility on profile page

- angular/core/components/thread_preview/thread_preview.haml
- angular/test/protractor/group_spec.coffee
I think this just needs a quick once-over CR; works for me on `development/view_open_group_as_visitor`
> Don't allow visitors to mark as read or mute

- app/models/discussion.rb
- config/initializers/event_bus.rb
- spec/services/motion_service_spec.rb
Addresses https://github.com/loomio/loomio/issues/3109
Does this need tests around it @gdpelican? Also, I noticed while I was testing it locally that it seemed like some of my own activity was showing up as unread. Will try and investigate further.
> Add motion_closed and motion_closed_by_user to salient items

- lib/tasks/bootstrap.rake
Before if your password was too short it would say the user was created even though it wasn't.
> If the bootstrap:create_user task fails to create the user it should say so and why.

- app/models/ability.rb
We're seeing a few Module::DelegationErrors and I think this might be a good way to deal with them.
Check the discussion exists as part of permissions checking, so failure to reference existing discussion results in unauthorised.
http://errbit.loomio.org/apps/56f0588e31323900110002ad/problems/5717bc276572720248000034
> Handle Module::DelegationError errors from Comment via email

- angular/core/components/proposal_form/closing_at_field.scss
> Better styling for date field on proposals

- angular/core/components/group_page/group_previous_proposals_card/group_previous_proposals_card.haml
… rather than to the previous proposals page.
Care to test it @HSalmon ?
> Make previous proposal titles on group page link to the proposal

- angular/core/components/memberships_page/memberships_panel/memberships_panel.haml
Looks like they were only ordered with coordinators first on the admin_memberships_panel, not the memberships_panel. Have updated.
Addresses: https://github.com/loomio/loomio/issues/3274
> List coordinators first for admin and non-admin memberships panel

- angular/core/components/star_toggle/star_toggle.haml
TIL that putting `ng-if` on the root element of a component makes it totally not work, I guess because it isolates a new scope and doesn't pass through the controller's scope.
> Unmunt star on thread page

- app/extras/send_missed_yesterday_email.rb
I think this will fix:
https://errbit.loomio.io/apps/57215524657272000e000001/problems/572a9da36572720010000a8b
ArgumentError
App: loomio.org Where: rake#loomio:send_missed_yesterday_email 
Environment: production Last Notice: May 05 10:10:41
activesupport-4.2.5.2/lib/active_support/core_ext/time/zones.rb:72→ rescue in find_zone!
activesupport-4.2.5.2/lib/active_support/core_ext/time/zones.rb:56→ find_zone!
activesupport-4.2.5.2/lib/active_support/core_ext/date_and_time/zones.rb:20→ in_time_zone
app/extras/send_missed_yesterday_email.rb:4→ block in to_subscribers!
app/extras/send_missed_yesterday_email.rb:3→ select
app/extras/send_missed_yesterday_email.rb:3→ to_subscribers!
lib/tasks/loomio.rake:22→ block (2 levels) in <top (required)>
> fix missed yesterday blowing up because of crazy tz value

- angular/core/components/thread_page/comment_form/comment_form.haml
Fixes this issue:
http://g.recordit.co/ph9ByELSXs.gif
Which was occasionally causing drafts to get saved after submit, meaning they showed up after the comment was submitted.
(NB the only change here is adding `ng-disabled: "isDisabled"` to the comment form text area.)
> Don't allow comment input while submitting

- Dockerfile
Without this warning people may be inclined to assume that the
Dockerfile can be used as a standalone image.
Fixes #3330
Signed-off-by: Loic Dachary <loic@dachary.org>
> Dockerfile: user warning redirecting to loomio-deploy

- lib/tasks/deploy.rake
Currently, every time we deploy, the final step (notifying clients that a deploy has happened), logs this:
```
Running rake loomio:notify_clients_of_update on ⬢ <repo>... up, run.8228
rake aborted!
Don't know how to build task '<repo>' (see --tasks)
/Users/gdpelican/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/gdpelican/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```
This
a) works perfectly, and
b) is misleading and scary.
This removes that error so we just get a).
> Fix notify client deploy error

- .env.development
- .env.test
- angular/core/components/flash/flash_service.coffee
- app/helpers/angular_helper.rb
This should fix some of the spurious / sporadic protractor errors, including
- `expected 'Welcome to the group!' but got ''`
- `expected page text to include 'Successfully signed in'`
(I believe there are others)
> Let's see what happens when the flash stays up a bit longer

- lib/plugins/base.rb
This allows us to serialize out the commit hash of each installed plugin, which will greatly help with debugging plugin issues.
> Serialize out commit hash with installed plugins

- angular/core/components/navbar/navbar.haml
- angular/core/css/0_mixins.scss
- angular/core/css/main.scss
- app/views/layouts/angular.html.haml
- Add box shadow to sidebar desktop
- Make toolbar appear above other page elements
- Increase navbar height variable slightly to account for slightly taller navbar
**Before:**
**After:**
(ignore the broken profile pic; that's because of my dev env :) )
> Sidebar css tweaks

- angular/core/components/thread_preview/thread_preview.scss
Reverts loomio/loomio#3515
This breaks text overflow on thread collection preview and was only put in for groups with tags. I'll find another way.
> Revert "Display thread preview link in flex"

- .mailmap
- .organizationmap
The FLOSS Contributor organization groups all contributors that are not
affiliated to any known organization.
Signed-off-by: Loic Dachary <loic@dachary.org>
> count code contributors per organization

- config/locales/server.en.yml
I've seen a couple times where people think that there is supposed to be a space between the brackets. I think the problem is that the `monospace font makes all the characters the same width so it looks a bit like a space between the brackets []()`. 
I reckon this little tweak should help.
> People misinterpret the markdown help

- app/models/discussion_reader.rb
- spec/models/discussion_reader_spec.rb
This should fix the issue I'm seeing occasionally where the last unread item is being skipped, resulting in this the last unread line appearing at the end of the thread, with no way to clear the unread item.
I want to test this some more, so don't merge just yet.
> Fix race condition on last read item

- angular/core/components/sidebar/sidebar.haml
- angular/core/components/sidebar/sidebar.scss
Hope this will also fix the parent group misalignment @rdbartlett describes here: https://github.com/loomio/loomio/issues/3609. Can't reproduce
> Fix alignment of unread and subgroups

- angular/core/components/sidebar/sidebar.coffee
- angular/core/components/sidebar/sidebar.haml
- config/locales/client.en.yml
[Trello card](https://trello.com/c/v6NpQG2k/1815-1-start-group-is-less-obvious-now-add-to-sidebar)
> Add start group option to sidebar

- app/models/search_vector.rb
- spec/controllers/api/search_controller_spec.rb
This is a first pass at adding a recency weight to our searches
What it does:
- If a discussion has last_activity_at within the past 7 days, the rank remains unchanged
- If a discussion has last_activity_at within the past 3 weeks, the rank is multiplied by 80%
- If a discussion has last_activity_at within the past 6 weeks, the rank is multiplied by 50%
- Otherwise, the rank is multiplied by 10%
I have no idea how this will work in production practice. ¯\ _(ツ)_/¯
> [WIP] Search recency

- app/admin/groups.rb
[Trello card](https://trello.com/c/4S4xQp3d/1673-2-reveal-subscription-status-for-groups-in-admin-group-list)
> Reveal group subscription status in admin panel

- angular/core/components/email_settings_page/email_settings_page.haml
Fix for: https://github.com/loomio/loomio/issues/3656
> Ensure group logos are always square on email settings page

- app/assets/stylesheets/email.css
- app/extras/queries/group_analytics.rb
- app/jobs/send_analytics_email_job.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/analytics.html.haml
- app/views/user_mailer/analytics.text.haml
- config/locales/server.en.yml
- spec/extras/queries/group_analytics_spec.rb
- Left aligned names in table
- Language tweak for title
- Replace table with contact us message in case of no activity
- Fix for admins with multiple analytics emails
> Adjustments to weekly analytics emails

- config/locales/server.es.yml
- config/locales/server.fr.yml
- config/locales/server.nl-NL.yml
- config/locales/server.zh-TW.yml
These were broken because we changed the variables passed into them.
> Remove broken translations from weekly email update

- angular/core/components/sidebar/sidebar.coffee
- angular/core/models/user_model.coffee
Fix for: https://github.com/loomio/loomio/issues/3653
> Ensure parents of orphan subgroups are visible in sidebar

- angular/core/css/1_utilities.scss
- app/admin/groups.rb
NB: This only covers moving an existing parent or subgroup to another parent; it does not support making a subgroup it's own parent group. The input will display the parent group's ID, but you can input either a group id or a group key and it will update correctly.
cc @natiloomio
> Admin moving of group from admin panel

- angular/core/components/thread_preview/thread_preview.scss
Before:
After:
desktop:
mobile:
> Move thread preview to flex

- angular/core/components/group_page/trial_card/confirm_gift_plan_modal/confirm_gift_plan_modal.scss
> Fix donation modal

- app/helpers/email_helper.rb
- app/mailers/thread_mailer.rb
- spec/helpers/email_helper_spec.rb
Ensure email footer links are always going to the right place
For #3690
> Unify thread mailer footer link

- app/controllers/api/discussions_controller.rb
- app/serializers/dashboard/discussion_serializer.rb
- app/serializers/dashboard/motion_serializer.rb
- app/serializers/discussion_serializer.rb
Currently our dashboard and inbox queries are getting killed by loading up a bunch of attachments:
**Dashboard**
**Inbox**
Over 55% of the time spent in the request is used doing an N+1 query for attachments which we don't use on these pages at all.
Here I've introduced a pair of new serializers for use with dashboard / inbox which ignores attachments (and, as a bonus, @mentions, which also incur a db hit and we also don't care about) for Discussions and Motions, which should halve the time it takes to process these queries. Wee performance!
On the plus side, it looks like folks are getting good mileage out of the discussion attachments feature, with about 2500 discussion attachments since we rolled out the feature June 9th, or about 15% of the 16.8k discussions created in that time. …
> Don't serialize out attachments / mentions for dashboard / inbox

- angular/core/components/outlet/outlet.coffee
- lib/plugins/README.md
- lib/plugins/base.rb
Could be activated in plugins.yml so:
```
plugin_for_standard_groups:
repo: loomio/standard_plugin
plans:
- standard
plugin_for_plus_groups:
repo: loomio/plus_plugin
plans:
- standard
- plus
```
> Allow specifying subscription plans with plugins

- angular/core/components/sign_in_form/sign_in_form.coffee
- app/controllers/users/sessions_controller.rb
> Remember me by default

- angular/core/components/thread_page/proposal_expanded/proposal_expanded.coffee
- app/controllers/api/discussions_controller.rb
- app/controllers/api/motions_controller.rb
- app/helpers/uses_full_serializer.rb
- app/serializers/dashboard/discussion_serializer.rb
- app/serializers/dashboard/motion_serializer.rb
- app/serializers/discussion_serializer.rb
- app/serializers/events/version_serializer.rb
- app/serializers/full/discussion_serializer.rb
- app/serializers/full/motion_serializer.rb
- app/serializers/motion_serializer.rb
- spec/controllers/api/motions_controller_spec.rb
Just throwing up for a test run
Idea is to only serialize out expensive things (like attachments and mentions) when calling **single resource** routes, IE show, create and update discussion / motion, meaning that we don't get huge amounts of expensive things we don't use when calling index actions (like /notifications, /events, /discussions, or /dashboard, all of which should have significant performance boosts after this.)
> Add full discussion / motion serializers for single resource requests [WIP]

- angular/test/protractor/discussion_spec.coffee
- app/controllers/development_controller.rb
@gdpelican, @robguthrie, here is the test for navigating to a comment via email
> Add test ensuring link in email takes user to relevant comment

- app/views/application/_google_analytics.html.haml
- app/views/layouts/angular.html.haml
- app/views/layouts/application.html.haml
- app/views/layouts/pages.html.haml
This adds support for using a seperate GTM ID on the marketing page.
> add gtm id for marketing container

- app/controllers/start_group_controller.rb
- app/jobs/start_group_job.rb
- app/mailers/invite_people_mailer.rb
- app/models/group_with_creator.rb
- app/services/group_service.rb
- app/services/invitation_service.rb
- app/views/start_group/create.html.haml
- app/views/start_group/new.html.haml
- config/initializers/event_bus.rb
The start group action is currently one of the slowest routes in our app:
Which sucks because it's right at the front door of the Buyer experience.
This is a refactor to kick off the actual group creation and admin invitation (which are relatively slow and pretty safe to assume successful) into a side job, so that the request itself can be quick like 🐰 .
> Refactor start group controller

- Gemfile
- Gemfile.lock
- app/models/event.rb
- app/models/events/motion_closing_soon.rb
- app/models/events/motion_outcome_created.rb
- app/models/motion.rb
- config/initializers/event_bus.rb
- spec/services/motion_service_spec.rb
Currently, two of the slower routes in our app are closing a motion, and creating an outcome (both key routes to the core workflow).
For closing a motion, this slowness can be attributed to creating heaps of DidNotVote records one at a time.
For creating an outcome, it's that we're notifying tonnes of users one at a time, which can get quite slow when there are lots of members in the group. (this is the case for motion_closing_soon as well, although this is less problematic because that code happens in a side job.)
So, I've introduced the activerecord import gem, which allows for batch insertions and should take waaay less time for groups with lots of members.
> Speed up motion close

- angular/core/components/group_page/members_card/members_card.haml
- angular/core/components/group_page/members_card/members_card.scss
- angular/core/components/user_page/user_page.haml
- angular/core/components/user_page/user_page.scss
[Trello card](https://trello.com/c/mXqKUhsU/1937-1-i-expect-to-be-able-to-click-faces-on-the-members-card-to-see-their-profiles)
Also added a margin to match the current user profile page to the user page:
> Link group member avatars to profiles

- angular/core/models/comment_model.coffee
- app/controllers/api/notifications_controller.rb
- app/models/event_collection.rb
- app/serializers/comment_serializer.rb
- spec/controllers/api/comments_controller_spec.rb
Looking at improving the performance of the events#index route (the one which loads events for the activity card)
Here's a recent extra-long query (this one took 2,700 ms):
A huge chunk of that time was taken querying for attachments and users (likers, in this case)
To combat this, I've added some queries to the EventCollection class, which will allow us to make a single query for all likers, attachments, or mentions (3 queries total) in the specified events, rather than having to do single queries for each of them (this added up to ~50 queries in the request above)
> Use cache queries instead of has_many for comment serialization

- angular/core/components/group_page/choose_plan_modal/choose_plan_modal.coffee
Attempt to address:
https://github.com/loomio/loomio/issues/3792
&
https://github.com/loomio/loomio/issues/3793
Could maybe do with a smoke-test on a test env with access to Chargify and Intercom
> Open chargify form in new tab, prevent modal from closing when contact form opens

- app/admin/groups.rb
- app/models/ability.rb
- db/migrate/20161108215035_add_features_to_groups.rb
- db/schema.rb
This adds a "toggle data export" button to the groups show page.
It also adds a features object much like the experiences object, for storing which features are enabled and any details we need about them.
> enable data export from admin panel

- angular/core/components/group_page/cover_photo_form/cover_photo_form.haml
- config/locales/client.en.yml
[Trello card](https://trello.com/c/5ziRHheb/2154-remove-unsplash-link-in-cover-photo-upload)
> Remove unsplash link from cover photo form

- angular/core/app.coffee
- angular/core/components/group_page/group_page_controller.coffee
- angular/core/components/sidebar/sidebar.coffee
- angular/core/components/thread_page/thread_page_controller.coffee
- angular/core/services/intercom_service.coffee
- app/views/layouts/angular.html.haml
A couple of minor performance fixes in here:
- Don't render the sidebar until the user clicks to open it on mobile (it renders normally for desktop)
- Don't scroll multiple times on the thread page (just scroll once we're ready)
- Remove the $watch statement from Intercom service and call it directly when `Session.currentGroup` changes
> Minor frontend performance upgrades

- angular/core/components/loading_content/loading_content.coffee
- angular/core/components/loading_content/loading_content.haml
- angular/core/components/loading_content/loading_content.scss
- angular/core/components/thread_page/activity_card/activity_card.coffee
- angular/core/components/thread_page/activity_card/activity_card.haml
- angular/core/components/thread_page/current_proposal_card/current_proposal_card.coffee
- angular/core/components/thread_page/current_proposal_card/current_proposal_card.haml
- angular/core/components/thread_page/thread_page.haml
- angular/core/components/thread_page/thread_page.scss
- angular/core/components/thread_page/thread_page_controller.coffee
Currently events are being loaded after the active proposal, previous proposal page, tags, etc, which is delaying the perceived load time of the page by ~500ms. This makes it so that events are the first query to go out after the thread itself is loaded.
> Ensure events are first thing loaded by thread page

- angular/core/components/thread_page/context_panel/context_panel.coffee
- angular/core/components/thread_page/context_panel/context_panel.haml
- angular/core/components/thread_page/context_panel/context_panel.scss
- config/locales/client.en.yml
[Trello card](https://trello.com/c/CZKcHUX6/2209-users-editing-title-and-context-instead-of-posting-comment-in-intro-thread)
> Prevent users from editing context when they mean to comment

- db/migrate/20170223024311_add_group_id_to_polls.rb
Had to do this to prevent migration from failing by missing group_id method :)
> Reload Poll colums to get the group_id attribute

- angular/core/components/poll/common/notify_group/poll_common_notify_group.haml
- config/locales/client.en.yml
It looks off without the helptext imo, so I just swapped out the message to say 'Your group will not be notified' when the option isn't checked
> Add different helptext for announcement off

- docs/en/development_handbook/code_guidelines.md
Hi! I just watched the [Design For Developers](https://www.youtube.com/watch?v=1I78I6l1nzI) (great talk!) by @rdbartlett and he mentioned BEM but I'd never heard of it. I thought it might be nice to link to an explanation of what it is.
I settled on linking to https://stackoverflow.com/tags/bem/info after also considering https://en.wikipedia.org/wiki/Block,_element,_modifier which is linked from https://en.wikipedia.org/wiki/BEM but is only a redirect to https://en.wikipedia.org/wiki/Cascading_Style_Sheets#CSS_authoring_methodologies
Personally, I find that neither http://bem.info nor http://getbem.com quickly provide what I'm interested in, which is what the letters in the BEM acronym stand for as well as a short description. The Stack Overflow tag description ticks all the boxes for …
> link to an explanation of BEM

- docs/en/development_handbook/quickstart.md
- docs/en/development_handbook/setup_environment.md
fixes #4201 
Changes in [```quickstart.md```](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/quickstart.md) and [```setup_environment.md```](https://github.com/loomio/loomio/blob/master/docs/en/development_handbook/setup_environment.md)
+ ```rbenv rehash``` is now deprecated, as per [official repository](https://github.com/rbenv/rbenv-gem-rehash)
+ dependencies are to be installed (```bundle install```)  before bootstrap task (```rake bootstrap```)
+ for users using postgres for the first, they can directly download postgres 9.6 instead of 9.4
/cc @gdpelican, @robguthrie
> Changes in environment setup and quickstart documentation

- app/models/stance.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- spec/models/user_spec.rb
- Allow verified users to vote even if they don't have a name set
- Add a validation message when attempting to change email to one that's already taken
> User validation messages

- config/environments/test.rb
Noticed your testsuite execution times and decided to help you out with it a bit. ;-)
This is a very simple trick -- turn off your Logging and get a 6% speed up to testsuite.
> turn off Logging for TEST enviroment

- lib/tasks/deploy.rake
untested (sorry!) but if the command is correct this will save bandwidth when deploying over mobile connections (which I've been doing recently)
> checkout as orphan branch to make deployment faster

- angular/core/components/email_settings_page/email_settings_page.haml
This should allow to display the locale string instead of its name.
> fixes incorrect reference to string in locales

- angular/core/components/thread_page/context_panel/context_panel.haml
- angular/core/components/thread_page/thread_item/thread_item.scss
- angular/core/css/1_utilities.scss
- app/models/discussion.rb
- app/models/discussion_reader.rb
- app/serializers/discussion_reader_serializer.rb
- app/serializers/discussion_serializer.rb
- app/serializers/mark_as_seen/discussion_serializer.rb
- app/services/discussion_service.rb
- config/initializers/event_bus.rb
- config/locales/client.en.yml
- db/migrate/20171103062211_add_discussion_readers_count.rb
- db/migrate/20171103062701_update_discussion_readers_count.rb
- db/schema.rb
Adds a "Seen by " to the metadata line on discussion context panel.
Issues:
I'd like to only update discussion readers count on reader create... how?
And in dev mode, creating a discussion ends up with Seen by 3, including Loomio Bot and Jennifer Grey.. just sometimes. WTF?
> add seen by count to discussion context

- angular/core/components/explore_page/explore_page_controller.coffee
Other pages show "title | Loomio" in the meta, the explore groups page just displayed  "| Loomio"...
> adds missing title for explore public group page meta

- angular/core/components/explore_page/explore_page.scss
- angular/core/components/group_page/group_theme/group_theme.scss
- angular/core/css/1_layout.scss
- angular/core/root_controller.coffee
uses background-size: contain and 22.85% padding to maintain aspect ratio and show all of the banner image on all screens. 
This should fix aspect ratio problems in #3790 and #3977 .
Tested on Firefox and Chromium.
See results with following banner image:
Before:
After:
Before:
After:
Before:
After:
> keep aspect ratio of group banner and show all of it in all screen sizes

- angular/core/components/attachment/form/attachment_form.coffee
Thanks to lines 8/9:
```
$scope.$watch 'files', ->
$scope.upload($scope.files) 
```
We don't need to call upload, since setting $scope.files will trigger upload anyway.
> Fix Duplicate Attachment on Paste

- angular/core/components/poll/ranked_choice/vote_form/poll_ranked_choice_vote_form.coffee
- angular/core/components/poll/ranked_choice/vote_form/poll_ranked_choice_vote_form.haml
- angular/core/components/poll/ranked_choice/vote_form/poll_ranked_choice_vote_form.scss
Due to some feedback around drag and drop not being very good for accessibility, I've put in a way to manipulate the ranked choice options using only the keyboard, which should be a slightly nicer experience.
> Add keyboard shortcuts to manipulate ranked choice options

- angular/core/components/thread_page/thread_item/thread_item.coffee
- angular/core/components/thread_page/thread_item/thread_item.haml
- angular/core/models/event_model.coffee
- angular/core/models/event_records_interface.coffee
- config/locales/client.en.yml
Now removing an event from the thread
- Displays a loading flash
- Displays a success message
- Doesn't allow double clicking
- Dims the event being removed
> Do good things when removing event from thread

- angular/core/components/poll/common/form_options/poll_common_form_options.coffee
- angular/core/components/poll/common/form_options/poll_common_form_options.haml
- config/locales/client.en.yml
@gdpelican I think we need a translations for timezone/place_name, so we don't just shove english timezones everywhere. 
Any idea on the best way to do this?
Seems similar to translations for language name too
> help users understand we convert timezones correctly

- angular/core/config/provide.coffee
error:
https://errbit.loomio.io/apps/57215524657272000e000001/problems/5a2f83b929e6e20007dce940
polyfill source:
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
converted via js2coffee
> use polyfill for closest on ie11

- angular/core/services/intercom_service.coffee
a stab at fixing:
https://errbit.loomio.io/apps/57215524657272000e000001/problems/5a303f0029e6e20007dd2cd8
I guess it happens because the group is not created?
> fix for group.createdAt undefined

- angular/core/components/poll/count/chart_panel/poll_count_chart_panel.haml
- angular/core/models/poll_model.coffee
Root cause of bug in #4445: membersCount() returns an integer for the total members, whereas in the fallback of goal() it was treated as if it returned a list (of members)
Per discussion in #4445, this PR also updates the numerator of the check poll results to be the total responses, not the Yes responses.
> Fix Check count results page (#4445)

- angular/core/components/memberships_page/memberships_page_controller.coffee
- angular/core/components/memberships_page/memberships_panel/memberships_panel.haml
- angular/core/components/user_page/user_page_controller.coffee
- config/locales/client.en.yml
- config/locales/client.fr.yml
Using Loomio in a large group that doesn't meet IRL, I find that it would be useful to know where members are (if they choose to enter a location, as discussed in #4391) and if they've been active on loomio recently (this can be useful for coordinators to gauge their group engagement too, see [this comment](https://www.loomio.org/d/laZLgn2I/time-poll/13)).
This PR also hides inaccurate detected locations from GUI per #4391, adds page title to group page header and removes unecessary parenthesis from users panel in locales. Sorry for this all-in-one commit :-(
> displays location and lastSeen on group members page and fixes minor glitches

- client/angular/components/poll/common/vote_form/poll_common_vote_form.scss
Looks like PR #4606 min-width reduction was not enough.
fixes #4607 and avoids cut-off text in longer locales...
> limits button width to a fourth of container even on medium screens

- client/angular/components/current_polls_card/current_polls_card.coffee
- client/angular/components/current_polls_card/current_polls_card.haml
- client/angular/components/current_polls_card/current_polls_card.scss
- client/angular/components/membership/card/membership_card.haml
- client/angular/components/membership/card/membership_card.scss
- client/angular/components/plus_button/plus_button.coffee
- client/angular/components/plus_button/plus_button.haml
Since we've removed the option to set a poll's group from the share form, there's no no way to start a poll within a group, which we've just had a paying customer complain about. I'd like to add this back in as a fix to fill the gap for now.
> Re-add new decision button on group page

- config/application.rb
When using Amazon Simple Email Service (SES), handshake with the SMTP server fails with:
> Job GroupMailer.invitation_created (id=2224) FAILED (0 prior attempts) with Net::ReadTimeout: Net::ReadTimeout
because of issues with the SSL handshake. Passing `ssl: true` to the ActionMailer config fixes this. This PR adds provides the option to pass 'SMTP_USE_SSL' from the application environment to enable the flag in ActionMailer
> Support SSL for SMTP connector

- app/models/event.rb
I've seen this before, but this time had time to try to address it:
This PR fixes it. And seems like it should have been there all along.
> fix for poll edited not gettting correct parent event

- app/extras/clients/base.rb
to manage all the "Failed Facebook api request." messages we get in sentry. Happy to consider using this just for facebook client.
> use rails logger for failed api requests because they are quite normal

- app/models/events/outcome_created.rb
- spec/models/event_spec.rb
I guess we can remove the announcement column on events after this?
fixes #4495
> ensure outcome author is emailed

- app/extras/group_inviter.rb
- app/extras/queries/users_by_volume_query.rb
Have to do this because we invite to the group regardless of their group / thread volume, and the guest group setting does (and should) override the formal group setting. 
So, right now:
- Person sets group volume to quiet
- They get invited to a new thread in the group
- They get a membership in that thread with normal volume
- They get emails about that thread (oops.)
> Don't set volume by default on group invite

- client/angular/components/navbar/navbar.haml
- client/angular/components/sidebar/sidebar.haml
- client/angular/components/user/dropdown/user_dropdown.haml
In sidebar, navbar and user-dropdown, replaces href attributes with ng-href because lmo-href alone doesn't allow middle/scrollwheel click and right click open.
Buttons opening modals and logout are untouched, middle/scrollwheel click has no effect on them, no open in new tab if right clicked. Cleaned-up the commits and merged with current master.
This should fix #3943
> allow middle/scrollwheel click and right click open in new tab on sidebar and dropdown buttons that open a page

- app/models/discussion.rb
Order has been effectively ignored and users have been reporting missing thread items.
without this fix the 
a request for:
```
https://www.loomio.org/api/v1/events?from=1&per=10&order=sequence_id&discussion_id=1
```
produces query which looks like this..
```
Event Load (4.0ms)  SELECT  DISTINCT "events".* FROM "events" WHERE "events"."discussion_id" = $1 AND ("events"."kind" NOT IN ('motion_closed', 'motion_outcome_updated', 'motion_outcome_created', 'new_vote', 'new_motion', 'motion_closed_by_user', 'motion_edited')) AND (sequence_id >= '1') ORDER BY events.id ASC, sequence_id LIMIT $2 
```
and we do not get results ordered by sequence id, so we miss items out.
This fixes it. yay.
> fix missing thread items problem

- app/controllers/dev/scenarios/group.rb
- app/controllers/dev/scenarios/membership.rb
- app/models/ability/membership.rb
- app/serializers/group_serializer.rb
- client/angular/components/fragments/only_coordinator.haml
- client/angular/components/membership/dropdown/membership_dropdown.coffee
- client/angular/pages/profile_page/profile_page_controller.coffee
- client/angular/test/nightwatch/core/group.js
- client/angular/test/nightwatch/core/membership.js
- client/angular/test/nightwatch/core/profile.js
- client/shared/models/user_model.coffee
- client/shared/services/ability_service.coffee
- config/locales/client.en.yml
- spec/models/ability_spec.rb
rather than this big task of ensuring there are coordinators, and checks and rules.. let's just allow groups to have no coordinators, and if that is the case, a member can self promote to coordinator.
> allow self promote to coordinator when no coordinators

- app/models/user.rb
a fix for #4734 
@gdpelican can you double check this? I only want to apply it for sign_in's initiated by the user, so if this breaks signing_in an unverified user just after creation then it's no good.
> fix for cannot login by password when unverified emails exist

- config/locales/server.en.yml
Hi friends! Hope you are all doing well.
I got a weird email as per #4737 and thought I might be able to fix it. 
As far as I can tell the translation is invoked here:
https://github.com/loomio/loomio/blob/bfc7628441d7dd91196e9d5b678296baa52b14ed/app/models/events/announcement_resend.rb#L18
I think it should have access to `%{title}` and `%{actor}` based on:
https://github.com/loomio/loomio/blob/master/app/mailers/poll_mailer.rb#L44
Just editing this on the web so not sure if tests pass or if any new tests are necessary.
> Add translation for poll mailer reminder. Fixes #4737

- app/controllers/api/memberships_controller.rb
Had a report that the contact request button on user profile page was not showing. And indeed it was not for many users, but it passes in tests. I found it too complex going through accessible_records and in this case and feel this is a simpler way to return the desired records.
> fix for contact request button not showing on many profile pages

- config/application.rb
Not verifying the SMTP server's certs is not a great idea, allowing a MITM to obtain auth credentials.
> allow configuring SMTP SSL verification

- docker_start.sh
Exit immediately when one command fails on startup. This should make it more easy to catch memory issues or any other kind of configuration problems on startup.
> chore: add exit option to bash

- config/locales/client.en.yml
Looks like the decision tools card is missing a score translation!
Repro: visit https://www.loomio.org/p/new on loomio.org:
> Add score poll title for decisions card

- app/models/ability/base.rb
- app/models/ability/group.rb
- app/models/group.rb
- app/models/user.rb
- spec/controllers/api/groups_controller_spec.rb
- spec/controllers/api/search_controller_spec.rb
we were allowing pending membership to grant access to groups, which isn't a security flaw, but it's stupid
> require accepted membership to access a group

- vue/src/components/explore/page.vue
Closes #6140. Cleans up group description from HTML or Markdown based on `description_format` field. Loofah is added to the Gemfile, but it's already a sub-dependency so this isn't really adding anything new.
I'm using Loofah instead of [`strip_tags`](https://apidock.com/rails/ActionView/Helpers/SanitizeHelper/strip_tags) because its `to_text` method adds whitespace between tags for clarity. With `strip_tags` this HTML:
```html
<p>Line one</p><p>Line two</p>
``` 
becomes "LineoneLinetwo", while Loofah will return "Line one Line two". Let me know if there's anything I should fix!
> Sanitize group description text from  HTML or Markdown

- app/controllers/identities/nextcloud_controller.rb
- app/extras/clients/nextcloud.rb
- app/models/identities/nextcloud.rb
- config/providers.yml
Loomio must be registered in nextcloud as oauth 2.0 client using https://loomio.example.com/nextcloud/authorize as redirection URL.
In loomio the NEXTCLOUD_HOST environment variable must point to the nextcloud instance, for example https://nextcloud.example.com. NEXTCLOUD_APP_KEY and NEXTCLOUD_APP_SECRET must be set to the client identifier and secret set by nextcloud.
> Add support for using nextcloud as identity provider

- config/locales/client.de.yml
This PR includes some missing german translations for the new vuejs client. It was not clear to me if the old translation workflow is still in use? The translation guide could not be found, because the link on CONTRIBUTING.md is broken.
> Sync german client language file; add missing translations

- Gemfile.lock
> Revert "Bump sentry-ruby from 4.0.1 to 4.1.0"

- config/locales/client.en.yml
- vue/src/components/dashboard/polls_panel.vue
We were facing an issue where people checked their dashboards and after seeing only the "Recent polls" section didn't understand that there were no pending polls to vote.
This change shows the Pending Polls section even if the user has no pending polls, but instead of the polls list it shows the message "You don't have any pending polls.".
It also changes the sections titles to the component  `v-card-title` to give them more emphasis.
> Display if user has no pending polls to vote

- app/controllers/api/v1/profile_controller.rb
- app/models/concerns/has_avatar.rb
- config/locales/client.en.yml
- config/routes.rb
- vue/src/components/profile/change_picture_form.vue
- vue/src/shared/interfaces/user_records_interface.coffee
Presently, if a user switches to gravatar after uploading their image, they will not be able to switch back from the front-end.
Screenshot:
There are a couple of problems with this PR:
1. When a user chooses something else, say gravatar. For a brief second the "Restore previous upload" shows up. This is a bit ugly.
2. I'm not sure if I'm doing translations correctly. Should I add the key to all the translation files?
3.  What happens if the user doesn't already have an uploaded image?
The problem with 3 is that if the user is having "initials" or "gravatar", there is no way for the frontend to know if an upload already exists. Maybe once an API is built for that we can use that to check if this option should be made visible or not.
I'm not sure if the vue is good either.
Feel free to …
> Ability to switch to previously uploaded avatar

- app/models/poll.rb
- config/poll_types.yml
- vue/src/components/poll/common/chart/table.vue
- vue/src/components/poll/common/poll_option_form.vue
- vue/src/components/poll/dot_vote/vote_form.vue
- vue/src/components/poll/score/vote_form.vue
- enabled the "meaning" field on dot vote and score poll options.
- added a character counter to help indicate the appropriate length for a poll option name
- updated the vote forms, so that it shows the meaning text while you're voting
- added a number input to the right, and taken the floating number off the slider
- fixed the dot_vote validation messages "you've used too many dots"
> add meaning support to dotvote and score poll_types

- app/controllers/identities/oauth_controller.rb
- app/extras/clients/oauth.rb
- app/models/identities/oauth.rb
- config/providers.yml
- config/routes.rb
all the oauth providers have hard coded specifics, this one should be fully configurable via ENV's
So far here are the ENV's with example data
OAUTH envs with examples
OAUTH_AUTH_URL=https://login.microsoftonline.com/token/oauth2/v2.0/authorize
OAUTH_TOKEN_URL=https://login.microsoftonline.com/token/oauth2/v2.0/token    
OAUTH_PROFILE_URL=https://graph.microsoft.com/v1.0/me 
OAUTH_SCOPE=https://graph.microsoft.com/.default
OAUTH_APP_KEY=clientid
OAUTH_APP_SECRET=secret key
OAUTH_ATTR_UID=id
OAUTH_ATTR_NAME=displayName
OAUTH_ATTR_EMAIL=mail
> generic oauth provider

- app/controllers/api/v1/stances_controller.rb
- app/models/stance.rb
- app/services/stance_service.rb
- spec/controllers/api/v1/stances_controller_spec.rb
If a user changes their position, we create a new stance record, so that replies to the existing stance still make sense, and new discussion can happen branching from the new stance
> If a user changes their position, we create a new stance record

- config/locales/client.en.yml
- vue/src/components/poll/common/form.vue
- vue/src/components/poll/common/poll_option_form.vue
- vue/tests/e2e/specs/poll.js
This is because many people did not realise there was an option 'meaning' which handles long information much better than option name.
This way, we can reference detailed options by name, and only show detail when user is voting.
Very long names are really hard to work with throughout the UI - so we must encourage use of the meaning field
> Change 'add option' ui from a name field, to a button that opens the poll_option_form

- app/models/ability/discussion.rb
- app/services/discussion_service.rb
- vue/src/components/strand/members_list.vue
- vue/src/shared/services/ability_service.coffee
This reverts the change that gives members more permissions in an invite only thread.
This way, we preserve the ability to control the level of access in an invite only thread, but default to permissive. It also maintains continuity with admin/members throughout the app.
> Invite people as admins to invite-only threads

- app/controllers/api/b2/memberships_controller.rb
- app/models/ability/group.rb
- spec/controllers/api/b2/memberships_controller_spec.rb
When using the API to manage memberships is very inconvenient to have to add bots to every group and make them admin of the group in order to be able to manage members programmatically. This generates noise because for every group people will be able to see the bot users as members.
Considering that global admins are already able to manage the application from the admin interface, it would make sense that they can also have more permissions when using the API.
This patch allows users that are global admins of the application to be able to manage users of any group when using the API.
This is a proposal and I understand if you don't want to accept it, but we ended up adding it downstream to our instance so I decided to send it here in case you find it useful too :)
> Allow admins to manage memberships of any group

- app/models/ability/poll.rb
- spec/models/ability/poll_spec.rb
- vue/src/shared/services/ability_service.js
- vue/src/shared/services/poll_service.js
I cannot explain why we had complicated logic around this, so I'm removing the case where non admins of a poll could announce/remind a poll
> simplify the logic about announcing a poll

- app/controllers/api/v1/polls_controller.rb
- config/routes.rb
- vue/package-lock.json
- vue/src/components/poll/common/chart/panel.vue
- vue/src/components/poll/common/chart/table.vue
- vue/src/shared/models/reaction_model.js
- vue/src/shared/models/user_model.js
- vue/src/shared/record_store/base_records_interface.js
- vue/src/shared/services/ability_service.js
We do this because it's faster, and less work for the client, also we were generating errors for polls with lots of voters when the GET string was too long fetching users by id
> dont lazyload users, rather fetch all users for a poll when we show it.

- app/controllers/api/v1/announcements_controller.rb
- app/extras/user_inviter.rb
- app/models/group.rb
- app/models/subscription.rb
- app/serializers/group_serializer.rb
- app/views/admin/groups/_stats.haml
- app/views/groups/stats.html.haml
- config/routes.rb
- spec/models/group_spec.rb
- vue/src/components/group/invitation_form.vue
previously we were inaccurate when inviting people who already belonged to a subgroup or parent group
> fix invitations remaining

- app/services/membership_service.rb
- app/workers/migrate_discussion_readers_for_deactivated_members_worker.rb
- db/migrate/20241116031145_revoke_discussion_readers_for_revoked_memberships.rb
- db/schema.rb
- spec/services/membership_service_spec.rb
This fixes an issue where you could invite 'everyone in thread' to a poll and it would invite people who had been removed from the group
> revoke discussion readers for revoked memberships.

- app/extras/app_config.rb
- app/services/received_email_service.rb
- vue/src/shared/services/group_service.js
Resolves #10112 
Adds `FEATURES_DISABLE_THREAD_FROM_MAIL` env which is used to hide/show the group email action. GUI part is tested, but I could not test the changes to `received_email_service.rb` because I don't have mail set up in my development environment. Would appreciate if someone else could try if threads are still created when mail is incoming or not when the flag is disabled or enabled (I don't think me setting up local mail is worth this).
Alternatively, discarding `received_email_service.rb`  changes might also be an option?
> Env toggle for thread from mail feature

- vue/src/components/common/action_dock.vue
- vue/src/components/reaction/display.vue
If a thread is closed the user shouldn't be able to send reactions but they should be able to see the existing ones.
> Fix reaction display

- app/admin/groups.rb
Allow admins to edit groups visibility from the admin UI, this way they can manage this setting without needing to be member of the group.
> admin: allow to edit group visibility
